# SuperADD — exact upstream reproduction + AU-PRO\(_{0.05}\) + MVTec AD 2 submission

Notebook này **không sửa `model.py`, không đổi backbone, không đổi post-processing, không tự tối ưu threshold**.

- Upstream: `LukasRoom/SuperADD`
- Pin commit: `44cf25144442fbbc1334ea59d1632327a4376d1a`
- Public benchmark để đối chiếu paper: **AU-ROC\(_{0.05}\)** + **Segmentation F1** do chính `test-industrial` của SuperADD tính.
- Metric bổ sung cho nghiên cứu: **AU-PRO\(_{0.05}\)** trên toàn bộ `test_public` (good + bad).
- Submission MVTec AD 2: chạy `test_private` + `test_private_mixed`, xuất **float16 TIFF** và **binary PNG**, rồi dùng chính `submit-industrial`.

> Quan trọng: paper SuperADD báo **AU-ROC\(_{0.05}\)**, không phải AU-PRO\(_{0.05}\). Vì vậy không được so AU-PRO với cột AU-ROC của paper.

## 1. Mount Drive và khai báo đường dẫn

In [ ]:
from google.colab import drive
drive.mount("/content/drive", force_remount=False)

from pathlib import Path
import os, sys, json, shutil, subprocess, hashlib, tarfile
from pathlib import PurePosixPath

PROJECT_DRIVE = Path("/content/drive/MyDrive/[Q3-4] 2026/[S7] Computer Vision/CV-Nhóm 9")

ARCHIVE_DIR = PROJECT_DRIVE / "data"
DINO_WEIGHT_DIR = PROJECT_DRIVE / "weights"
PRETRAINED_CACHE = PROJECT_DRIVE / "superadd_pretrained" / "models"
DRIVE_OUT = PROJECT_DRIVE / "superadd_results_exact"

REPO = Path("/content/SuperADD")
DATA_ROOT = REPO / "data" / "mvtec_ad_2"

COMMIT = "44cf25144442fbbc1334ea59d1632327a4376d1a"

CATEGORIES = [
    #"can",
    #"fabric",
    #"fruit_jelly",
    "rice",
    #"sheet_metal", "vial", "wallplugs", "walnuts"
]

PUBLIC_SPLIT = ["test_public"]
PRIVATE_SPLITS = ["test_private", "test_private_mixed"]

assert ARCHIVE_DIR.is_dir(), ARCHIVE_DIR
assert DINO_WEIGHT_DIR.is_dir(), DINO_WEIGHT_DIR

DRIVE_OUT.mkdir(parents=True, exist_ok=True)
PRETRAINED_CACHE.mkdir(parents=True, exist_ok=True)

print("Project :", PROJECT_DRIVE)
print("Archives:", ARCHIVE_DIR)
print("Weights :", DINO_WEIGHT_DIR)
print("Output  :", DRIVE_OUT)

Mounted at /content/drive
Project : /content/drive/MyDrive/[Q3-4] 2026/[S7] Computer Vision/CV-Nhóm 9
Archives: /content/drive/MyDrive/[Q3-4] 2026/[S7] Computer Vision/CV-Nhóm 9/data
Weights : /content/drive/MyDrive/[Q3-4] 2026/[S7] Computer Vision/CV-Nhóm 9/weights
Output  : /content/drive/MyDrive/[Q3-4] 2026/[S7] Computer Vision/CV-Nhóm 9/superadd_results_exact

## 2. Clone đúng commit và cài đúng workspace bằng `uv`

In [ ]:
def run(cmd, cwd=None, env=None):
    cmd = [str(x) for x in cmd]
    print("$", " ".join(cmd))
    return subprocess.run(cmd, cwd=cwd, env=env, check=True)

run(["nvidia-smi"])

if REPO.exists():
    shutil.rmtree(REPO)

run(["git", "clone", "https://github.com/LukasRoom/SuperADD.git", REPO])
run(["git", "checkout", "--detach", COMMIT], cwd=REPO)

actual = subprocess.check_output(["git", "rev-parse", "HEAD"], cwd=REPO, text=True).strip()
assert actual == COMMIT, (actual, COMMIT)

run([sys.executable, "-m", "pip", "install", "-q", "uv"])
UV = shutil.which("uv")
assert UV is not None

run([UV, "sync", "--locked", "--all-packages", "--python", "3.11"], cwd=REPO)

dirty = subprocess.check_output(["git", "status", "--porcelain"], cwd=REPO, text=True).strip()
assert dirty == "", f"Source vừa clone đã bị thay đổi:\n{dirty}"

print("SUPERADD SOURCE: PASS", actual)

$ nvidia-smi
$ git clone https://github.com/LukasRoom/SuperADD.git /content/SuperADD
$ git checkout --detach 44cf25144442fbbc1334ea59d1632327a4376d1a
$ /usr/bin/python3 -m pip install -q uv
$ /usr/local/bin/uv sync --locked --all-packages --python 3.11
SUPERADD SOURCE: PASS 44cf25144442fbbc1334ea59d1632327a4376d1a

## 3. Giải nén đúng 3 split cần dùng

In [ ]:
SPLITS_NEEDED = {"test_public", "test_private", "test_private_mixed"}

def extract_selected_splits(archive: Path, destination: Path, splits=SPLITS_NEEDED):
    destination.mkdir(parents=True, exist_ok=True)

    for split in splits:
        shutil.rmtree(destination / split, ignore_errors=True)

    copied = {s: 0 for s in splits}

    with tarfile.open(archive, "r:gz") as tf:
        for member in tf.getmembers():
            parts = PurePosixPath(member.name).parts
            split_positions = [i for i, p in enumerate(parts) if p in splits]
            if not split_positions:
                continue

            i = split_positions[0]
            split = parts[i]
            rel_parts = parts[i:]

            if any(p in ("", ".", "..") for p in rel_parts):
                raise RuntimeError(f"Unsafe path: {member.name}")

            target = destination.joinpath(*rel_parts)

            if member.isdir():
                target.mkdir(parents=True, exist_ok=True)
                continue

            if not member.isfile():
                raise RuntimeError(f"Unsupported archive entry: {member.name}")

            target.parent.mkdir(parents=True, exist_ok=True)
            src = tf.extractfile(member)
            if src is None:
                raise RuntimeError(member.name)

            with src, open(target, "wb") as dst:
                shutil.copyfileobj(src, dst, length=8 * 1024 * 1024)

            copied[split] += 1

    for split in splits:
        assert (destination / split).exists(), f"Thiếu {destination/split}"
        assert copied[split] > 0, f"Không extract được file cho {split} từ {archive.name}"

    return copied

archives = {p.name[:-7]: p for p in ARCHIVE_DIR.glob("*.tar.gz")}
missing = set(CATEGORIES) - set(archives)
assert not missing, f"Thiếu archive: {sorted(missing)}"

DATA_ROOT.mkdir(parents=True, exist_ok=True)

for category in CATEGORIES:
    print("\n==", category, "==")
    counts = extract_selected_splits(archives[category], DATA_ROOT / category)
    print(counts)

for c in CATEGORIES:
    pub = DATA_ROOT / c / "test_public"
    assert list((pub / "bad").glob("*.png")), f"{c}: thiếu public/bad"
    assert list((pub / "good").glob("*.png")), f"{c}: thiếu public/good"
    assert list((pub / "ground_truth" / "bad").glob("*_mask.png")), f"{c}: thiếu GT"
    assert list((DATA_ROOT / c / "test_private").glob("*.png")), f"{c}: thiếu private"
    assert list((DATA_ROOT / c / "test_private_mixed").glob("*.png")), f"{c}: thiếu private_mixed"

print("\nDATASET: PASS", DATA_ROOT)

== rice ==
{'test_public': 222, 'test_private_mixed': 277, 'test_private': 277}

DATASET: PASS /content/SuperADD/data/mvtec_ad_2

## 4. DINOv3 checkpoint + pretrained SuperADD memory banks

In [ ]:
import requests
from tqdm.auto import tqdm
import numpy as np

weight_candidates = sorted(DINO_WEIGHT_DIR.glob("dinov3_vith16plus_pretrain_*.pth"))
assert len(weight_candidates) == 1, (
    "Cần đúng 1 checkpoint dinov3_vith16plus_pretrain_*.pth trong "
    f"{DINO_WEIGHT_DIR}; hiện có {weight_candidates}"
)

(REPO / "weights").mkdir(exist_ok=True)

weight_src = weight_candidates[0]
weight_dst = REPO / "weights" / weight_src.name

if not weight_dst.exists() or weight_dst.stat().st_size != weight_src.stat().st_size:
    shutil.copy2(weight_src, weight_dst)

assert weight_dst.stat().st_size > 100_000_000, "Checkpoint quá nhỏ / sai file."
print("DINO:", weight_dst.name, f"{weight_dst.stat().st_size/2**30:.2f} GiB")


PUBLIC_SHARE = "https://owncloud.fraunhofer.de/index.php/s/THkX7W8AhRd2RCs/download"

def download_pretrained_file(filename: str, dst: Path):
    if dst.exists() and dst.stat().st_size > 0:
        return

    tmp = dst.with_suffix(dst.suffix + ".part")
    tmp.unlink(missing_ok=True)

    with requests.get(
        PUBLIC_SHARE,
        params={"path": "/", "files": filename},
        stream=True,
        timeout=(30, 300),
    ) as r:
        r.raise_for_status()
        total = int(r.headers.get("Content-Length", 0))

        with open(tmp, "wb") as f, tqdm(
            total=total or None, unit="B", unit_scale=True, desc=filename
        ) as bar:
            for chunk in r.iter_content(8 * 1024 * 1024):
                if chunk:
                    f.write(chunk)
                    bar.update(len(chunk))

    assert tmp.stat().st_size > 0
    tmp.replace(dst)

def validate_model_pair(category: str, folder: Path):
    jp = folder / f"{category}.json"
    npz = folder / f"{category}.npz"

    meta = json.loads(jp.read_text())
    assert "constructor" in meta and "trained" in meta

    ctor = meta["constructor"]
    assert ctor["backbone"] == "dinov3_vith16plus"
    assert ctor["layers"] == [7, 15, 23, 31]
    assert int(ctor["patch_size"]) == 640
    assert int(ctor["patch_overlap"]) == 128

    z = np.load(npz)
    assert set(z.files) == {"7", "15", "23", "31"}, z.files
    z.close()

    return float(meta["trained"]["threshold"])

for category in CATEGORIES:
    for suffix in (".json", ".npz"):
        p = PRETRAINED_CACHE / f"{category}{suffix}"
        download_pretrained_file(p.name, p)

    thr = validate_model_pair(category, PRETRAINED_CACHE)
    print(category, "threshold =", thr)

(REPO / "models").mkdir(exist_ok=True)

for category in CATEGORIES:
    for suffix in (".json", ".npz"):
        src = PRETRAINED_CACHE / f"{category}{suffix}"
        dst = REPO / "models" / src.name

        if not dst.exists() or dst.stat().st_size != src.stat().st_size:
            shutil.copy2(src, dst)

print("PRETRAINED MODELS: PASS")

DINO: dinov3_vith16plus_pretrain_lvd1689m-7c1da9a5.pth 3.13 GiB
rice threshold = 0.8007440567016602
PRETRAINED MODELS: PASS

## 5. Hàm ghi config

Chỉ thay **đường dẫn, split, category, cờ lưu prediction**. Các tham số model khi load pretrained được đọc từ `models/<category>.json`.

Để khớp `test.py` của SuperADD và Table 1 paper, public evaluation dùng `evaluate_good_images = false`.

In [ ]:
UPSTREAM_CONFIG = json.loads(
    subprocess.check_output(
        ["git", "show", f"{COMMIT}:config.json"],
        cwd=REPO,
        text=True
    )
)

def write_config(results_dir: str, test_split):
    cfg = dict(UPSTREAM_CONFIG)

    cfg.update({
        "datasets_dir": "./data/",
        "dino_weights_dir": "./weights/",
        "models_dir": "./models/",
        "results_dir": results_dir,
        "submissions_dir": "./submissions/",
        "categories": CATEGORIES,
        "test_split": list(test_split),
        "save_predictions": True,
        "evaluate_good_images": False,
    })

    (REPO / "config.json").write_text(json.dumps(cfg, indent=4))
    return cfg

cfg = write_config("./outputs_public/", PUBLIC_SPLIT)
print(json.dumps(cfg, indent=2))

{
  "datasets_dir": "./data/",
  "dino_weights_dir": "./weights/",
  "models_dir": "./models/",
  "results_dir": "./outputs_public/",
  "submissions_dir": "./submissions/",
  "categories": [
    "rice"
  ],
  "train_fraction": 1,
  "threshold_fraction": 8,
  "brightness_augmentation": [
    0.8,
    1.2
  ],
  "patch_size": 640,
  "patch_overlap": 128,
  "backbone": "dinov3_vith16plus",
  "layers": [
    7,
    15,
    23,
    31
  ],
  "max_database_size": 100000,
  "subsampling_iterations": 100,
  "threshold_percentile": 95,
  "threshold_factor": 1.421,
  "evaluation_downscale": 4,
  "closing_radius": 26,
  "closing_angles": 16,
  "closing_lower_threshold": 0.8,
  "binary_erosion": 1,
  "test_split": [
    "test_public"
  ],
  "save_predictions": true,
  "evaluate_good_images": false
}

## 6. Public — chạy **đúng `test-industrial` của SuperADD**

Kết quả dùng để đối chiếu paper:
- cột `AU` = pixel-level standardized partial **AU-ROC\(_{0.05}\)**
- cột `F1` = F1 của **binary map do threshold/post-processing SuperADD sinh ra**

In [ ]:
PUBLIC_OUT = REPO / "outputs_public"
shutil.rmtree(PUBLIC_OUT, ignore_errors=True)
PUBLIC_OUT.mkdir(parents=True, exist_ok=True)

import pandas as pd
import subprocess, os

def run_streamed(cmd, cwd=None, env=None, tail_n=100):
    cmd = [str(x) for x in cmd]
    print("$", " ".join(cmd), flush=True)

    merged_env = os.environ.copy()
    merged_env["MPLBACKEND"] = "Agg"

    if env:
        merged_env.update(env)

    merged_env["PYTHONUNBUFFERED"] = "1"

    p = subprocess.Popen(
        cmd,
        cwd=cwd,
        env=merged_env,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        text=True,
        bufsize=1,
    )

    tail = []
    assert p.stdout is not None

    for line in p.stdout:
        print(line, end="", flush=True)
        tail.append(line)
        if len(tail) > tail_n:
            tail.pop(0)

    rc = p.wait()
    if rc != 0:
        raise RuntimeError(
            f"\\n[FAILED returncode={rc}]\\n" + "".join(tail)
        )
    return rc

category_rows = []

for category in CATEGORIES:
    print("\\n" + "=" * 80)
    print("PUBLIC CATEGORY:", category)
    print("=" * 80)

    cfg = write_config("./outputs_public/", ["test_public"])
    cfg["categories"] = [category]
    cfg["evaluate_good_images"] = False
    cfg["save_predictions"] = True
    (REPO / "config.json").write_text(json.dumps(cfg, indent=4))

    score_csv = PUBLIC_OUT / "scores_test_public.csv"
    score_csv.unlink(missing_ok=True)

    try:
        run_streamed(
            [UV, "run", "--no-sync", "test-industrial"],
            cwd=REPO,
        )
    except Exception:
        print("\\nFAILED CATEGORY =", category)
        print("GPU state:")
        subprocess.run(["nvidia-smi"])
        raise

    assert score_csv.is_file(), f"Không tạo được {score_csv}"

    one = pd.read_csv(score_csv)
    one = one.loc[:, ~one.columns.str.startswith("Unnamed")]

    row = one[one["Category"] == category]
    assert len(row) == 1, one
    category_rows.append(row.iloc[0].to_dict())

scores = pd.DataFrame(category_rows, columns=["Category", "AU", "F1"])
scores.loc[len(scores)] = [
    "mean",
    scores["AU"].mean(),
    scores["F1"].mean(),
]
scores.to_csv(PUBLIC_OUT / "scores_test_public.csv", index=False)

paper = pd.DataFrame({
    "Category": [
        "can", "fabric", "fruit_jelly", "rice",
        "sheet_metal", "vial", "wallplugs", "walnuts", "mean"
    ],
    "Paper_AUROC005_pct": [
        51.61, 84.20, 81.19, 96.11,
        93.18, 82.59, 92.53, 90.03, 83.93
    ],
    "Paper_F1_pct": [
        0.00, 93.74, 54.68, 73.31,
        59.54, 64.77, 79.16, 75.69, 62.61
    ],
})

report = scores.copy()
report["AUROC005_pct"] = report["AU"] * 100
report["F1_pct"] = report["F1"] * 100
report = report.merge(paper, on="Category", how="left")
report["d_AUROC005_pp"] = (
    report["AUROC005_pct"] - report["Paper_AUROC005_pct"]
)
report["d_F1_pp"] = (
    report["F1_pct"] - report["Paper_F1_pct"]
)

display(report[[
    "Category",
    "AUROC005_pct", "Paper_AUROC005_pct", "d_AUROC005_pp",
    "F1_pct", "Paper_F1_pct", "d_F1_pp",
]])

report.to_csv(
    PUBLIC_OUT / "paper_comparison_test_public.csv",
    index=False,
)

print("\\nPUBLIC TEST FINISHED.")

\n================================================================================
PUBLIC CATEGORY: rice
================================================================================
$ /usr/local/bin/uv run --no-sync test-industrial

processing split test_public
Downloading: "https://github.com/facebookresearch/dinov3/zipball/main" to /root/.cache/torch/hub/main.zip
Downloading: "file:///content/SuperADD/weights/dinov3_vith16plus_pretrain_lvd1689m-7c1da9a5.pth" to /root/.cache/torch/hub/checkpoints/dinov3_vith16plus_pretrain_lvd1689m-7c1da9a5.pth

  0%|          | 0.00/3.13G [00:00<?, ?B/s]
  1%|          | 19.1M/3.13G [00:00<00:16, 201MB/s]
  1%|          | 39.8M/3.13G [00:00<00:15, 210MB/s]
  2%|▏         | 61.8M/3.13G [00:00<00:15, 219MB/s]
  3%|▎         | 82.8M/3.13G [00:00<00:17, 185MB/s]
  3%|▎         | 105M/3.13G [00:00<00:16, 202MB/s]
  4%|▍         | 125M/3.13G [00:00<00:18, 175MB/s]
  5%|▍         | 147M/3.13G [00:00<00:16, 191MB/s]
  5%|▌         | 173M/3.13G [00:00<00:14, 214MB/s]
  6%|▌         | 194M/3.13G [00:01<00:15, 209MB/s]
  7%|▋         | 223M/3.13G [00:01<00:13, 236MB/s]
  8%|▊         | 246M/3.13G [00:01<00:14, 213MB/s]
  8%|▊         | 270M/3.13G [00:01<00:13, 223MB/s]
  9%|▉         | 293M/3.13G [00:01<00:13, 227MB/s]
 10%|▉         | 318M/3.13G [00:01<00:12, 235MB/s]
 11%|█         | 340M/3.13G [00:01<00:14, 201MB/s]
 11%|█▏        | 362M/3.13G [00:01<00:14, 207MB/s]
 12%|█▏        | 390M/3.13G [00:01<00:12, 230MB/s]
 13%|█▎        | 413M/3.13G [00:02<00:13, 217MB/s]
 14%|█▎        | 440M/3.13G [00:02<00:12, 236MB/s]
 15%|█▍        | 470M/3.13G [00:02<00:11, 255MB/s]
 15%|█▌        | 494M/3.13G [00:02<00:11, 241MB/s]
 16%|█▌        | 518M/3.13G [00:02<00:12, 229MB/s]
 17%|█▋        | 540M/3.13G [00:02<00:12, 227MB/s]
 18%|█▊        | 564M/3.13G [00:02<00:11, 234MB/s]
 18%|█▊        | 590M/3.13G [00:02<00:11, 242MB/s]
 19%|█▉        | 614M/3.13G [00:02<00:11, 242MB/s]
 20%|█▉        | 638M/3.13G [00:02<00:11, 243MB/s]
 21%|██        | 661M/3.13G [00:04<00:40, 65.4MB/s]
 21%|██        | 678M/3.13G [00:06<01:43, 25.6MB/s]
 22%|██▏       | 703M/3.13G [00:06<01:12, 36.5MB/s]
 23%|██▎       | 728M/3.13G [00:06<00:51, 50.1MB/s]
 23%|██▎       | 747M/3.13G [00:06<00:43, 59.0MB/s]
 24%|██▍       | 767M/3.13G [00:06<00:34, 74.1MB/s]
 24%|██▍       | 785M/3.13G [00:06<00:29, 86.9MB/s]
 25%|██▌       | 803M/3.13G [00:06<00:24, 102MB/s]
 26%|██▌       | 820M/3.13G [00:06<00:22, 109MB/s]
 26%|██▋       | 845M/3.13G [00:07<00:18, 138MB/s]
 27%|██▋       | 864M/3.13G [00:07<00:17, 140MB/s]
 28%|██▊       | 884M/3.13G [00:07<00:15, 155MB/s]
 28%|██▊       | 904M/3.13G [00:07<00:14, 169MB/s]
 29%|██▉       | 923M/3.13G [00:07<00:13, 177MB/s]
 29%|██▉       | 942M/3.13G [00:07<00:13, 179MB/s]
 30%|██▉       | 961M/3.13G [00:07<00:12, 182MB/s]
 31%|███       | 979M/3.13G [00:07<00:20, 116MB/s]
 31%|███       | 994M/3.13G [00:10<01:42, 22.6MB/s]
 31%|███▏      | 0.98G/3.13G [00:10<01:26, 26.7MB/s]
 32%|███▏      | 1.00G/3.13G [00:10<01:00, 38.0MB/s]
 32%|███▏      | 1.02G/3.13G [00:10<00:44, 51.2MB/s]
 33%|███▎      | 1.04G/3.13G [00:10<00:30, 74.5MB/s]
 34%|███▍      | 1.06G/3.13G [00:10<00:25, 88.9MB/s]
 35%|███▍      | 1.08G/3.13G [00:10<00:18, 117MB/s]
 35%|███▌      | 1.11G/3.13G [00:11<00:15, 142MB/s]
 36%|███▌      | 1.13G/3.13G [00:11<00:12, 167MB/s]
 37%|███▋      | 1.16G/3.13G [00:11<00:11, 189MB/s]
 38%|███▊      | 1.18G/3.13G [00:11<00:10, 202MB/s]
 38%|███▊      | 1.20G/3.13G [00:11<00:09, 215MB/s]
 39%|███▉      | 1.22G/3.13G [00:11<00:10, 187MB/s]
 40%|███▉      | 1.25G/3.13G [00:11<00:10, 200MB/s]
 41%|████      | 1.27G/3.13G [00:11<00:09, 215MB/s]
 41%|████▏     | 1.30G/3.13G [00:11<00:08, 229MB/s]
 42%|████▏     | 1.32G/3.13G [00:12<00:08, 232MB/s]
 43%|████▎     | 1.34G/3.13G [00:12<00:08, 225MB/s]
 44%|████▎     | 1.37G/3.13G [00:12<00:07, 238MB/s]
 45%|████▍     | 1.39G/3.13G [00:12<00:07, 254MB/s]
 45%|████▌     | 1.42G/3.13G [00:12<00:06, 273MB/s]
 46%|████▋     | 1.45G/3.13G [00:12<00:07, 236MB/s]
 47%|████▋     | 1.47G/3.13G [00:12<00:09, 197MB/s]
 48%|████▊     | 1.49G/3.13G [00:12<00:08, 203MB/s]
 49%|████▊     | 1.52G/3.13G [00:12<00:07, 231MB/s]
 49%|████▉     | 1.55G/3.13G [00:13<00:07, 214MB/s]
 50%|█████     | 1.57G/3.13G [00:13<00:08, 210MB/s]
 51%|█████     | 1.59G/3.13G [00:13<00:08, 200MB/s]
 51%|█████▏    | 1.61G/3.13G [00:13<00:08, 203MB/s]
 52%|█████▏    | 1.63G/3.13G [00:13<00:07, 211MB/s]
 53%|█████▎    | 1.66G/3.13G [00:13<00:07, 224MB/s]
 54%|█████▎    | 1.68G/3.13G [00:13<00:06, 226MB/s]
 54%|█████▍    | 1.70G/3.13G [00:13<00:06, 235MB/s]
 55%|█████▌    | 1.72G/3.13G [00:16<00:50, 30.1MB/s]
 56%|█████▌    | 1.75G/3.13G [00:16<00:32, 45.2MB/s]
 57%|█████▋    | 1.79G/3.13G [00:16<00:22, 64.9MB/s]
 58%|█████▊    | 1.81G/3.13G [00:16<00:18, 78.6MB/s]
 58%|█████▊    | 1.83G/3.13G [00:16<00:14, 95.7MB/s]
 59%|█████▉    | 1.85G/3.13G [00:16<00:12, 113MB/s]
 60%|█████▉    | 1.87G/3.13G [00:17<00:10, 123MB/s]
 61%|██████    | 1.90G/3.13G [00:17<00:09, 134MB/s]
 61%|██████▏   | 1.92G/3.13G [00:17<00:07, 165MB/s]
 62%|██████▏   | 1.95G/3.13G [00:17<00:06, 194MB/s]
 63%|██████▎   | 1.98G/3.13G [00:17<00:06, 191MB/s]
 64%|██████▍   | 2.00G/3.13G [00:17<00:05, 205MB/s]
 65%|██████▍   | 2.02G/3.13G [00:17<00:05, 208MB/s]
 65%|██████▌   | 2.04G/3.13G [00:17<00:05, 217MB/s]
 66%|██████▌   | 2.07G/3.13G [00:18<00:17, 65.1MB/s]
 66%|██████▋   | 2.08G/3.13G [00:20<00:39, 28.2MB/s]
 67%|██████▋   | 2.09G/3.13G [00:20<00:34, 32.6MB/s]
 67%|██████▋   | 2.10G/3.13G [00:20<00:29, 37.7MB/s]
 68%|██████▊   | 2.11G/3.13G [00:20<00:25, 43.3MB/s]
 68%|██████▊   | 2.12G/3.13G [00:21<00:23, 45.4MB/s]
 68%|██████▊   | 2.14G/3.13G [00:21<00:17, 61.4MB/s]
 69%|██████▉   | 2.16G/3.13G [00:21<00:12, 82.0MB/s]
 70%|██████▉   | 2.18G/3.13G [00:21<00:09, 105MB/s]
 70%|███████   | 2.20G/3.13G [00:21<00:08, 125MB/s]
 71%|███████   | 2.21G/3.13G [00:21<00:08, 117MB/s]
 71%|███████▏  | 2.23G/3.13G [00:21<00:07, 134MB/s]
 72%|███████▏  | 2.25G/3.13G [00:21<00:06, 147MB/s]
 72%|███████▏  | 2.27G/3.13G [00:21<00:05, 156MB/s]
 73%|███████▎  | 2.29G/3.13G [00:22<00:05, 174MB/s]
 74%|███████▍  | 2.31G/3.13G [00:22<00:04, 202MB/s]
 75%|███████▍  | 2.33G/3.13G [00:22<00:04, 185MB/s]
 75%|███████▌  | 2.35G/3.13G [00:22<00:04, 191MB/s]
 76%|███████▌  | 2.38G/3.13G [00:22<00:03, 213MB/s]
 77%|███████▋  | 2.41G/3.13G [00:22<00:03, 242MB/s]
 78%|███████▊  | 2.43G/3.13G [00:22<00:03, 222MB/s]
 78%|███████▊  | 2.46G/3.13G [00:22<00:03, 232MB/s]
 79%|███████▉  | 2.48G/3.13G [00:23<00:03, 179MB/s]
 80%|███████▉  | 2.50G/3.13G [00:23<00:04, 150MB/s]
 80%|████████  | 2.51G/3.13G [00:23<00:04, 150MB/s]
 81%|████████  | 2.53G/3.13G [00:26<00:34, 18.8MB/s]
 82%|████████▏ | 2.56G/3.13G [00:26<00:20, 30.4MB/s]
 83%|████████▎ | 2.59G/3.13G [00:26<00:13, 44.4MB/s]
 83%|████████▎ | 2.61G/3.13G [00:26<00:10, 55.1MB/s]
 84%|████████▍ | 2.63G/3.13G [00:27<00:07, 73.3MB/s]
 85%|████████▍ | 2.65G/3.13G [00:27<00:05, 89.7MB/s]
 85%|████████▌ | 2.68G/3.13G [00:27<00:04, 113MB/s]
 86%|████████▌ | 2.70G/3.13G [00:27<00:03, 123MB/s]
 87%|████████▋ | 2.72G/3.13G [00:27<00:02, 148MB/s]
 88%|████████▊ | 2.74G/3.13G [00:27<00:02, 167MB/s]
 88%|████████▊ | 2.77G/3.13G [00:27<00:02, 192MB/s]
 89%|████████▉ | 2.79G/3.13G [00:27<00:01, 201MB/s]
 90%|████████▉ | 2.82G/3.13G [00:27<00:01, 216MB/s]
 91%|█████████ | 2.84G/3.13G [00:28<00:01, 218MB/s]
 91%|█████████▏| 2.86G/3.13G [00:28<00:01, 227MB/s]
 92%|█████████▏| 2.89G/3.13G [00:28<00:01, 234MB/s]
 93%|█████████▎| 2.91G/3.13G [00:28<00:01, 224MB/s]
 94%|█████████▎| 2.93G/3.13G [00:28<00:00, 229MB/s]
 94%|█████████▍| 2.95G/3.13G [00:28<00:01, 169MB/s]
 95%|█████████▍| 2.97G/3.13G [00:29<00:02, 80.8MB/s]
 95%|█████████▌| 2.99G/3.13G [00:29<00:01, 89.1MB/s]
 96%|█████████▌| 3.00G/3.13G [00:30<00:03, 36.2MB/s]
 96%|█████████▋| 3.01G/3.13G [00:30<00:02, 44.9MB/s]
 97%|█████████▋| 3.03G/3.13G [00:30<00:01, 58.7MB/s]
 98%|█████████▊| 3.06G/3.13G [00:30<00:00, 89.4MB/s]
 98%|█████████▊| 3.08G/3.13G [00:31<00:00, 110MB/s]
 99%|█████████▉| 3.10G/3.13G [00:31<00:00, 122MB/s]
100%|█████████▉| 3.12G/3.13G [00:31<00:00, 133MB/s]
100%|██████████| 3.13G/3.13G [00:31<00:00, 107MB/s]

processing rice images:   0%|          | 0/132 [00:00<?, ?it/s]
processing rice images:   1%|          | 1/132 [00:00<00:41,  3.14it/s]
processing rice images:   2%|▏         | 2/132 [00:00<00:40,  3.21it/s]
processing rice images:   2%|▏         | 3/132 [00:00<00:39,  3.27it/s]
processing rice images:   3%|▎         | 4/132 [00:01<00:39,  3.25it/s]
processing rice images:   4%|▍         | 5/132 [00:01<00:38,  3.28it/s]
processing rice images:   5%|▍         | 6/132 [00:01<00:38,  3.29it/s]
processing rice images:   5%|▌         | 7/132 [00:02<00:39,  3.17it/s]
processing rice images:   6%|▌         | 8/132 [00:02<00:38,  3.22it/s]
processing rice images:   7%|▋         | 9/132 [00:02<00:37,  3.26it/s]
processing rice images:   8%|▊         | 10/132 [00:03<00:37,  3.26it/s]
processing rice images:   8%|▊         | 11/132 [00:03<00:37,  3.22it/s]
processing rice images:   9%|▉         | 12/132 [00:03<00:37,  3.24it/s]
processing rice images:  10%|▉         | 13/132 [00:04<00:36,  3.27it/s]
processing rice images:  11%|█         | 14/132 [00:04<00:36,  3.26it/s]
processing rice images:  11%|█▏        | 15/132 [00:04<00:37,  3.10it/s]
processing rice images:  12%|█▏        | 16/132 [00:05<00:40,  2.86it/s]
processing rice images:  13%|█▎        | 17/132 [00:05<00:42,  2.69it/s]
processing rice images:  14%|█▎        | 18/132 [00:05<00:44,  2.56it/s]
processing rice images:  14%|█▍        | 19/132 [00:06<00:45,  2.49it/s]
processing rice images:  15%|█▌        | 20/132 [00:06<00:45,  2.46it/s]
processing rice images:  16%|█▌        | 21/132 [00:07<00:45,  2.44it/s]
processing rice images:  17%|█▋        | 22/132 [00:07<00:45,  2.40it/s]
processing rice images:  17%|█▋        | 23/132 [00:08<00:45,  2.40it/s]
processing rice images:  18%|█▊        | 24/132 [00:08<00:45,  2.38it/s]
processing rice images:  19%|█▉        | 25/132 [00:08<00:45,  2.37it/s]
processing rice images:  20%|█▉        | 26/132 [00:09<00:42,  2.50it/s]
processing rice images:  20%|██        | 27/132 [00:09<00:39,  2.66it/s]
processing rice images:  21%|██        | 28/132 [00:09<00:36,  2.83it/s]
processing rice images:  22%|██▏       | 29/132 [00:10<00:34,  2.96it/s]
processing rice images:  23%|██▎       | 30/132 [00:10<00:33,  3.04it/s]
processing rice images:  23%|██▎       | 31/132 [00:10<00:32,  3.09it/s]
processing rice images:  24%|██▍       | 32/132 [00:11<00:31,  3.15it/s]
processing rice images:  25%|██▌       | 33/132 [00:11<00:30,  3.20it/s]
processing rice images:  26%|██▌       | 34/132 [00:11<00:30,  3.20it/s]
processing rice images:  27%|██▋       | 35/132 [00:12<00:29,  3.24it/s]
processing rice images:  27%|██▋       | 36/132 [00:12<00:29,  3.27it/s]
processing rice images:  28%|██▊       | 37/132 [00:12<00:29,  3.25it/s]
processing rice images:  29%|██▉       | 38/132 [00:12<00:28,  3.27it/s]
processing rice images:  30%|██▉       | 39/132 [00:13<00:28,  3.29it/s]
processing rice images:  30%|███       | 40/132 [00:13<00:27,  3.30it/s]
processing rice images:  31%|███       | 41/132 [00:13<00:27,  3.27it/s]
processing rice images:  32%|███▏      | 42/132 [00:14<00:27,  3.28it/s]
processing rice images:  33%|███▎      | 43/132 [00:29<07:18,  4.93s/it]
processing rice images:  33%|███▎      | 44/132 [00:44<11:34,  7.89s/it]
processing rice images:  34%|███▍      | 45/132 [01:00<14:43, 10.15s/it]
processing rice images:  35%|███▍      | 46/132 [01:15<16:59, 11.85s/it]
processing rice images:  36%|███▌      | 47/132 [01:31<18:20, 12.95s/it]
processing rice images:  36%|███▋      | 48/132 [01:46<19:07, 13.66s/it]
processing rice images:  37%|███▋      | 49/132 [02:01<19:31, 14.12s/it]
processing rice images:  38%|███▊      | 50/132 [02:17<19:48, 14.49s/it]
processing rice images:  39%|███▊      | 51/132 [02:32<19:59, 14.81s/it]
processing rice images:  39%|███▉      | 52/132 [02:48<19:58, 14.98s/it]
processing rice images:  40%|████      | 53/132 [03:03<19:49, 15.06s/it]
processing rice images:  41%|████      | 54/132 [03:18<19:36, 15.09s/it]
processing rice images:  42%|████▏     | 55/132 [03:33<19:25, 15.13s/it]
processing rice images:  42%|████▏     | 56/132 [03:49<19:11, 15.15s/it]
processing rice images:  43%|████▎     | 57/132 [04:04<18:56, 15.15s/it]
processing rice images:  44%|████▍     | 58/132 [04:19<18:43, 15.18s/it]
processing rice images:  45%|████▍     | 59/132 [04:34<18:28, 15.19s/it]
processing rice images:  45%|████▌     | 60/132 [04:49<18:13, 15.19s/it]
processing rice images:  46%|████▌     | 61/132 [05:05<17:59, 15.21s/it]
processing rice images:  47%|████▋     | 62/132 [05:20<17:46, 15.23s/it]
processing rice images:  48%|████▊     | 63/132 [05:35<17:31, 15.24s/it]
processing rice images:  48%|████▊     | 64/132 [05:51<17:20, 15.30s/it]
processing rice images:  49%|████▉     | 65/132 [06:06<17:09, 15.37s/it]
processing rice images:  50%|█████     | 66/132 [06:22<16:57, 15.41s/it]
processing rice images:  51%|█████     | 67/132 [06:37<16:44, 15.45s/it]
processing rice images:  52%|█████▏    | 68/132 [06:53<16:29, 15.47s/it]
processing rice images:  52%|█████▏    | 69/132 [07:08<16:11, 15.43s/it]
processing rice images:  53%|█████▎    | 70/132 [07:23<15:51, 15.35s/it]
processing rice images:  54%|█████▍    | 71/132 [07:39<15:36, 15.35s/it]
processing rice images:  55%|█████▍    | 72/132 [07:54<15:18, 15.31s/it]
processing rice images:  55%|█████▌    | 73/132 [08:09<15:01, 15.28s/it]
processing rice images:  56%|█████▌    | 74/132 [08:24<14:46, 15.28s/it]
processing rice images:  57%|█████▋    | 75/132 [08:39<14:30, 15.27s/it]
processing rice images:  58%|█████▊    | 76/132 [08:55<14:14, 15.25s/it]
processing rice images:  58%|█████▊    | 77/132 [09:10<13:58, 15.25s/it]
processing rice images:  59%|█████▉    | 78/132 [09:25<13:42, 15.23s/it]
processing rice images:  60%|█████▉    | 79/132 [09:40<13:27, 15.24s/it]
processing rice images:  61%|██████    | 80/132 [09:56<13:12, 15.25s/it]
processing rice images:  61%|██████▏   | 81/132 [10:11<13:00, 15.31s/it]
processing rice images:  62%|██████▏   | 82/132 [10:27<12:47, 15.36s/it]
processing rice images:  63%|██████▎   | 83/132 [10:42<12:33, 15.37s/it]
processing rice images:  64%|██████▎   | 84/132 [10:58<12:20, 15.42s/it]
processing rice images:  64%|██████▍   | 85/132 [11:13<12:05, 15.43s/it]
processing rice images:  65%|██████▌   | 86/132 [11:28<11:47, 15.38s/it]
processing rice images:  66%|██████▌   | 87/132 [11:43<11:29, 15.33s/it]
processing rice images:  67%|██████▋   | 88/132 [11:59<11:12, 15.30s/it]
processing rice images:  67%|██████▋   | 89/132 [12:14<10:56, 15.26s/it]
processing rice images:  68%|██████▊   | 90/132 [12:29<10:39, 15.24s/it]
processing rice images:  69%|██████▉   | 91/132 [12:44<10:24, 15.23s/it]
processing rice images:  70%|██████▉   | 92/132 [12:59<10:08, 15.21s/it]
processing rice images:  70%|███████   | 93/132 [13:15<09:53, 15.22s/it]
processing rice images:  71%|███████   | 94/132 [13:30<09:38, 15.23s/it]
processing rice images:  72%|███████▏  | 95/132 [13:45<09:23, 15.22s/it]
processing rice images:  73%|███████▎  | 96/132 [14:00<09:07, 15.21s/it]
processing rice images:  73%|███████▎  | 97/132 [14:16<08:53, 15.23s/it]
processing rice images:  74%|███████▍  | 98/132 [14:31<08:40, 15.30s/it]
processing rice images:  75%|███████▌  | 99/132 [14:47<08:26, 15.35s/it]
processing rice images:  76%|███████▌  | 100/132 [15:02<08:11, 15.37s/it]
processing rice images:  77%|███████▋  | 101/132 [15:17<07:56, 15.38s/it]
processing rice images:  77%|███████▋  | 102/132 [15:33<07:40, 15.33s/it]
processing rice images:  78%|███████▊  | 103/132 [15:48<07:23, 15.30s/it]
processing rice images:  79%|███████▉  | 104/132 [16:03<07:08, 15.29s/it]
processing rice images:  80%|███████▉  | 105/132 [16:18<06:51, 15.26s/it]
processing rice images:  80%|████████  | 106/132 [16:33<06:36, 15.26s/it]
processing rice images:  81%|████████  | 107/132 [16:49<06:21, 15.25s/it]
processing rice images:  82%|████████▏ | 108/132 [17:04<06:05, 15.22s/it]
processing rice images:  83%|████████▎ | 109/132 [17:19<05:49, 15.22s/it]
processing rice images:  83%|████████▎ | 110/132 [17:34<05:34, 15.23s/it]
processing rice images:  84%|████████▍ | 111/132 [17:49<05:19, 15.22s/it]
processing rice images:  85%|████████▍ | 112/132 [18:05<05:04, 15.22s/it]
processing rice images:  86%|████████▌ | 113/132 [18:20<04:48, 15.20s/it]
processing rice images:  86%|████████▋ | 114/132 [18:35<04:33, 15.20s/it]
processing rice images:  87%|████████▋ | 115/132 [18:50<04:19, 15.26s/it]
processing rice images:  88%|████████▊ | 116/132 [19:06<04:05, 15.33s/it]
processing rice images:  89%|████████▊ | 117/132 [19:21<03:50, 15.37s/it]
processing rice images:  89%|████████▉ | 118/132 [19:37<03:35, 15.41s/it]
processing rice images:  90%|█████████ | 119/132 [19:52<03:19, 15.37s/it]
processing rice images:  91%|█████████ | 120/132 [20:07<03:04, 15.34s/it]
processing rice images:  92%|█████████▏| 121/132 [20:23<02:48, 15.30s/it]
processing rice images:  92%|█████████▏| 122/132 [20:38<02:32, 15.27s/it]
processing rice images:  93%|█████████▎| 123/132 [20:53<02:17, 15.26s/it]
processing rice images:  94%|█████████▍| 124/132 [21:08<02:01, 15.24s/it]
processing rice images:  95%|█████████▍| 125/132 [21:23<01:46, 15.20s/it]
processing rice images:  95%|█████████▌| 126/132 [21:39<01:31, 15.19s/it]
processing rice images:  96%|█████████▌| 127/132 [21:54<01:16, 15.21s/it]
processing rice images:  97%|█████████▋| 128/132 [22:09<01:00, 15.23s/it]
processing rice images:  98%|█████████▊| 129/132 [22:24<00:45, 15.22s/it]
processing rice images:  98%|█████████▊| 130/132 [22:40<00:30, 15.24s/it]
processing rice images:  99%|█████████▉| 131/132 [22:55<00:15, 15.28s/it]
processing rice images: 100%|██████████| 132/132 [23:10<00:00, 15.32s/it]
processing rice images: 100%|██████████| 132/132 [23:10<00:00, 10.54s/it]
category rice: 96.11% (AU), 73.31% (F1)

---------- Results -----------
test_public
  Category        AU        F1
0     rice  0.961125  0.733134
1     mean  0.961125  0.733134

,Category,AUROC005_pct,Paper_AUROC005_pct,d_AUROC005_pp,F1_pct,Paper_F1_pct,d_F1_pp
0,rice,96.112538,96.11,0.002538,73.313419,73.31,0.003419
1,mean,96.112538,83.93,12.182538,73.313419,62.61,10.703419

\nPUBLIC TEST FINISHED.

## 7. Metric bổ sung: AU-PRO\(_{0.05}\) trên **toàn bộ `test_public`**

Paper SuperADD **không báo metric này**. Cell này giữ nguyên `model.predict()` của SuperADD và:
- dùng TIFF float16 đã sinh cho ảnh `bad`;
- chỉ inference thêm ảnh `good` để tính FPR trên toàn bộ pixel normal;
- resize GT về resolution anomaly map bằng nearest-neighbor;
- mỗi connected component GT có trọng số bằng nhau;
- tích phân PRO–FPR từ 0 đến 0.05 và chuẩn hóa chia 0.05.

In [ ]:
# ============================================================
# CELL 7 — AU-PRO@0.05 trên test_public
# SuperADD prediction giữ nguyên, chỉ bổ sung metric AU-PRO
# ============================================================

from pathlib import Path
import os
import subprocess
import textwrap
import pandas as pd

# Chỉ chạy 1 category
AU_PRO_CATEGORIES = ["rice"]

PUBLIC_OUT = REPO / "outputs_public"

AU_PRO_SCRIPT = r"""
from pathlib import Path

import numpy as np
import cv2
import tifffile
import pandas as pd

from torchvision import transforms
from tqdm import tqdm

from industrial.model import SuperADD
from industrial.dataset import MVTecAD2Dataset
from industrial.paths import get_dataset_path, get_model_path


# ============================================================
# CONFIG
# ============================================================

CATEGORIES = ["rice"]

PUBLIC_OUT = Path("./outputs_public")

MAX_FPR = 0.05


# ============================================================
# AU-PRO@0.05
# ============================================================

def compute_aupro_005(normal_scores, region_scores):

    normal_scores = np.concatenate(
        normal_scores
    ).astype(
        np.float32,
        copy=False
    )

    num_regions = len(region_scores)

    if num_regions == 0:
        raise RuntimeError(
            "Không tìm thấy GT connected component."
        )

    anomaly_scores = []
    anomaly_weights = []

    # Mỗi GT region có trọng số bằng nhau
    for scores in region_scores:

        scores = np.asarray(
            scores,
            dtype=np.float32
        ).reshape(-1)

        if scores.size == 0:
            continue

        anomaly_scores.append(scores)

        anomaly_weights.append(
            np.full(
                scores.size,
                1.0 / (num_regions * scores.size),
                dtype=np.float64
            )
        )

    anomaly_scores = np.concatenate(
        anomaly_scores
    )

    anomaly_weights = np.concatenate(
        anomaly_weights
    )

    num_normal_pixels = normal_scores.size

    if num_normal_pixels == 0:
        raise RuntimeError(
            "Không có normal pixels để tính FPR."
        )

    # Score của toàn bộ pixel
    scores_all = np.concatenate([
        normal_scores,
        anomaly_scores
    ])

    # Normal pixel đóng góp vào FPR
    fpr_delta = np.concatenate([
        np.full(
            num_normal_pixels,
            1.0 / num_normal_pixels,
            dtype=np.float64
        ),
        np.zeros(
            anomaly_scores.size,
            dtype=np.float64
        )
    ])

    # Anomaly pixel đóng góp vào PRO
    pro_delta = np.concatenate([
        np.zeros(
            num_normal_pixels,
            dtype=np.float64
        ),
        anomaly_weights
    ])

    # Threshold sweep từ score lớn -> nhỏ
    order = np.argsort(
        scores_all,
        kind="mergesort"
    )[::-1]

    sorted_scores = scores_all[order]

    cumulative_fpr = np.cumsum(
        fpr_delta[order]
    )

    cumulative_pro = np.cumsum(
        pro_delta[order]
    )

    # Chỉ lấy cuối mỗi nhóm có cùng anomaly score
    group_ends = np.r_[
        np.flatnonzero(
            sorted_scores[1:]
            !=
            sorted_scores[:-1]
        ),
        sorted_scores.size - 1
    ]

    fpr = np.r_[
        0.0,
        cumulative_fpr[group_ends]
    ]

    pro = np.r_[
        0.0,
        cumulative_pro[group_ends]
    ]

    # Loại FPR trùng
    unique_fpr, first_idx, counts = np.unique(
        fpr,
        return_index=True,
        return_counts=True
    )

    unique_pro = pro[
        first_idx + counts - 1
    ]

    if unique_fpr[-1] < MAX_FPR:
        raise RuntimeError(
            "FPR curve không đạt 0.05."
        )

    # ========================================================
    # Cắt curve chính xác tại FPR = 0.05
    # ========================================================

    idx = np.searchsorted(
        unique_fpr,
        MAX_FPR,
        side="left"
    )

    if (
        idx < len(unique_fpr)
        and
        np.isclose(
            unique_fpr[idx],
            MAX_FPR
        )
    ):

        x = unique_fpr[:idx + 1]
        y = unique_pro[:idx + 1]

    else:

        x0 = unique_fpr[idx - 1]
        x1 = unique_fpr[idx]

        y0 = unique_pro[idx - 1]
        y1 = unique_pro[idx]

        y_at_max_fpr = (
            y0
            +
            (MAX_FPR - x0)
            *
            (y1 - y0)
            /
            (x1 - x0)
        )

        x = np.r_[
            unique_fpr[:idx],
            MAX_FPR
        ]

        y = np.r_[
            unique_pro[:idx],
            y_at_max_fpr
        ]

    # Chuẩn hóa diện tích về [0,1]
    area = np.trapezoid(
        y,
        x
    )

    return float(
        area / MAX_FPR
    )


# ============================================================
# EVALUATION
# ============================================================

rows = []

for category in CATEGORIES:

    print()
    print("=" * 70)
    print(
        f"AU-PRO@0.05 — {category}"
    )
    print("=" * 70)

    dataset = MVTecAD2Dataset(
        get_dataset_path(
            "mvtec_ad_2"
        ),
        category,
        "test_public",
        transform=transforms.ToTensor()
    )

    # Bad images đã được Cell 6 inference và lưu TIFF
    bad_prediction_dir = (
        PUBLIC_OUT
        /
        "anomaly_images"
        /
        category
        /
        "test_public"
    )

    model = None

    normal_scores = []
    region_scores = []

    num_good = 0
    num_bad = 0

    for sample in tqdm(
        dataset,
        desc=category
    ):

        stem = Path(
            sample.image_path
        ).stem

        # ====================================================
        # BAD IMAGE
        # Dùng lại prediction TIFF từ Cell 6
        # ====================================================

        if sample.label == 1:

            prediction_path = (
                bad_prediction_dir
                /
                f"{stem}.tiff"
            )

            if not prediction_path.is_file():

                raise FileNotFoundError(
                    f"Thiếu prediction: "
                    f"{prediction_path}"
                )

            anomaly_map = np.asarray(
                tifffile.imread(
                    prediction_path
                ),
                dtype=np.float16
            ).astype(
                np.float32
            )

            num_bad += 1

        # ====================================================
        # GOOD IMAGE
        # Cell 6 không inference good vì
        # evaluate_good_images=False.
        # Cần predict để tính normal-pixel FPR cho AU-PRO.
        # ====================================================

        else:

            if model is None:

                model = SuperADD.from_disk(
                    get_model_path(
                        category
                    )
                )

            anomaly_map, _ = model.predict(
                sample.image
            )

            # Đồng nhất precision với TIFF do test.py lưu
            anomaly_map = (
                anomaly_map
                .astype(
                    np.float16
                )
                .astype(
                    np.float32
                )
            )

            num_good += 1

        # ====================================================
        # GT MASK
        # ====================================================

        if sample.mask is None:

            gt = np.zeros(
                anomaly_map.shape,
                dtype=np.uint8
            )

        else:

            gt_original = (
                sample.mask[0]
                .cpu()
                .numpy()
                >
                0.5
            ).astype(
                np.uint8
            )

            # Resize mask -> đúng resolution anomaly map
            gt = cv2.resize(
                gt_original,
                anomaly_map.shape[::-1],
                interpolation=cv2.INTER_NEAREST
            )

            gt = (
                gt > 0
            ).astype(
                np.uint8
            )

        # ====================================================
        # NORMAL PIXELS
        # ====================================================

        normal_scores.append(
            anomaly_map[
                gt == 0
            ].reshape(-1)
        )

        # ====================================================
        # GT CONNECTED COMPONENTS
        # ====================================================

        if gt.any():

            num_labels, labels = (
                cv2.connectedComponents(
                    gt,
                    connectivity=8
                )
            )

            for region_id in range(
                1,
                num_labels
            ):

                region_scores.append(
                    anomaly_map[
                        labels
                        ==
                        region_id
                    ].reshape(-1)
                )

    # ========================================================
    # CALCULATE
    # ========================================================

    au_pro = compute_aupro_005(
        normal_scores,
        region_scores
    )

    rows.append({
        "Category": category,
        "AU_PRO_0.05": au_pro,
        "AU_PRO_0.05_pct": au_pro * 100.0,
        "good_images": num_good,
        "bad_images": num_bad,
        "gt_regions": len(region_scores)
    })

    print()
    print(
        f"{category}: "
        f"AU-PRO@0.05 = "
        f"{au_pro * 100:.2f}%"
    )


# ============================================================
# SAVE RESULT
# ============================================================

df = pd.DataFrame(
    rows
)

if len(df) > 1:

    mean_row = {
        "Category": "mean",
        "AU_PRO_0.05":
            df["AU_PRO_0.05"].mean(),
        "AU_PRO_0.05_pct":
            df["AU_PRO_0.05_pct"].mean(),
        "good_images":
            df["good_images"].sum(),
        "bad_images":
            df["bad_images"].sum(),
        "gt_regions":
            df["gt_regions"].sum()
    }

    df.loc[len(df)] = mean_row


output_path = (
    PUBLIC_OUT
    /
    "aupro_005_test_public.csv"
)

df.to_csv(
    output_path,
    index=False
)

print()
print("=" * 70)
print(df.to_string(index=False))
print("=" * 70)
print()
print(
    "Saved:",
    output_path
)
"""


# ============================================================
# GHI SCRIPT RA FILE
# Tránh lỗi khi truyền một script rất dài qua python -c
# ============================================================

script_path = (
    REPO
    /
    "_compute_aupro_005.py"
)

script_path.write_text(
    AU_PRO_SCRIPT
)


# ============================================================
# ENVIRONMENT
# ============================================================

env = os.environ.copy()

env["PYTHONUNBUFFERED"] = "1"

# Fix lỗi matplotlib backend trên Colab
env["MPLBACKEND"] = "Agg"


# ============================================================
# RUN TRONG UV ENV CỦA SUPERADD
# ============================================================

cmd = [
    str(UV),
    "run",
    "--no-sync",
    "python",
    "-u",
    str(script_path)
]

print(
    "$",
    " ".join(cmd)
)


process = subprocess.Popen(
    cmd,
    cwd=REPO,
    env=env,
    stdout=subprocess.PIPE,
    stderr=subprocess.STDOUT,
    text=True,
    bufsize=1
)

logs = []

for line in process.stdout:

    print(
        line,
        end="",
        flush=True
    )

    logs.append(
        line
    )


return_code = process.wait()


if return_code != 0:

    raise RuntimeError(
        "\nAU-PRO evaluation FAILED:\n"
        +
        "".join(
            logs[-100:]
        )
    )


# ============================================================
# DISPLAY RESULT
# ============================================================

result_csv = (
    PUBLIC_OUT
    /
    "aupro_005_test_public.csv"
)

assert result_csv.is_file(), (
    f"Không tìm thấy {result_csv}"
)

result_df = pd.read_csv(
    result_csv
)

display(
    result_df
)

$ /usr/local/bin/uv run --no-sync python -u /content/SuperADD/_compute_aupro_005.py

======================================================================
AU-PRO@0.05 — rice
======================================================================

rice:   0%|          | 0/132 [00:00<?, ?it/s]Using cache found in /root/.cache/torch/hub/facebookresearch_dinov3_main

rice:   1%|          | 1/132 [00:48<1:46:46, 48.91s/it]
rice:   2%|▏         | 2/132 [01:04<1:03:51, 29.47s/it]
rice:   2%|▏         | 3/132 [01:20<49:34, 23.06s/it]
rice:   3%|▎         | 4/132 [01:35<42:24, 19.88s/it]
rice:   4%|▍         | 5/132 [01:50<38:16, 18.09s/it]
rice:   5%|▍         | 6/132 [02:05<35:48, 17.05s/it]
rice:   5%|▌         | 7/132 [02:20<34:19, 16.48s/it]
rice:   6%|▌         | 8/132 [02:35<33:25, 16.17s/it]
rice:   7%|▋         | 9/132 [02:51<32:38, 15.93s/it]
rice:   8%|▊         | 10/132 [03:06<32:02, 15.76s/it]
rice:   8%|▊         | 11/132 [03:22<31:35, 15.67s/it]
rice:   9%|▉         | 12/132 [03:37<31:05, 15.55s/it]
rice:  10%|▉         | 13/132 [03:52<30:35, 15.43s/it]
rice:  11%|█         | 14/132 [04:07<30:12, 15.36s/it]
rice:  11%|█▏        | 15/132 [04:23<29:50, 15.31s/it]
rice:  12%|█▏        | 16/132 [04:38<29:32, 15.28s/it]
rice:  13%|█▎        | 17/132 [04:53<29:13, 15.25s/it]
rice:  14%|█▎        | 18/132 [05:08<28:55, 15.22s/it]
rice:  14%|█▍        | 19/132 [05:23<28:40, 15.23s/it]
rice:  15%|█▌        | 20/132 [05:39<28:25, 15.23s/it]
rice:  16%|█▌        | 21/132 [05:54<28:07, 15.20s/it]
rice:  17%|█▋        | 22/132 [06:09<27:53, 15.22s/it]
rice:  17%|█▋        | 23/132 [06:24<27:39, 15.22s/it]
rice:  18%|█▊        | 24/132 [06:39<27:22, 15.21s/it]
rice:  19%|█▉        | 25/132 [06:55<27:09, 15.23s/it]
rice:  20%|█▉        | 26/132 [07:10<27:01, 15.30s/it]
rice:  20%|██        | 27/132 [07:25<26:49, 15.33s/it]
rice:  21%|██        | 28/132 [07:41<26:36, 15.35s/it]
rice:  22%|██▏       | 29/132 [07:56<26:22, 15.37s/it]
rice:  23%|██▎       | 30/132 [08:12<26:07, 15.37s/it]
rice:  23%|██▎       | 31/132 [08:27<25:47, 15.33s/it]
rice:  24%|██▍       | 32/132 [08:42<25:27, 15.27s/it]
rice:  25%|██▌       | 33/132 [08:57<25:09, 15.25s/it]
rice:  26%|██▌       | 34/132 [09:12<24:52, 15.23s/it]
rice:  27%|██▋       | 35/132 [09:28<24:34, 15.21s/it]
rice:  27%|██▋       | 36/132 [09:43<24:19, 15.20s/it]
rice:  28%|██▊       | 37/132 [09:58<24:03, 15.19s/it]
rice:  29%|██▉       | 38/132 [10:13<23:46, 15.17s/it]
rice:  30%|██▉       | 39/132 [10:28<23:32, 15.19s/it]
rice:  30%|███       | 40/132 [10:43<23:16, 15.18s/it]
rice:  31%|███       | 41/132 [10:59<23:00, 15.17s/it]
rice:  32%|███▏      | 42/132 [11:14<22:44, 15.16s/it]
rice:  33%|███▎      | 43/132 [11:14<15:54, 10.72s/it]
rice:  33%|███▎      | 44/132 [11:14<11:09,  7.60s/it]
rice:  34%|███▍      | 45/132 [11:15<07:52,  5.43s/it]
rice:  35%|███▍      | 46/132 [11:15<05:35,  3.90s/it]
rice:  36%|███▌      | 47/132 [11:16<04:03,  2.86s/it]
rice:  36%|███▋      | 48/132 [11:16<03:00,  2.15s/it]
rice:  37%|███▋      | 49/132 [11:17<02:16,  1.65s/it]
rice:  38%|███▊      | 50/132 [11:17<01:46,  1.30s/it]
rice:  39%|███▊      | 51/132 [11:17<01:24,  1.05s/it]
rice:  39%|███▉      | 52/132 [11:18<01:10,  1.14it/s]
rice:  40%|████      | 53/132 [11:18<01:00,  1.31it/s]
rice:  41%|████      | 54/132 [11:19<00:53,  1.46it/s]
rice:  42%|████▏     | 55/132 [11:19<00:47,  1.62it/s]
rice:  42%|████▏     | 56/132 [11:20<00:43,  1.73it/s]
rice:  43%|████▎     | 57/132 [11:20<00:39,  1.91it/s]
rice:  44%|████▍     | 58/132 [11:21<00:34,  2.16it/s]
rice:  45%|████▍     | 59/132 [11:21<00:31,  2.31it/s]
rice:  45%|████▌     | 60/132 [11:21<00:29,  2.47it/s]
rice:  46%|████▌     | 61/132 [11:22<00:27,  2.58it/s]
rice:  47%|████▋     | 62/132 [11:22<00:26,  2.64it/s]
rice:  48%|████▊     | 63/132 [11:22<00:25,  2.69it/s]
rice:  48%|████▊     | 64/132 [11:23<00:24,  2.75it/s]
rice:  49%|████▉     | 65/132 [11:23<00:23,  2.81it/s]
rice:  50%|█████     | 66/132 [11:23<00:22,  2.88it/s]
rice:  51%|█████     | 67/132 [11:24<00:22,  2.89it/s]
rice:  52%|█████▏    | 68/132 [11:24<00:21,  2.92it/s]
rice:  52%|█████▏    | 69/132 [11:24<00:21,  2.92it/s]
rice:  53%|█████▎    | 70/132 [11:25<00:20,  2.98it/s]
rice:  54%|█████▍    | 71/132 [11:25<00:20,  2.94it/s]
rice:  55%|█████▍    | 72/132 [11:25<00:20,  2.93it/s]
rice:  55%|█████▌    | 73/132 [11:26<00:20,  2.89it/s]
rice:  56%|█████▌    | 74/132 [11:26<00:20,  2.87it/s]
rice:  57%|█████▋    | 75/132 [11:26<00:19,  2.89it/s]
rice:  58%|█████▊    | 76/132 [11:27<00:18,  2.96it/s]
rice:  58%|█████▊    | 77/132 [11:27<00:18,  2.98it/s]
rice:  59%|█████▉    | 78/132 [11:27<00:18,  2.98it/s]
rice:  60%|█████▉    | 79/132 [11:28<00:17,  3.02it/s]
rice:  61%|██████    | 80/132 [11:28<00:17,  2.98it/s]
rice:  61%|██████▏   | 81/132 [11:28<00:17,  2.96it/s]
rice:  62%|██████▏   | 82/132 [11:29<00:16,  2.96it/s]
rice:  63%|██████▎   | 83/132 [11:29<00:16,  2.99it/s]
rice:  64%|██████▎   | 84/132 [11:29<00:16,  2.94it/s]
rice:  64%|██████▍   | 85/132 [11:30<00:15,  3.00it/s]
rice:  65%|██████▌   | 86/132 [11:30<00:15,  2.90it/s]
rice:  66%|██████▌   | 87/132 [11:31<00:17,  2.52it/s]
rice:  67%|██████▋   | 88/132 [11:31<00:18,  2.37it/s]
rice:  67%|██████▋   | 89/132 [11:32<00:19,  2.24it/s]
rice:  68%|██████▊   | 90/132 [11:32<00:19,  2.19it/s]
rice:  69%|██████▉   | 91/132 [11:33<00:18,  2.16it/s]
rice:  70%|██████▉   | 92/132 [11:33<00:18,  2.12it/s]
rice:  70%|███████   | 93/132 [11:34<00:18,  2.09it/s]
rice:  71%|███████   | 94/132 [11:34<00:18,  2.08it/s]
rice:  72%|███████▏  | 95/132 [11:35<00:18,  2.04it/s]
rice:  73%|███████▎  | 96/132 [11:35<00:17,  2.01it/s]
rice:  73%|███████▎  | 97/132 [11:35<00:15,  2.23it/s]
rice:  74%|███████▍  | 98/132 [11:36<00:14,  2.41it/s]
rice:  75%|███████▌  | 99/132 [11:36<00:12,  2.58it/s]
rice:  76%|███████▌  | 100/132 [11:36<00:11,  2.71it/s]
rice:  77%|███████▋  | 101/132 [11:37<00:11,  2.76it/s]
rice:  77%|███████▋  | 102/132 [11:37<00:10,  2.84it/s]
rice:  78%|███████▊  | 103/132 [11:37<00:10,  2.89it/s]
rice:  79%|███████▉  | 104/132 [11:38<00:09,  2.94it/s]
rice:  80%|███████▉  | 105/132 [11:38<00:09,  2.94it/s]
rice:  80%|████████  | 106/132 [11:38<00:08,  2.99it/s]
rice:  81%|████████  | 107/132 [11:39<00:08,  2.96it/s]
rice:  82%|████████▏ | 108/132 [11:39<00:08,  2.99it/s]
rice:  83%|████████▎ | 109/132 [11:39<00:07,  2.99it/s]
rice:  83%|████████▎ | 110/132 [11:40<00:07,  2.95it/s]
rice:  84%|████████▍ | 111/132 [11:40<00:07,  2.85it/s]
rice:  85%|████████▍ | 112/132 [11:41<00:07,  2.83it/s]
rice:  86%|████████▌ | 113/132 [11:41<00:06,  2.76it/s]
rice:  86%|████████▋ | 114/132 [11:41<00:06,  2.79it/s]
rice:  87%|████████▋ | 115/132 [11:42<00:06,  2.77it/s]
rice:  88%|████████▊ | 116/132 [11:42<00:05,  2.80it/s]
rice:  89%|████████▊ | 117/132 [11:42<00:05,  2.76it/s]
rice:  89%|████████▉ | 118/132 [11:43<00:04,  2.82it/s]
rice:  90%|█████████ | 119/132 [11:43<00:04,  2.81it/s]
rice:  91%|█████████ | 120/132 [11:43<00:04,  2.77it/s]
rice:  92%|█████████▏| 121/132 [11:44<00:03,  2.79it/s]
rice:  92%|█████████▏| 122/132 [11:44<00:03,  2.79it/s]
rice:  93%|█████████▎| 123/132 [11:44<00:03,  2.84it/s]
rice:  94%|█████████▍| 124/132 [11:45<00:02,  2.79it/s]
rice:  95%|█████████▍| 125/132 [11:45<00:02,  2.76it/s]
rice:  95%|█████████▌| 126/132 [11:46<00:02,  2.51it/s]
rice:  96%|█████████▌| 127/132 [11:46<00:02,  2.35it/s]
rice:  97%|█████████▋| 128/132 [11:47<00:01,  2.23it/s]
rice:  98%|█████████▊| 129/132 [11:47<00:01,  2.12it/s]
rice:  98%|█████████▊| 130/132 [11:48<00:00,  2.13it/s]
rice:  99%|█████████▉| 131/132 [11:48<00:00,  2.09it/s]
rice: 100%|██████████| 132/132 [11:49<00:00,  2.07it/s]
rice: 100%|██████████| 132/132 [11:49<00:00,  5.37s/it]

rice: AU-PRO@0.05 = 71.61%

======================================================================
Category  AU_PRO_0.05  AU_PRO_0.05_pct  good_images  bad_images  gt_regions
    rice     0.716051        71.605128           42          90         120
======================================================================

Saved: outputs_public/aupro_005_test_public.csv

  Category  AU_PRO_0.05  AU_PRO_0.05_pct  good_images  bad_images  gt_regions
0     rice     0.716051        71.605128           42          90         120

## 8. Private + private-mixed — tạo đúng submission của SuperADD

`submit-industrial` yêu cầu đủ 8 category và cả hai split private.

Nó kiểm tra:
- TIFF: 2D, `float16`
- PNG: 2D, chỉ `{0,255}`
- tên: `###_regular` cho private và `###_mixed` cho private-mixed
- đúng số lượng từng category.

In [ ]:
# ============================================================
# CELL 8 — PRIVATE + PRIVATE_MIXED INFERENCE / SUBMISSION
# ============================================================

from pathlib import Path
import os
import shutil
import subprocess

# ------------------------------------------------------------
# CONFIG
# ------------------------------------------------------------

CATEGORIES = ["fruit_jelly"]

PRIVATE_SPLITS = [
    "test_private",
    "test_private_mixed",
]

SUBMIT_OUT = REPO / "outputs"
SUBMISSIONS = REPO / "submissions"


# ------------------------------------------------------------
# CLEAN OUTPUT CŨ
# CHỈ chạy khi bắt đầu inference lại từ đầu
# ------------------------------------------------------------

shutil.rmtree(
    SUBMIT_OUT,
    ignore_errors=True
)

shutil.rmtree(
    SUBMISSIONS,
    ignore_errors=True
)


# ------------------------------------------------------------
# WRITE CONFIG
# ------------------------------------------------------------

cfg = write_config(
    "./outputs/",
    PRIVATE_SPLITS
)

# Ép chắc chắn chỉ chạy category đã chọn
cfg["categories"] = CATEGORIES
cfg["test_split"] = PRIVATE_SPLITS
cfg["save_predictions"] = True
cfg["evaluate_good_images"] = False

(REPO / "config.json").write_text(
    json.dumps(
        cfg,
        indent=4
    )
)

print("Categories :", CATEGORIES)
print("Splits     :", PRIVATE_SPLITS)


# ------------------------------------------------------------
# ENVIRONMENT
# ------------------------------------------------------------

env = os.environ.copy()

env["PYTHONUNBUFFERED"] = "1"

# Fix matplotlib backend trên Colab
env["MPLBACKEND"] = "Agg"


# ------------------------------------------------------------
# STREAMED RUNNER
# ------------------------------------------------------------

def run_streamed(
    cmd,
    cwd=None,
    env=None,
    tail_n=120
):

    cmd = [
        str(x)
        for x in cmd
    ]

    print(
        "\n$",
        " ".join(cmd),
        flush=True
    )

    process = subprocess.Popen(
        cmd,
        cwd=cwd,
        env=env,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        text=True,
        bufsize=1
    )

    logs = []

    for line in process.stdout:

        print(
            line,
            end="",
            flush=True
        )

        logs.append(line)

        if len(logs) > tail_n:
            logs.pop(0)

    return_code = process.wait()

    if return_code != 0:

        raise RuntimeError(
            "\n"
            f"PROCESS FAILED "
            f"(return code={return_code})\n"
            +
            "".join(logs)
        )


# ------------------------------------------------------------
# INFERENCE
# ------------------------------------------------------------

run_streamed(
    [
        UV,
        "run",
        "--no-sync",
        "test-industrial"
    ],
    cwd=REPO,
    env=env
)


# ------------------------------------------------------------
# KIỂM TRA OUTPUT
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("INFERENCE FINISHED")
print("=" * 70)

for category in CATEGORIES:

    for split in PRIVATE_SPLITS:

        folder = (
            SUBMIT_OUT
            / "anomaly_images"
            / category
            / split
        )

        files = list(
            folder.glob("*.tiff")
        )

        print(
            f"{category:12s} | "
            f"{split:20s} | "
            f"{len(files)} TIFF"
        )


# ------------------------------------------------------------
# SUBMISSION
# Chỉ được tạo khi đủ cả 8 category
# ------------------------------------------------------------

ALL_CATEGORIES = [
    "can",
    "fabric",
    "fruit_jelly",
    "rice",
    "sheet_metal",
    "vial",
    "wallplugs",
    "walnuts",
]

if set(CATEGORIES) == set(ALL_CATEGORIES):

    print(
        "\nĐủ 8 category -> tạo submission..."
    )

    run_streamed(
        [
            UV,
            "run",
            "--no-sync",
            "submit-industrial"
        ],
        cwd=REPO,
        env=env
    )

    archives = sorted(
        SUBMISSIONS.glob(
            "submission_*.tar.gz"
        ),
        key=lambda p:
            p.stat().st_mtime
    )

    assert archives, (
        "Không tạo được submission."
    )

    submission = archives[-1]

    print(
        "\nSUBMISSION:",
        submission
    )

    print(
        "SIZE GiB:",
        submission.stat().st_size
        / 2**30
    )

else:

    print(
        "\nChỉ inference:",
        CATEGORIES
    )

    print(
        "Chưa tạo submission vì "
        "chưa đủ 8 category."
    )

## 9. Kiểm tra cuối + lưu về Drive

In [ ]:
import tifffile
from PIL import Image
import numpy as np
from datetime import datetime, timezone

sample_tiff = next(
    (SUBMIT_OUT / "anomaly_images" / "fruit_jelly" / "test_private")
    .glob("*.tiff")
)

sample_png = next(
    (SUBMIT_OUT / "anomaly_images_thresholded" / "fruit_jelly" / "test_private")
    .glob("*.png")
)

a = np.asarray(tifffile.imread(sample_tiff))
b = np.asarray(Image.open(sample_png))

assert a.ndim == 2 and a.dtype == np.float16
assert b.ndim == 2
assert set(np.unique(b).tolist()).issubset({0, 255})

run_id = datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ")
save_dir = DRIVE_OUT / run_id
save_dir.mkdir(parents=True, exist_ok=True)

for p in [
    PUBLIC_OUT / "scores_test_public.csv",
    PUBLIC_OUT / "paper_comparison_test_public.csv",
    PUBLIC_OUT / "aupro_005_test_public.csv",
]:
    assert p.is_file(), p
    shutil.copy2(p, save_dir / p.name)

submission_dst = save_dir / submission.name
shutil.copy2(submission, submission_dst)

h = hashlib.sha256()
with open(submission_dst, "rb") as f:
    for chunk in iter(lambda: f.read(8 * 1024 * 1024), b""):
        h.update(chunk)
sha = h.hexdigest()

meta = {
    "superadd_commit": COMMIT,
    "submission_sha256": sha,
    "categories": CATEGORIES,
    "paper_metric": "pixel standardized partial AU-ROC@max_fpr=0.05 + thresholded SegF1",
    "research_metric": "AU-PRO@FPR<=0.05",
}

(save_dir / "reproducibility.json").write_text(
    json.dumps(meta, indent=2)
)

print("SAVED:", save_dir)
print("UPLOAD THIS FILE:", submission_dst)
print("SHA256:", sha)

NameError: name 'submission' is not defined

## Kết quả nào dùng cho mục đích nào?

- `outputs_public/scores_test_public.csv` → **đối chiếu trực tiếp Table 1 SuperADD**.
- `outputs_public/aupro_005_test_public.csv` → **AU-PRO\(_{0.05}\)** cho nghiên cứu của bạn; paper SuperADD không báo cột này.
- `submissions/submission_*.tar.gz` → file nộp lên MVTec AD 2/VAND server cho **TESTpriv + TESTpriv,mix**.
- Không nộp `test_public` để lấy private score.

In [ ]:
# ============================================================
# CELL 9 — BACKUP OUTPUT CỦA CATEGORY "can" LÊN GOOGLE DRIVE
# ============================================================

from pathlib import Path
from datetime import datetime, timezone
from PIL import Image

import hashlib
import json
import shutil
import tifffile
import numpy as np


CATEGORY = "fruit_jelly"

PRIVATE_SPLITS = [
    "test_private",
    "test_private_mixed",
]


# ============================================================
# 1. KIỂM TRA OUTPUT
# ============================================================

counts = {}

for split in PRIVATE_SPLITS:

    tiff_dir = (
        SUBMIT_OUT
        / "anomaly_images"
        / CATEGORY
        / split
    )

    png_dir = (
        SUBMIT_OUT
        / "anomaly_images_thresholded"
        / CATEGORY
        / split
    )

    assert tiff_dir.is_dir(), tiff_dir
    assert png_dir.is_dir(), png_dir

    tiffs = sorted(tiff_dir.glob("*.tiff"))
    pngs = sorted(png_dir.glob("*.png"))

    assert len(tiffs) > 0, f"Không có TIFF trong {tiff_dir}"
    assert len(pngs) > 0, f"Không có PNG trong {png_dir}"

    # Kiểm tra format một sample
    a = np.asarray(
        tifffile.imread(tiffs[0])
    )

    b = np.asarray(
        Image.open(pngs[0])
    )

    assert (
        a.ndim == 2
        and
        a.dtype == np.float16
    ), (
        f"TIFF sai format: "
        f"shape={a.shape}, dtype={a.dtype}"
    )

    assert b.ndim == 2

    assert set(
        np.unique(b).tolist()
    ).issubset({0, 255})

    counts[split] = {
        "tiff": len(tiffs),
        "png": len(pngs),
    }

    print(
        f"{split}: "
        f"{len(tiffs)} TIFF | "
        f"{len(pngs)} PNG"
    )


# ============================================================
# 2. TẠO THƯ MỤC BACKUP TRÊN DRIVE
# ============================================================

run_id = datetime.now(
    timezone.utc
).strftime(
    "%Y%m%dT%H%M%SZ"
)

save_dir = (
    DRIVE_OUT
    / run_id
)

save_dir.mkdir(
    parents=True,
    exist_ok=True
)


# ============================================================
# 3. COPY TIFF + PNG CỦA CAN
# ============================================================

for split in PRIVATE_SPLITS:

    # TIFF anomaly maps
    src_tiff = (
        SUBMIT_OUT
        / "anomaly_images"
        / CATEGORY
        / split
    )

    dst_tiff = (
        save_dir
        / "outputs"
        / "anomaly_images"
        / CATEGORY
        / split
    )

    shutil.copytree(
        src_tiff,
        dst_tiff,
        dirs_exist_ok=True
    )

    # PNG thresholded maps
    src_png = (
        SUBMIT_OUT
        / "anomaly_images_thresholded"
        / CATEGORY
        / split
    )

    dst_png = (
        save_dir
        / "outputs"
        / "anomaly_images_thresholded"
        / CATEGORY
        / split
    )

    shutil.copytree(
        src_png,
        dst_png,
        dirs_exist_ok=True
    )


# ============================================================
# 4. COPY KẾT QUẢ TEST_PUBLIC NẾU CÓ
# ============================================================

metric_files = [
    PUBLIC_OUT / "scores_test_public.csv",
    PUBLIC_OUT / "paper_comparison_test_public.csv",
    PUBLIC_OUT / "aupro_005_test_public.csv",
]

metric_dir = (
    save_dir
    / "metrics"
)

metric_dir.mkdir(
    parents=True,
    exist_ok=True
)

for p in metric_files:

    if p.is_file():

        shutil.copy2(
            p,
            metric_dir / p.name
        )


# ============================================================
# 5. LƯU METADATA
# ============================================================

meta = {
    "superadd_commit": COMMIT,
    "categories": [CATEGORY],
    "splits": PRIVATE_SPLITS,
    "counts": counts,
    "tiff_format": "float16, single-channel",
    "thresholded_png": "uint8 {0,255}",
}

(
    save_dir
    / "reproducibility.json"
).write_text(
    json.dumps(
        meta,
        indent=2
    )
)


# ============================================================
# 6. KIỂM TRA BACKUP
# ============================================================

print("\nBACKUP COMPLETE")
print("Saved to:", save_dir)

for split in PRIVATE_SPLITS:

    saved_tiffs = list(
        (
            save_dir
            / "outputs"
            / "anomaly_images"
            / CATEGORY
            / split
        ).glob("*.tiff")
    )

    saved_pngs = list(
        (
            save_dir
            / "outputs"
            / "anomaly_images_thresholded"
            / CATEGORY
            / split
        ).glob("*.png")
    )

    print(
        f"{split}: "
        f"{len(saved_tiffs)} TIFF | "
        f"{len(saved_pngs)} PNG"
    )

test_private: 321 TIFF | 321 PNG
test_private_mixed: 321 TIFF | 321 PNG

BACKUP COMPLETE
Saved to: /content/drive/MyDrive/[Q3-4] 2026/[S7] Computer Vision/CV-Nhóm 9/superadd_results_exact/20260910T181308Z
test_private: 321 TIFF | 321 PNG
test_private_mixed: 321 TIFF | 321 PNG