# MS-ILA — Week 03: Frozen DINOv3 normal representation + anomaly scoring

Notebook này nối trực tiếp **Week 02**:

```text
native-resolution loader
→ local 512×512 / context 768×768→512
→ frozen DINOv3 ViT-S/16
→ normal-only prototype representation
→ soft anomaly scoring
→ local/context geometric alignment
→ uniform fusion
→ Hann stitching
→ full-resolution soft anomaly map
```

## Hai task của notebook

| Task | Điều kiện để notebook ghi `PASS` |
|---|---|
| Frozen DINOv3 normal representation | Backbone hoàn toàn frozen; tạo normal prototype bank cho 3 pilot categories; prototype finite, L2-normalized; manifest được lưu |
| Frozen DINOv3 anomaly scoring | Sinh **soft full-resolution score map** đúng `H×W`, finite, nằm trong `[0,1]`, cho toàn bộ split cấu hình; không threshold/morphology |

### Baseline được khóa cho Week 03

Đây là **control baseline do project định nghĩa**, không phải một “anomaly head chính thức” của DINOv3.

Với category $c$, layer $\ell$, view $v\in\{\text{local},\text{context}\}$:

$$
z_{\ell,v}(p)=\frac{f_{\ell,v}(p)}{\|f_{\ell,v}(p)\|_2}
$$

Normal train patches được nén thành $K$ spherical prototypes
$$\mathcal C_{c,\ell,v}=\{c_k\}_{k=1}^K$$ bằng MiniBatch K-Means trên feature đã L2-normalize.

Patch anomaly score:

$$
s_{\ell,v}(p)=\frac{1-\max_k z_{\ell,v}(p)^\top c_k}{2}\in[0,1]
$$

Multi-layer control:

$$
S_v(p)=\frac{1}{|\mathcal L|}\sum_{\ell\in\mathcal L}s_{\ell,v}(p)
$$

Context map phải được **crop/resample về đúng central local FOV** trước khi fusion:

$$
S_{\text{tile}}
=
\frac{1}{2}S_{\text{local}}
+
\frac{1}{2}\operatorname{Align}(S_{\text{context}})
$$

Sau đó Hann stitch để thu $S\in[0,1]^{H\times W}$.

> Không dùng per-image min-max normalization vì sẽ phá tính so sánh của score giữa các ảnh.  
> Không threshold trong hai task này; AU-PRO$_{0.05}$ cần score map mềm.

## 0.1 — Mount Google Drive

In [ ]:
from google.colab import drive
drive.mount("/content/drive", force_remount=False)

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

## 0.2 — Clone/pull repository MS-ILA

Giữ cách làm giống Week 02. PAT chỉ được nhập runtime, không ghi vào notebook.

In [ ]:
from pathlib import Path
from getpass import getpass
import subprocess, os

PROJECT_ROOT = Path("/content/msila")

if PROJECT_ROOT.exists():
    print("Repository đã tồn tại:", PROJECT_ROOT)
    subprocess.run(["git", "-C", str(PROJECT_ROOT), "pull"], check=True)
else:
    token = getpass("GitHub PAT: ")
    clone_url = f"https://haduckien-raccoon:{token}@github.com/haduckien-raccoon/msila.git"
    subprocess.run(["git", "clone", clone_url, str(PROJECT_ROOT)], check=True)

assert (PROJECT_ROOT / "src").exists()
print("PROJECT_ROOT:", PROJECT_ROOT)

Repository đã tồn tại: /content/msila
PROJECT_ROOT: /content/msila

## 0.3 — Chuẩn bị dataset local

Mỗi Colab runtime mới cần dataset trên SSD local. Cell dưới chỉ copy/extract nếu chưa phát hiện đủ category.

In [ ]:
from pathlib import Path
import shutil, tarfile
from tqdm.auto import tqdm

DRIVE_ARCHIVE_DIR = Path("/content/drive/MyDrive/CV-Nhóm 9/data")
ARCHIVE_DIR = Path("/content/mvtec_ad2_zips")
DATA_ROOT = PROJECT_ROOT / "src" / "data"

EXPECTED_SPLITS = {
    "train", "validation", "test_public",
    "test_private", "test_private_mixed",
}

def dataset_category_dirs(root: Path):
    out = []
    if not root.exists():
        return out
    for p in root.iterdir():
        if not p.is_dir():
            continue
        child = {x.name for x in p.iterdir() if x.is_dir()}
        if child.intersection(EXPECTED_SPLITS):
            out.append(p)
    return sorted(out)

existing = dataset_category_dirs(DATA_ROOT)

if len(existing) >= 8:
    print(f"Dataset đã sẵn sàng: {len(existing)} categories")
else:
    ARCHIVE_DIR.mkdir(parents=True, exist_ok=True)
    for old in ARCHIVE_DIR.glob("*.tar.gz"):
        old.unlink()

    archives_drive = sorted(DRIVE_ARCHIVE_DIR.glob("*.tar.gz"))
    assert len(archives_drive) == 8, (
        f"Expected 8 .tar.gz trong {DRIVE_ARCHIVE_DIR}, found {len(archives_drive)}"
    )

    print("Copy 8 archives Drive → Colab SSD...")
    for src in tqdm(archives_drive):
        shutil.copy2(src, ARCHIVE_DIR / src.name)

    def safe_extract(tf, dest: Path):
        dest_r = dest.resolve()
        for member in tf.getmembers():
            target = (dest / member.name).resolve()
            if target != dest_r and dest_r not in target.parents:
                raise RuntimeError(f"Unsafe tar path: {member.name}")
        try:
            tf.extractall(dest, filter="data")
        except TypeError:
            tf.extractall(dest)

    def find_dataset_root(tmp: Path):
        candidates = []
        dirs = [tmp] + [p for p in tmp.rglob("*") if p.is_dir()]
        for d in dirs:
            try:
                child = {x.name for x in d.iterdir() if x.is_dir()}
            except OSError:
                continue
            if child.intersection(EXPECTED_SPLITS):
                candidates.append((len(d.relative_to(tmp).parts), d))
        if candidates:
            return sorted(candidates, key=lambda x: x[0])[0][1]
        top_dirs = [p for p in tmp.iterdir() if p.is_dir()]
        top_files = [p for p in tmp.iterdir() if p.is_file()]
        if len(top_dirs) == 1 and not top_files:
            return top_dirs[0]
        return tmp

    DATA_ROOT.mkdir(parents=True, exist_ok=True)

    for archive in sorted(ARCHIVE_DIR.glob("*.tar.gz")):
        category = archive.name[:-7]
        tmp = Path("/content") / f"_extract_{category}"
        out_dir = DATA_ROOT / category

        if tmp.exists():
            shutil.rmtree(tmp)
        tmp.mkdir(parents=True)

        print("Extract:", archive.name)
        with tarfile.open(archive, "r:gz") as tf:
            safe_extract(tf, tmp)

        detected = find_dataset_root(tmp)

        if out_dir.exists():
            shutil.rmtree(out_dir)

        if detected == tmp:
            tmp.rename(out_dir)
        else:
            shutil.move(str(detected), str(out_dir))
            if tmp.exists():
                shutil.rmtree(tmp)

    print("Extraction complete.")

existing = dataset_category_dirs(DATA_ROOT)
print("Categories:", [p.name for p in existing])
assert len(existing) >= 8

Copy 8 archives Drive → Colab SSD...

  0%|          | 0/8 [00:00<?, ?it/s]

Extract: can.tar.gz
Extract: fabric.tar.gz
Extract: fruit_jelly.tar.gz
Extract: rice.tar.gz
Extract: sheet_metal.tar.gz
Extract: vial.tar.gz
Extract: wallplugs.tar.gz
Extract: walnuts.tar.gz
Extraction complete.
Categories: ['can', 'fabric', 'fruit_jelly', 'rice', 'sheet_metal', 'vial', 'wallplugs', 'walnuts']

## Cleanup: giải phóng disk để chạy colab

In [ ]:
from pathlib import Path
import shutil

DATA_ROOT = Path("/content/msila/src/data")

KEEP_CATEGORIES = {
    "fabric",
    "rice",
    "sheet_metal"
}

deleted = []

for p in DATA_ROOT.iterdir():
    if p.is_dir() and p.name not in KEEP_CATEGORIES:
        print("Delete:", p)
        shutil.rmtree(p)
        deleted.append(p.name)

print("\nDeleted categories:", deleted)

print("\nRemaining:")
for p in sorted(DATA_ROOT.iterdir()):
    if p.is_dir():
        print(" -", p.name)

print("\nDisk usage:")
!df -h /content

Delete: /content/msila/src/data/fruit_jelly
Delete: /content/msila/src/data/wallplugs
Delete: /content/msila/src/data/vial
Delete: /content/msila/src/data/can
Delete: /content/msila/src/data/walnuts

Deleted categories: ['fruit_jelly', 'wallplugs', 'vial', 'can', 'walnuts']

Remaining:
 - fabric
 - rice
 - sheet_metal

Disk usage:
Filesystem      Size  Used Avail Use% Mounted on
overlay         113G   96G   17G  86% /

In [ ]:
# ============================================================
# CLEANUP: Xóa các file .tar.gz đã copy xuống Colab SSD
# ============================================================

from pathlib import Path

ARCHIVE_DIR = Path("/content/mvtec_ad2_zips")

archives_local = sorted(ARCHIVE_DIR.glob("*.tar.gz"))

if not archives_local:
    print("Không có file .tar.gz nào trong Colab để xóa.")
else:
    total_bytes = sum(p.stat().st_size for p in archives_local)

    print(f"Tìm thấy {len(archives_local)} archive:")
    for p in archives_local:
        print(f" - {p.name} ({p.stat().st_size / 1024**3:.2f} GB)")

    print(f"\nTổng dung lượng sẽ giải phóng: {total_bytes / 1024**3:.2f} GB")

    for p in archives_local:
        p.unlink()

    # Xóa luôn thư mục nếu đã rỗng
    try:
        ARCHIVE_DIR.rmdir()
        print(f"Đã xóa thư mục rỗng: {ARCHIVE_DIR}")
    except OSError:
        pass

    print("\nCleanup complete.")

Tìm thấy 8 archive:
 - can.tar.gz (2.66 GB)
 - fabric.tar.gz (10.09 GB)
 - fruit_jelly.tar.gz (1.20 GB)
 - rice.tar.gz (6.30 GB)
 - sheet_metal.tar.gz (1.54 GB)
 - vial.tar.gz (0.76 GB)
 - wallplugs.tar.gz (2.06 GB)
 - walnuts.tar.gz (5.89 GB)

Tổng dung lượng sẽ giải phóng: 30.49 GB
Đã xóa thư mục rỗng: /content/mvtec_ad2_zips

Cleanup complete.

In [ ]:
from pathlib import Path
import shutil

p = Path("/content/msila/outputs/week02")

if p.exists():
    print("Deleting:", p)
    shutil.rmtree(p)
    print("Deleted successfully.")
else:
    print("Folder does not exist:", p)

!df -h /content

Deleting: /content/msila/outputs/week02
Deleted successfully.
Filesystem      Size  Used Avail Use% Mounted on
overlay         113G   66G   48G  59% /

# W3.0 — Environment, protocol constants và pilot categories

In [ ]:
import os, sys, json, math, time, random, hashlib, re
from pathlib import Path

import numpy as np
import pandas as pd
import torch
import torch.nn.functional as F
from tqdm.auto import tqdm

import importlib.util, subprocess
if importlib.util.find_spec("sklearn") is None:
    subprocess.run([sys.executable, "-m", "pip", "install", "-q", "scikit-learn"], check=True)

from sklearn.cluster import MiniBatchKMeans

if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from src.data.loader import MVTecAD2HighResDataset
from src.data.tiling import (
    generate_tile_records,
    extract_local_context,
    stitch_tiles_hann,
)

DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# Week-02 locked protocol
LOCAL_TILE_SIZE = 512
LOCAL_OVERLAP = 128
CONTEXT_SIZE = 768
CONTEXT_OUT_SIZE = 512

DINOV3_MEAN = (0.485, 0.456, 0.406)
DINOV3_STD  = (0.229, 0.224, 0.225)
DINOV3_MODEL = "dinov3_vits16"
DINOV3_LAYER_IDS = [-4, -2, -1]

# Normal representation control
N_PROTOTYPES = 64
PATCH_SAMPLES_PER_TILE_PER_VIEW = 64
MAX_FIT_PATCHES_PER_LAYER_VIEW = 30000
PAIR_BATCH_SIZE = 4

# Final Week-03 run must keep this False.
FAST_DEV_RUN = False
DEV_MAX_TRAIN_IMAGES_PER_CATEGORY = 3
DEV_MAX_SCORE_IMAGES_PER_CATEGORY_SPLIT = 3

SCORE_SPLITS = [
    "validation",
    "test_public",
    "test_private",
    "test_private_mixed",
]

SEED = 42
random.seed(SEED)
np.random.seed(SEED)
torch.manual_seed(SEED)

W3_OUTPUT_DIR = PROJECT_ROOT / "outputs" / "week03"
REP_DIR = W3_OUTPUT_DIR / "normal_representation"
SCORE_DIR = W3_OUTPUT_DIR / "score_maps"
DOCS_DIR = PROJECT_ROOT / "docs"

for d in [W3_OUTPUT_DIR, REP_DIR, SCORE_DIR, DOCS_DIR]:
    d.mkdir(parents=True, exist_ok=True)

WEEK3_STATUS = {
    "normal_representation": "TODO",
    "anomaly_scoring": "TODO",
}

def norm_name(x):
    return re.sub(r"[^a-z0-9]+", "", str(x).lower())

available_categories = [p.name for p in dataset_category_dirs(DATA_ROOT)]
requested_pilots = [
    "fabric",
    "rice",
    "sheet_metal"
]
PILOT_CATEGORIES = []

for req in requested_pilots:
    matches = [c for c in available_categories if norm_name(c) == norm_name(req)]
    if len(matches) != 1:
        raise RuntimeError(
            f"Cannot resolve pilot category {req!r}. Available={available_categories}"
        )
    PILOT_CATEGORIES.append(matches[0])

print("DEVICE           :", DEVICE)
print("PILOT_CATEGORIES :", PILOT_CATEGORIES)
print("FAST_DEV_RUN     :", FAST_DEV_RUN)

if FAST_DEV_RUN:
    print("WARNING: DEV mode only; final status will be DEV_PASS.")

DEVICE           : cuda
PILOT_CATEGORIES : ['fabric', 'rice', 'sheet_metal']
FAST_DEV_RUN     : False

# W3.1 — Task 1: Frozen DINOv3 normal representation

## Acceptance criteria

1. DINOv3 chạy `eval()` và **0 trainable parameters**.
2. Chỉ dùng `train` normal của từng pilot category.
3. Local và context có **representation riêng** để tránh trộn hai phân phối FOV.
4. Ba block DINOv3 được giữ riêng; không learned fusion.
5. Feature patch được L2-normalize trước K-Means; prototypes cũng L2-normalize.
6. Mọi prototype finite; norm gần 1.
7. Lưu:
   - `outputs/week03/normal_representation/<category>.pt`
   - `outputs/week03/normal_representation/manifest.csv`

## W3.1.1 — Load checkpoint + frozen feature extractor

In [ ]:
CHECKPOINT_CANDIDATES = [
    Path("/content/dinov3_vits16_pretrain_lvd1689m.pth"),
    Path("/content/msila_weights/dinov3_vits16_pretrain_lvd1689m-08c60483.pth"),
    Path("/content/drive/MyDrive/MSILA_weights/dinov3_vits16_pretrain_lvd1689m-08c60483.pth"),
    # Path thực tế đang dùng trong project của bạn
    Path("/content/drive/MyDrive/CV-Nhóm 9/weights/dinov3_vits16_pretrain_lvd1689m.pth"),
]

DINOV3_WEIGHTS = next((p for p in CHECKPOINT_CANDIDATES if p.exists()), None)

if DINOV3_WEIGHTS is None:
    raise FileNotFoundError(
        "Không tìm thấy DINOv3 ViT-S/16 checkpoint. "
        "Hãy kiểm tra CHECKPOINT_CANDIDATES."
    )

def sha256_file(path, chunk_size=8 * 1024 * 1024):
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(chunk_size), b""):
            h.update(chunk)
    return h.hexdigest()

sha256 = sha256_file(DINOV3_WEIGHTS)
print("Checkpoint:", DINOV3_WEIGHTS)
print("SHA256    :", sha256)

assert sha256.startswith("08c60483"), (
    "Checkpoint hash không khớp DINOv3 ViT-S/16 đã khóa ở Week 02."
)

# -----------------------------------------------------------------------------
# IMPORTANT FIX
# -----------------------------------------------------------------------------
# Không dùng torch.hub.load(...) để load backbone từ repo main.
# hubconf.py hiện import cả segmentation head, từ đó kéo torchmetrics dù Week 3
# chỉ cần backbone. Ta import trực tiếp dinov3.hub.backbones để tránh dependency
# không liên quan và tránh lỗi ModuleNotFoundError: torchmetrics.
# -----------------------------------------------------------------------------

def resolve_dinov3_repo():
    """Tìm DINOv3 source repo; nếu chưa có thì clone trực tiếp mà không import hubconf.py."""
    hub_root = Path(torch.hub.get_dir())

    candidates = [
        Path("/content/dinov3_repo"),
        Path("/content/dinov3"),
        *sorted(hub_root.glob("facebookresearch_dinov3_*")),
    ]

    for repo in candidates:
        if (repo / "dinov3" / "hub" / "backbones.py").exists():
            print("DINOv3 repo:", repo)
            return repo

    repo = Path("/content/dinov3_repo")
    print("DINOv3 source chưa có; cloning official repository...")
    subprocess.run(
        [
            "git", "clone", "--depth", "1",
            "https://github.com/facebookresearch/dinov3.git",
            str(repo),
        ],
        check=True,
    )
    assert (repo / "dinov3" / "hub" / "backbones.py").exists()
    return repo


def load_frozen_dinov3(model_name=DINOV3_MODEL, weights=DINOV3_WEIGHTS, device=DEVICE):
    repo = resolve_dinov3_repo()
    repo_str = str(repo.resolve())
    if repo_str not in sys.path:
        sys.path.insert(0, repo_str)

    # Import ONLY backbone module; không đi qua hubconf.py.
    from dinov3.hub import backbones as dinov3_backbones

    if not hasattr(dinov3_backbones, model_name):
        raise AttributeError(f"Unknown DINOv3 backbone: {model_name}")

    factory = getattr(dinov3_backbones, model_name)

    # backbones.py hỗ trợ local weight path; không cần tải checkpoint lại.
    model = factory(
        pretrained=True,
        weights=str(weights),
        check_hash=False,  # SHA256 đầy đủ đã kiểm tra ở phía trên.
    )

    model = model.to(device).eval()
    for p in model.parameters():
        p.requires_grad_(False)

    n_trainable = sum(p.numel() for p in model.parameters() if p.requires_grad)
    assert n_trainable == 0
    assert model.training is False

    # Ghi lại source commit để tái lập thí nghiệm.
    try:
        commit = subprocess.check_output(
            ["git", "-C", str(repo), "rev-parse", "HEAD"],
            text=True,
        ).strip()
        print("DINOv3 source commit:", commit)
    except Exception:
        pass

    return model


def resolve_block_indices(model, layer_ids):
    n = len(model.blocks)
    out = []
    for idx in layer_ids:
        j = idx if idx >= 0 else n + idx
        if not (0 <= j < n):
            raise IndexError((idx, j, n))
        out.append(j)
    return out


def _first_tensor(obj):
    if torch.is_tensor(obj):
        return obj
    if isinstance(obj, (tuple, list)):
        for x in obj:
            t = _first_tensor(x)
            if t is not None:
                return t
    if isinstance(obj, dict):
        for x in obj.values():
            t = _first_tensor(x)
            if t is not None:
                return t
    return None


@torch.no_grad()
def forward_with_block_features(model, x, layer_ids):
    resolved = resolve_block_indices(model, layer_ids)
    feats, handles = {}, []

    for j in resolved:
        def hook(module, inputs, output, j=j):
            t = _first_tensor(output)
            if t is None:
                raise RuntimeError(f"No tensor at block {j}")
            feats[j] = t.detach()
        handles.append(model.blocks[j].register_forward_hook(hook))

    try:
        _ = model(x)
    finally:
        for h in handles:
            h.remove()

    missing = [j for j in resolved if j not in feats]
    if missing:
        raise RuntimeError(f"Missing hooked features: {missing}")

    return {j: feats[j] for j in resolved}


def feature_tensor_to_spatial_map(feat):
    if feat.ndim == 4:
        return feat
    if feat.ndim != 3:
        raise ValueError(f"Expected BNC/BCHW, got {tuple(feat.shape)}")

    B, N, C = feat.shape
    found = None
    for n_special in range(min(32, N - 1) + 1):
        n_patch = N - n_special
        side = math.isqrt(n_patch)
        if side * side == n_patch:
            found = (n_special, side)
            break

    if found is None:
        raise ValueError(f"Cannot infer square patch grid from N={N}")

    n_special, side = found
    tokens = feat[:, n_special:, :]
    return tokens.transpose(1, 2).contiguous().reshape(B, C, side, side)


def normalize_batch_dinov3(x):
    mean = torch.tensor(DINOV3_MEAN, device=x.device, dtype=x.dtype)[None, :, None, None]
    std = torch.tensor(DINOV3_STD, device=x.device, dtype=x.dtype)[None, :, None, None]
    return (x - mean) / std


dinov3 = load_frozen_dinov3()
RESOLVED_LAYERS = resolve_block_indices(dinov3, DINOV3_LAYER_IDS)

print("Resolved DINOv3 layers:", RESOLVED_LAYERS)
print("Trainable params:", sum(p.numel() for p in dinov3.parameters() if p.requires_grad))

Checkpoint: /content/drive/MyDrive/CV-Nhóm 9/weights/dinov3_vits16_pretrain_lvd1689m.pth
SHA256    : 08c60483bc63c04f533611e34bf70b120eedb7240f469bc16e9e20bf344b941d
DINOv3 source chưa có; cloning official repository...
Downloading: "file:///content/drive/.shortcut-targets-by-id/1otP3wEZaj9wQVLqCh9zhcX1RQU8Lnb_a/CV-Nh%C3%B3m%209/weights/dinov3_vits16_pretrain_lvd1689m.pth" to /root/.cache/torch/hub/checkpoints/dinov3_vits16_pretrain_lvd1689m.pth

100%|██████████| 82.5M/82.5M [00:00<00:00, 399MB/s]

DINOv3 source commit: 6876159a11b4df116f30f667f8c9888617df0751
Resolved DINOv3 layers: [8, 10, 11]
Trainable params: 0

## W3.1.2 — Priority reservoir + prototype fitting

`PriorityReservoir` gán một random priority độc lập cho mỗi patch và giữ top-\(M\).
Cách này cho một uniform subset giới hạn bộ nhớ mà không cần giữ toàn bộ feature cloud.

In [ ]:
class PriorityReservoir:
    def __init__(self, cap, seed):
        self.cap = int(cap)
        self.gen = torch.Generator(device="cpu")
        self.gen.manual_seed(int(seed))
        self.x = None
        self.key = None
        self.seen = 0

    def add(self, rows):
        rows = rows.detach().float().cpu()
        if rows.ndim != 2:
            raise ValueError(rows.shape)

        self.seen += rows.shape[0]
        keys = torch.rand(rows.shape[0], generator=self.gen)

        if self.x is None:
            x = rows
            k = keys
        else:
            x = torch.cat([self.x, rows], dim=0)
            k = torch.cat([self.key, keys], dim=0)

        if x.shape[0] > self.cap:
            idx = torch.topk(k, k=self.cap, largest=True).indices
            x = x[idx]
            k = k[idx]

        self.x, self.key = x, k

    def tensor(self):
        if self.x is None or self.x.shape[0] == 0:
            raise RuntimeError("Empty reservoir")
        return self.x

def sample_rows_per_tile(spatial_bchw, n_per_tile, generator):
    B, C, H, W = spatial_bchw.shape
    flat = spatial_bchw.permute(0, 2, 3, 1).reshape(B, H * W, C)
    rows = []

    for b in range(B):
        n = min(int(n_per_tile), H * W)
        idx = torch.randperm(H * W, generator=generator)[:n]
        rows.append(flat[b, idx.to(flat.device)])

    return torch.cat(rows, dim=0)

def fit_spherical_prototypes(features_nc, n_prototypes=N_PROTOTYPES, seed=SEED):
    x = F.normalize(features_nc.float(), dim=1, eps=1e-12).cpu().numpy()
    k = min(int(n_prototypes), x.shape[0])

    km = MiniBatchKMeans(
        n_clusters=k,
        random_state=int(seed),
        batch_size=min(4096, max(256, x.shape[0])),
        n_init=3,
        max_iter=100,
        reassignment_ratio=0.01,
    )
    km.fit(x)

    centers = torch.from_numpy(km.cluster_centers_).float()
    centers = F.normalize(centers, dim=1, eps=1e-12)
    return centers, float(km.inertia_)

## W3.1.3 — Build normal representation cho 3 pilot categories

In [ ]:
@torch.no_grad()
def build_category_normal_representation(category):
    ds = MVTecAD2HighResDataset(
        DATA_ROOT,
        split="train",
        categories=[category],
    )

    indices = list(range(len(ds)))
    if FAST_DEV_RUN:
        indices = indices[:DEV_MAX_TRAIN_IMAGES_PER_CATEGORY]

    reservoirs = {}
    for layer in RESOLVED_LAYERS:
        for view in ["local", "context"]:
            reservoirs[(layer, view)] = PriorityReservoir(
                MAX_FIT_PATCHES_PER_LAYER_VIEW,
                seed=SEED + 1000 * layer + (0 if view == "local" else 1),
            )

    patch_gen = torch.Generator(device="cpu")
    patch_gen.manual_seed(SEED + sum(ord(c) for c in category))
    n_tiles_total = 0

    for i in tqdm(indices, desc=f"Normal repr | {category}"):
        sample = ds[i]
        image = sample["image"]
        H, W = image.shape[-2:]

        records = generate_tile_records(
            H, W,
            local_size=LOCAL_TILE_SIZE,
            overlap=LOCAL_OVERLAP,
            context_size=CONTEXT_SIZE,
        )
        n_tiles_total += len(records)

        for start in range(0, len(records), PAIR_BATCH_SIZE):
            chunk = records[start:start + PAIR_BATCH_SIZE]
            pair = []

            for rec in chunk:
                local, context = extract_local_context(
                    image,
                    rec,
                    local_out_size=LOCAL_TILE_SIZE,
                    context_out_size=CONTEXT_OUT_SIZE,
                )
                pair.extend([local, context])

            x = torch.stack(pair, dim=0).to(DEVICE)
            x = normalize_batch_dinov3(x)
            feats = forward_with_block_features(dinov3, x, DINOV3_LAYER_IDS)

            for layer, feat in feats.items():
                spatial = feature_tensor_to_spatial_map(feat)
                spatial = F.normalize(spatial.float(), dim=1, eps=1e-12)

                local_rows = sample_rows_per_tile(
                    spatial[0::2], PATCH_SAMPLES_PER_TILE_PER_VIEW, patch_gen
                )
                context_rows = sample_rows_per_tile(
                    spatial[1::2], PATCH_SAMPLES_PER_TILE_PER_VIEW, patch_gen
                )

                reservoirs[(layer, "local")].add(local_rows)
                reservoirs[(layer, "context")].add(context_rows)

    out = {
        "category": category,
        "model": DINOV3_MODEL,
        "checkpoint_sha256": sha256,
        "layers": RESOLVED_LAYERS,
        "local_tile_size": LOCAL_TILE_SIZE,
        "local_overlap": LOCAL_OVERLAP,
        "context_size": CONTEXT_SIZE,
        "context_out_size": CONTEXT_OUT_SIZE,
        "n_train_images": len(indices),
        "n_tiles": n_tiles_total,
        "fast_dev_run": FAST_DEV_RUN,
        "prototypes": {},
        "meta": {},
    }

    rows = []

    for layer in RESOLVED_LAYERS:
        out["prototypes"][layer] = {}
        out["meta"][layer] = {}

        for view in ["local", "context"]:
            reservoir = reservoirs[(layer, view)]
            fit_x = reservoir.tensor()


            # ========================================================
            # SAVE sampled normal DINOv3 features -> .npz
            # ========================================================
            NORMAL_FEATURE_DIR = (
                PROJECT_ROOT
                / "outputs"
                / "week03"
                / "normal_features"
            )
            NORMAL_FEATURE_DIR.mkdir(parents=True, exist_ok=True)

            feature_path = (
                NORMAL_FEATURE_DIR
                / f"{category}_layer{layer}_{view}.npz"
            )

            np.savez_compressed(
                feature_path,
                features=fit_x.cpu().numpy().astype(np.float16),
                category=np.array(category),
                layer=np.int32(layer),
                view=np.array(view),
                checkpoint_sha256=np.array(sha256),
                n_train_images=np.int32(len(indices)),
                n_tiles=np.int32(n_tiles_total),
            )

            print("Saved normal features:", feature_path)

            # ========================================================
            # FIT PROTOTYPES
            # ========================================================

            centers, inertia = fit_spherical_prototypes(
                fit_x,
                n_prototypes=N_PROTOTYPES,
                seed=SEED + layer,
            )

            assert torch.isfinite(centers).all()
            norm_err = float((centers.norm(dim=1) - 1.0).abs().max())
            assert norm_err < 1e-4

            out["prototypes"][layer][view] = centers
            out["meta"][layer][view] = {
                "seen_patch_samples": int(reservoir.seen),
                "fit_patch_samples": int(fit_x.shape[0]),
                "n_prototypes": int(centers.shape[0]),
                "dim": int(centers.shape[1]),
                "kmeans_inertia": inertia,
                "max_prototype_norm_error": norm_err,
            }

            rows.append({
                "category": category,
                "layer": layer,
                "view": view,
                **out["meta"][layer][view],
                "n_train_images": len(indices),
                "n_tiles": n_tiles_total,
            })

    save_path = REP_DIR / f"{category}.pt"
    torch.save(out, save_path)
    return out, rows, save_path

all_rep_rows = []
rep_paths = {}

for category in PILOT_CATEGORIES:
    rep, rows, save_path = build_category_normal_representation(category)
    all_rep_rows.extend(rows)
    rep_paths[category] = save_path
    print("Saved:", save_path)

rep_manifest = pd.DataFrame(all_rep_rows)
rep_manifest.to_csv(REP_DIR / "manifest.csv", index=False)
display(rep_manifest)

assert len(rep_manifest) == len(PILOT_CATEGORIES) * len(RESOLVED_LAYERS) * 2
assert (rep_manifest["fit_patch_samples"] > 0).all()
assert (rep_manifest["n_prototypes"] > 0).all()
assert (rep_manifest["max_prototype_norm_error"] < 1e-4).all()
assert sum(p.numel() for p in dinov3.parameters() if p.requires_grad) == 0
assert dinov3.training is False

WEEK3_STATUS["normal_representation"] = "DEV_PASS" if FAST_DEV_RUN else "PASS"

print("Frozen DINOv3 normal representation:",
      WEEK3_STATUS["normal_representation"])

Normal repr | fabric:   0%|          | 0/387 [00:00<?, ?it/s]

Saved normal features: /content/msila/outputs/week03/normal_features/fabric_layer8_local.npz
Saved normal features: /content/msila/outputs/week03/normal_features/fabric_layer8_context.npz
Saved normal features: /content/msila/outputs/week03/normal_features/fabric_layer10_local.npz
Saved normal features: /content/msila/outputs/week03/normal_features/fabric_layer10_context.npz
Saved normal features: /content/msila/outputs/week03/normal_features/fabric_layer11_local.npz
Saved normal features: /content/msila/outputs/week03/normal_features/fabric_layer11_context.npz
Saved: /content/msila/outputs/week03/normal_representation/fabric.pt

Normal repr | rice:   0%|          | 0/313 [00:00<?, ?it/s]

Saved normal features: /content/msila/outputs/week03/normal_features/rice_layer8_local.npz
Saved normal features: /content/msila/outputs/week03/normal_features/rice_layer8_context.npz
Saved normal features: /content/msila/outputs/week03/normal_features/rice_layer10_local.npz
Saved normal features: /content/msila/outputs/week03/normal_features/rice_layer10_context.npz
Saved normal features: /content/msila/outputs/week03/normal_features/rice_layer11_local.npz
Saved normal features: /content/msila/outputs/week03/normal_features/rice_layer11_context.npz
Saved: /content/msila/outputs/week03/normal_representation/rice.pt

Normal repr | sheet_metal:   0%|          | 0/137 [00:00<?, ?it/s]

Saved normal features: /content/msila/outputs/week03/normal_features/sheet_metal_layer8_local.npz
Saved normal features: /content/msila/outputs/week03/normal_features/sheet_metal_layer8_context.npz
Saved normal features: /content/msila/outputs/week03/normal_features/sheet_metal_layer10_local.npz
Saved normal features: /content/msila/outputs/week03/normal_features/sheet_metal_layer10_context.npz
Saved normal features: /content/msila/outputs/week03/normal_features/sheet_metal_layer11_local.npz
Saved normal features: /content/msila/outputs/week03/normal_features/sheet_metal_layer11_context.npz
Saved: /content/msila/outputs/week03/normal_representation/sheet_metal.pt

,category,layer,view,seen_patch_samples,fit_patch_samples,n_prototypes,dim,kmeans_inertia,max_prototype_norm_error,n_train_images,n_tiles
0,fabric,8,local,866880,30000,64,384,9097.729492,1.192093e-07,387,13545
1,fabric,8,context,866880,30000,64,384,9594.249023,1.192093e-07,387,13545
2,fabric,10,local,866880,30000,64,384,6154.761719,1.192093e-07,387,13545
3,fabric,10,context,866880,30000,64,384,6530.511719,1.192093e-07,387,13545
4,fabric,11,local,866880,30000,64,384,2143.233154,1.192093e-07,387,13545
5,fabric,11,context,866880,30000,64,384,2204.251953,1.192093e-07,387,13545
6,rice,8,local,701120,30000,64,384,11598.158203,1.192093e-07,313,10955
7,rice,8,context,701120,30000,64,384,11260.368164,1.788139e-07,313,10955
8,rice,10,local,701120,30000,64,384,6842.707031,1.192093e-07,313,10955
9,rice,10,context,701120,30000,64,384,6638.718262,1.192093e-07,313,10955
10,rice,11,local,701120,30000,64,384,1617.505493,1.192093e-07,313,10955
11,rice,11,context,701120,30000,64,384,1554.601440,1.192093e-07,313,10955
12,sheet_metal,8,local,289344,30000,64,384,11939.109375,1.192093e-07,137,4521
13,sheet_metal,8,context,289344,30000,64,384,11581.192383,1.192093e-07,137,4521
14,sheet_metal,10,local,289344,30000,64,384,6836.360840,1.192093e-07,137,4521
15,sheet_metal,10,context,289344,30000,64,384,6548.276855,1.192093e-07,137,4521
16,sheet_metal,11,local,289344,30000,64,384,2099.227783,1.192093e-07,137,4521
17,sheet_metal,11,context,289344,30000,64,384,2003.320557,1.788139e-07,137,4521

Frozen DINOv3 normal representation: PASS

## W3.1.4 — Sanity check normal prototype self-score

In [ ]:
def cosine_score_to_prototypes(query_nc, prototypes_kc):
    q = F.normalize(query_nc.float(), dim=1, eps=1e-12)
    p = F.normalize(prototypes_kc.float(), dim=1, eps=1e-12).to(q.device)
    max_cos = (q @ p.T).amax(dim=1)
    score = 0.5 * (1.0 - max_cos)
    return score.clamp(0.0, 1.0)

sanity_rows = []

for category, pth in rep_paths.items():
    bank = torch.load(pth, map_location="cpu")
    for layer in RESOLVED_LAYERS:
        for view in ["local", "context"]:
            proto = bank["prototypes"][layer][view]
            s = cosine_score_to_prototypes(proto, proto)
            sanity_rows.append({
                "category": category,
                "layer": layer,
                "view": view,
                "max_self_score": float(s.max()),
            })

sanity_df = pd.DataFrame(sanity_rows)
display(sanity_df)

assert (sanity_df["max_self_score"] < 1e-5).all()
print("Prototype self-score sanity: PASS")

       category  layer     view  max_self_score
0        fabric      8    local    2.682209e-07
1        fabric      8  context    2.980232e-07
2        fabric     10    local    2.086163e-07
3        fabric     10  context    2.086163e-07
4        fabric     11    local    3.874302e-07
5        fabric     11  context    2.086163e-07
6          rice      8    local    3.576279e-07
7          rice      8  context    2.980232e-07
8          rice     10    local    2.682209e-07
9          rice     10  context    2.384186e-07
10         rice     11    local    2.980232e-07
11         rice     11  context    4.172325e-07
12  sheet_metal      8    local    3.576279e-07
13  sheet_metal      8  context    3.576279e-07
14  sheet_metal     10    local    2.086163e-07
15  sheet_metal     10  context    1.788139e-07
16  sheet_metal     11    local    3.874302e-07
17  sheet_metal     11  context    2.980232e-07

Prototype self-score sanity: PASS

# W3.2 — Task 2: Frozen DINOv3 anomaly scoring

## Scoring protocol được khóa

- Category-specific normal prototype bank.
- Local query chỉ so với local bank; context query chỉ so với context bank.
- Mỗi layer: nearest spherical prototype cosine distance.
- Multi-layer: **uniform mean** — không learned attention.
- Context: central-FOV alignment trước fusion.
- Local/context: **0.5 / 0.5** — control baseline.
- Full-resolution: Hann stitch.
- **Không** min-max theo từng ảnh.
- **Không** threshold.
- **Không** morphology.

Task này PASS vì score-map plumbing đúng; **PASS không có nghĩa là AU-PRO đã tốt**.

## W3.2.1 — Patch score + context-to-local geometric alignment

In [ ]:
def spatial_score_against_prototypes(spatial_bchw, prototypes_kc):
    """
    spatial_bchw: [B,C,h,w]
    prototypes_kc: [K,C]
    return: [B,h,w] in [0,1]
    """
    B, C, h, w = spatial_bchw.shape

    q = spatial_bchw.permute(0, 2, 3, 1).reshape(B, h * w, C).float()
    q = F.normalize(q, dim=-1, eps=1e-12)

    p = F.normalize(
        prototypes_kc.float().to(q.device),
        dim=1,
        eps=1e-12,
    )

    sim = torch.matmul(q, p.T)
    max_cos = sim.amax(dim=-1)
    score = 0.5 * (1.0 - max_cos)

    return score.clamp(0.0, 1.0).reshape(B, h, w)

def context_map_to_local_fov(context_map_bhw):
    """
    Context input 512 represents native 768 FOV.
    Local FOV is central 512/768 = 2/3 of context FOV.
    """
    B, H, W = context_map_bhw.shape
    ratio = LOCAL_TILE_SIZE / CONTEXT_SIZE

    theta = torch.tensor(
        [[ratio, 0.0, 0.0],
         [0.0, ratio, 0.0]],
        dtype=context_map_bhw.dtype,
        device=context_map_bhw.device,
    )[None].repeat(B, 1, 1)

    grid = F.affine_grid(
        theta,
        size=(B, 1, LOCAL_TILE_SIZE, LOCAL_TILE_SIZE),
        align_corners=False,
    )

    aligned = F.grid_sample(
        context_map_bhw[:, None],
        grid,
        mode="bilinear",
        padding_mode="border",
        align_corners=False,
    )[:, 0]

    return aligned

_const = torch.full((2, CONTEXT_OUT_SIZE, CONTEXT_OUT_SIZE), 0.37)
_aligned = context_map_to_local_fov(_const)

assert _aligned.shape == (2, LOCAL_TILE_SIZE, LOCAL_TILE_SIZE)
assert torch.allclose(_aligned, torch.full_like(_aligned, 0.37), atol=1e-6)

print("Context-to-local FOV alignment sanity: PASS")

Context-to-local FOV alignment sanity: PASS

## W3.2.2 — Score một native-resolution image

In [ ]:
@torch.no_grad()
def score_native_image_frozen_dinov3(sample, bank, pair_batch_size=PAIR_BATCH_SIZE):
    image = sample["image"]
    H, W = image.shape[-2:]

    records = generate_tile_records(
        H, W,
        local_size=LOCAL_TILE_SIZE,
        overlap=LOCAL_OVERLAP,
        context_size=CONTEXT_SIZE,
    )

    tile_maps = []

    for start in range(0, len(records), pair_batch_size):
        chunk = records[start:start + pair_batch_size]
        pair = []

        for rec in chunk:
            local, context = extract_local_context(
                image,
                rec,
                local_out_size=LOCAL_TILE_SIZE,
                context_out_size=CONTEXT_OUT_SIZE,
            )
            pair.extend([local, context])

        x = torch.stack(pair).to(DEVICE)
        x = normalize_batch_dinov3(x)
        feats = forward_with_block_features(dinov3, x, DINOV3_LAYER_IDS)

        local_layer_scores = []
        context_layer_scores = []

        for layer, feat in feats.items():
            spatial = feature_tensor_to_spatial_map(feat)

            local_s = spatial_score_against_prototypes(
                spatial[0::2],
                bank["prototypes"][layer]["local"],
            )
            context_s = spatial_score_against_prototypes(
                spatial[1::2],
                bank["prototypes"][layer]["context"],
            )

            local_s = F.interpolate(
                local_s[:, None],
                size=(LOCAL_TILE_SIZE, LOCAL_TILE_SIZE),
                mode="bilinear",
                align_corners=False,
            )[:, 0]

            context_s = F.interpolate(
                context_s[:, None],
                size=(CONTEXT_OUT_SIZE, CONTEXT_OUT_SIZE),
                mode="bilinear",
                align_corners=False,
            )[:, 0]

            context_s = context_map_to_local_fov(context_s)

            local_layer_scores.append(local_s)
            context_layer_scores.append(context_s)

        local_score = torch.stack(local_layer_scores, dim=0).mean(dim=0)
        context_score = torch.stack(context_layer_scores, dim=0).mean(dim=0)

        fused = (0.5 * local_score + 0.5 * context_score).clamp(0.0, 1.0)
        tile_maps.extend([m.detach().cpu() for m in fused])

    stitched = stitch_tiles_hann(
        tile_maps,
        records,
        out_hw=(H, W),
        local_size=LOCAL_TILE_SIZE,
    ).float().clamp(0.0, 1.0)

    assert stitched.shape == (H, W)
    assert torch.isfinite(stitched).all()
    assert float(stitched.min()) >= -1e-6
    assert float(stitched.max()) <= 1.0 + 1e-6

    return stitched, records

## W3.2.3 — Unit scoring sanity

In [ ]:
q = torch.tensor([
    [1.0, 0.0],
    [0.0, 1.0],
    [-1.0, 0.0],
])
p = torch.tensor([[1.0, 0.0]])

s = cosine_score_to_prototypes(q, p)
print("scores:", s.tolist())

assert abs(float(s[0]) - 0.0) < 1e-6
assert abs(float(s[1]) - 0.5) < 1e-6
assert abs(float(s[2]) - 1.0) < 1e-6

print("Cosine scoring definition: PASS")

scores: [0.0, 0.5, 1.0]
Cosine scoring definition: PASS

## W3.2.4 — Full scoring run + save `.npy` soft maps

Đầu ra `.npy` là dữ liệu khoa học chính. PNG chỉ là preview.
Private/private-mixed vẫn có thể xuất score map dù GT mask bị ẩn.

In [ ]:
import matplotlib.pyplot as plt

def sample_id_from_meta(meta):
    p = Path(meta["path"])
    token = hashlib.sha1(str(p).encode("utf-8")).hexdigest()[:10]
    return f"{p.stem}_{token}"

score_rows = []
N_PREVIEW_PER_CATEGORY_SPLIT = 5
preview_counter = {}

for category in PILOT_CATEGORIES:
    bank = torch.load(REP_DIR / f"{category}.pt", map_location="cpu")

    assert bank["category"] == category
    assert bank["checkpoint_sha256"] == sha256

    for split in SCORE_SPLITS:
        try:
            ds = MVTecAD2HighResDataset(
                DATA_ROOT,
                split=split,
                categories=[category],
            )
        except RuntimeError:
            print(f"Skip empty split: {category}/{split}")
            continue

        indices = list(range(len(ds)))
        if FAST_DEV_RUN:
            indices = indices[:DEV_MAX_SCORE_IMAGES_PER_CATEGORY_SPLIT]

        out_dir = SCORE_DIR / split / category
        out_dir.mkdir(parents=True, exist_ok=True)
        preview_counter[(category, split)] = 0

        for i in tqdm(indices, desc=f"Score | {category} | {split}"):
            sample = ds[i]
            meta = sample["meta"]

            if DEVICE.type == "cuda":
                torch.cuda.synchronize()
                torch.cuda.reset_peak_memory_stats()

            t0 = time.perf_counter()
            amap, records = score_native_image_frozen_dinov3(
                sample,
                bank,
                pair_batch_size=PAIR_BATCH_SIZE,
            )

            if DEVICE.type == "cuda":
                torch.cuda.synchronize()

            elapsed = time.perf_counter() - t0
            peak_vram_mb = (
                torch.cuda.max_memory_allocated() / 1024**2
                if DEVICE.type == "cuda"
                else np.nan
            )

            sid = sample_id_from_meta(meta)
            npy_path = out_dir / f"{sid}.npy"
            np.save(npy_path, amap.numpy().astype(np.float32))

            score_rows.append({
                "category": category,
                "split": split,
                "index": i,
                "sample_id": sid,
                "image_path": meta["path"],
                "H": meta["H"],
                "W": meta["W"],
                "n_tiles": len(records),
                "runtime_s": elapsed,
                "peak_vram_mb": peak_vram_mb,
                "score_min": float(amap.min()),
                "score_max": float(amap.max()),
                "score_mean": float(amap.mean()),
                "finite": bool(torch.isfinite(amap).all()),
                "score_path": str(npy_path),
                "has_gt_mask": sample["mask"] is not None,
            })

            if preview_counter[(category, split)] < N_PREVIEW_PER_CATEGORY_SPLIT:
                ncols = 3 if sample["mask"] is not None else 2
                fig, axes = plt.subplots(1, ncols, figsize=(4 * ncols, 4))
                axes = np.atleast_1d(axes)

                axes[0].imshow(sample["image"].permute(1, 2, 0).numpy())
                axes[0].set_title("Native image")

                axes[1].imshow(amap.numpy(), cmap="magma", vmin=0.0, vmax=1.0)
                axes[1].set_title("Frozen DINOv3 soft score")

                if sample["mask"] is not None:
                    axes[2].imshow(sample["mask"].numpy(), cmap="gray")
                    axes[2].set_title("GT mask")

                for ax in axes:
                    ax.axis("off")

                plt.tight_layout()
                fig.savefig(
                    out_dir / f"{sid}_preview.png",
                    dpi=130,
                    bbox_inches="tight",
                )
                plt.close(fig)

                preview_counter[(category, split)] += 1

score_manifest = pd.DataFrame(score_rows)
score_manifest.to_csv(SCORE_DIR / "manifest.csv", index=False)
display(score_manifest.head(20))

assert len(score_manifest) > 0
assert score_manifest["finite"].all()
assert (score_manifest["score_min"] >= -1e-6).all()
assert (score_manifest["score_max"] <= 1.0 + 1e-6).all()

for (category, split), g in score_manifest.groupby(["category", "split"]):
    r = g.iloc[0]
    arr = np.load(r["score_path"])
    assert arr.shape == (int(r["H"]), int(r["W"]))
    assert np.isfinite(arr).all()

WEEK3_STATUS["anomaly_scoring"] = "DEV_PASS" if FAST_DEV_RUN else "PASS"

print("Frozen DINOv3 anomaly scoring:",
      WEEK3_STATUS["anomaly_scoring"])
print("Score maps:", SCORE_DIR)

Score | fabric | validation:   0%|          | 0/43 [00:00<?, ?it/s]

Score | fabric | test_public:   0%|          | 0/156 [00:00<?, ?it/s]

Score | fabric | test_private:   0%|          | 0/314 [00:00<?, ?it/s]

Score | fabric | test_private_mixed:   0%|          | 0/314 [00:00<?, ?it/s]

Score | rice | validation:   0%|          | 0/35 [00:00<?, ?it/s]

Score | rice | test_public:   0%|          | 0/132 [00:00<?, ?it/s]

Score | rice | test_private:   0%|          | 0/277 [00:00<?, ?it/s]

Score | rice | test_private_mixed:   0%|          | 0/277 [00:00<?, ?it/s]

Score | sheet_metal | validation:   0%|          | 0/19 [00:00<?, ?it/s]

Score | sheet_metal | test_public:   0%|          | 0/114 [00:00<?, ?it/s]

Score | sheet_metal | test_private:   0%|          | 0/142 [00:00<?, ?it/s]

Score | sheet_metal | test_private_mixed:   0%|          | 0/142 [00:00<?, ?it/s]

,category,split,index,sample_id,image_path,H,W,n_tiles,runtime_s,peak_vram_mb,score_min,score_max,score_mean,finite,score_path,has_gt_mask
0,fabric,validation,0,023_regular_fa0c7ab25c,/content/msila/src/data/fabric/validation/good...,2048,2448,35,2.447191,357.505859,0.013791,0.130069,0.047169,True,/content/msila/outputs/week03/score_maps/valid...,False
1,fabric,validation,1,002_regular_d81bcae524,/content/msila/src/data/fabric/validation/good...,2048,2448,35,2.160567,357.505859,0.016892,0.138358,0.050946,True,/content/msila/outputs/week03/score_maps/valid...,True
2,fabric,validation,2,026_regular_bb5748ceb9,/content/msila/src/data/fabric/validation/good...,2048,2448,35,2.164265,357.505859,0.015016,0.135093,0.049679,True,/content/msila/outputs/week03/score_maps/valid...,False
3,fabric,validation,3,027_regular_a2b0babbdf,/content/msila/src/data/fabric/validation/good...,2048,2448,35,2.246726,357.505859,0.015022,0.136765,0.048753,True,/content/msila/outputs/week03/score_maps/valid...,False
4,fabric,validation,4,020_regular_2c05fe4a69,/content/msila/src/data/fabric/validation/good...,2048,2448,35,2.115729,357.505859,0.015408,0.138150,0.050536,True,/content/msila/outputs/week03/score_maps/valid...,False
5,fabric,validation,5,032_regular_c660c0fa97,/content/msila/src/data/fabric/validation/good...,2048,2448,35,2.137054,357.505859,0.014392,0.146308,0.048656,True,/content/msila/outputs/week03/score_maps/valid...,False
6,fabric,validation,6,029_regular_166a9b987b,/content/msila/src/data/fabric/validation/good...,2048,2448,35,2.230562,357.505859,0.018797,0.127055,0.056030,True,/content/msila/outputs/week03/score_maps/valid...,False
7,fabric,validation,7,005_regular_4010fdc5a8,/content/msila/src/data/fabric/validation/good...,2048,2448,35,2.176343,357.505859,0.014740,0.130619,0.046887,True,/content/msila/outputs/week03/score_maps/valid...,True
8,fabric,validation,8,031_regular_d1c64f412d,/content/msila/src/data/fabric/validation/good...,2048,2448,35,2.063803,357.505859,0.015985,0.141956,0.051258,True,/content/msila/outputs/week03/score_maps/valid...,False
9,fabric,validation,9,041_regular_a2f3497018,/content/msila/src/data/fabric/validation/good...,2048,2448,35,2.061546,357.505859,0.020529,0.128739,0.052934,True,/content/msila/outputs/week03/score_maps/valid...,False
10,fabric,validation,10,001_regular_85a50fc27a,/content/msila/src/data/fabric/validation/good...,2048,2448,35,2.087739,357.505859,0.016569,0.129872,0.049394,True,/content/msila/outputs/week03/score_maps/valid...,True
11,fabric,validation,11,007_regular_8913f28773,/content/msila/src/data/fabric/validation/good...,2048,2448,35,2.180352,357.505859,0.014361,0.134793,0.046554,True,/content/msila/outputs/week03/score_maps/valid...,True
12,fabric,validation,12,016_regular_9d40236bbc,/content/msila/src/data/fabric/validation/good...,2048,2448,35,2.236253,357.505859,0.015273,0.141171,0.048853,True,/content/msila/outputs/week03/score_maps/valid...,False
13,fabric,validation,13,034_regular_c4a55d8fcb,/content/msila/src/data/fabric/validation/good...,2048,2448,35,2.075344,357.505859,0.019163,0.130762,0.056980,True,/content/msila/outputs/week03/score_maps/valid...,False
14,fabric,validation,14,009_regular_4384f8f029,/content/msila/src/data/fabric/validation/good...,2048,2448,35,2.102196,357.505859,0.015249,0.129904,0.049211,True,/content/msila/outputs/week03/score_maps/valid...,True
15,fabric,validation,15,042_regular_dd46c625cb,/content/msila/src/data/fabric/validation/good...,2048,2448,35,2.086314,357.505859,0.015610,0.136137,0.050828,True,/content/msila/outputs/week03/score_maps/valid...,False
16,fabric,validation,16,024_regular_e74a33e452,/content/msila/src/data/fabric/validation/good...,2048,2448,35,2.133071,357.505859,0.019371,0.128664,0.050868,True,/content/msila/outputs/week03/score_maps/valid...,False
17,fabric,validation,17,011_regular_3c51b089d7,/content/msila/src/data/fabric/validation/good...,2048,2448,35,2.288540,357.505859,0.015170,0.145881,0.048751,True,/content/msila/outputs/week03/score_maps/valid...,True
18,fabric,validation,18,003_regular_65ee86a1f0,/content/msila/src/data/fabric/validation/good...,2048,2448,35,2.137871,357.505859,0.015408,0.138774,0.046105,True,/content/msila/outputs/week03/score_maps/valid...,True
19,fabric,validation,19,030_regular_6f00653318,/content/msila/src/data/fabric/validation/good...,2048,2448,35,2.123693,357.505859,0.018304,0.135529,0.051742,True,/content/msila/outputs/week03/score_maps/valid...,False

Frozen DINOv3 anomaly scoring: PASS
Score maps: /content/msila/outputs/week03/score_maps

## W3.2.5 — Scientific QA: soft score, không per-image min-max, không threshold

In [ ]:
qa = score_manifest.copy()

unique_counts = []
for p in qa["score_path"].head(min(20, len(qa))):
    arr = np.load(p)
    unique_counts.append(np.unique(arr).size)

print("Unique-value counts (first maps):", unique_counts)

assert max(unique_counts) > 2, (
    "Score maps appear binary/discrete; task yêu cầu soft anomaly maps."
)

print("Soft-score QA: PASS")

Unique-value counts (first maps): [4281756, 4248081, 4214392, 4243399, 4228485, 4261403, 4097535, 4336830, 4206415, 4084582, 4213954, 4286255, 4260819, 4076452, 4253060, 4227351, 4114274, 4259842, 4292214, 4185696]
Soft-score QA: PASS

# W3.3 — Two-task gate + report

Không hard-code `PASS`. Notebook chỉ ghi PASS sau khi acceptance cells thực sự chạy qua.

In [ ]:
final_ok = (
    WEEK3_STATUS["normal_representation"] == "PASS"
    and WEEK3_STATUS["anomaly_scoring"] == "PASS"
)

report = f"""# Week 03 — Frozen DINOv3 control

## Status

| Task | Status |
|---|---|
| Frozen DINOv3 normal representation | {WEEK3_STATUS['normal_representation']} |
| Frozen DINOv3 anomaly scoring | {WEEK3_STATUS['anomaly_scoring']} |

## Locked scientific choices

- Backbone: `{DINOV3_MODEL}`, fully frozen.
- Layers: `{RESOLVED_LAYERS}`.
- Local: `{LOCAL_TILE_SIZE}x{LOCAL_TILE_SIZE}`, overlap `{LOCAL_OVERLAP}`.
- Context: native `{CONTEXT_SIZE}x{CONTEXT_SIZE}` -> backbone `{CONTEXT_OUT_SIZE}x{CONTEXT_OUT_SIZE}`.
- Normal representation: category/layer/view-specific spherical prototype bank.
- K prototypes: `{N_PROTOTYPES}`.
- Patch score: `(1 - max cosine similarity) / 2`.
- Multi-layer fusion: uniform mean.
- Local/context fusion: 0.5 / 0.5 after context central-FOV alignment.
- Full-resolution reconstruction: Hann stitching.
- Per-image min-max: NO.
- Threshold/morphology: NO.
- FAST_DEV_RUN: `{FAST_DEV_RUN}`.

## Evidence

- `outputs/week03/normal_representation/manifest.csv`
- `outputs/week03/normal_representation/<category>.pt`
- `outputs/week03/score_maps/manifest.csv`
- `outputs/week03/score_maps/<split>/<category>/*.npy`
"""

report_path = DOCS_DIR / "week03_frozen_dinov3_control.md"
report_path.write_text(report, encoding="utf-8")

print(report)
print("Report:", report_path)

if FAST_DEV_RUN:
    print("DEV RUN complete. Set FAST_DEV_RUN=False for final Week-03 PASS.")
else:
    assert final_ok
    print("WEEK 03 TWO-TASK GATE: PASS")

# Week 03 — Frozen DINOv3 control

## Status

| Task | Status |
|---|---|
| Frozen DINOv3 normal representation | PASS |
| Frozen DINOv3 anomaly scoring | PASS |

## Locked scientific choices

- Backbone: `dinov3_vits16`, fully frozen.
- Layers: `[8, 10, 11]`.
- Local: `512x512`, overlap `128`.
- Context: native `768x768` -> backbone `512x512`.
- Normal representation: category/layer/view-specific spherical prototype bank.
- K prototypes: `64`.
- Patch score: `(1 - max cosine similarity) / 2`.
- Multi-layer fusion: uniform mean.
- Local/context fusion: 0.5 / 0.5 after context central-FOV alignment.
- Full-resolution reconstruction: Hann stitching.
- Per-image min-max: NO.
- Threshold/morphology: NO.
- FAST_DEV_RUN: `False`.

## Evidence

- `outputs/week03/normal_representation/manifest.csv`
- `outputs/week03/normal_representation/<category>.pt`
- `outputs/week03/score_maps/manifest.csv`
- `outputs/week03/score_maps/<split>/<category>/*.npy`

Report: /content/msila/docs/week03_frozen_dinov3_control.md
WEEK 03 TWO-TASK GATE: PASS

# Lưu GG driver

In [ ]:
# ============================================================
# W3 FINAL — Backup Week 3 outputs to Google Drive
# ============================================================

from pathlib import Path
import shutil
import time

timestamp = time.strftime("%Y%m%d_%H%M%S")
LOCAL_W3_OUTPUT = PROJECT_ROOT / "outputs" / "week03"

destination = f"/content/drive/MyDrive/CV-Nhóm 9/outputs/week03_{timestamp}"
DRIVE_W3_OUTPUT = Path(destination)

assert LOCAL_W3_OUTPUT.exists(), (
    f"Không tìm thấy local Week 3 output: {LOCAL_W3_OUTPUT}"
)

DRIVE_W3_OUTPUT.parent.mkdir(parents=True, exist_ok=True)

if DRIVE_W3_OUTPUT.exists():
    # Đổi tên thư mục cũ thành output_backup_thờigian để không bị mất
    timestamp = time.strftime("%Y%m%d_%H%M%S")
    backup_path = DRIVE_W3_OUTPUT.parent / f"output_backup_{timestamp}"

    # Đổi tên/Di chuyển thư mục cũ sang backup
    DRIVE_W3_OUTPUT.rename(backup_path)
    print(f"Đã sao lưu dữ liệu cũ sang: {backup_path}")

print("Copying Week 3 outputs:")
print("FROM:", LOCAL_W3_OUTPUT)
print("TO  :", DRIVE_W3_OUTPUT)

shutil.copytree(
    LOCAL_W3_OUTPUT,
    DRIVE_W3_OUTPUT,
)

print("Backup Week 3 -> Google Drive COMPLETE.")

Copying Week 3 outputs:
FROM: /content/msila/outputs/week03
TO  : /content/drive/MyDrive/CV-Nhóm 9/outputs/week03_20260913_103652

Error: [('/content/msila/outputs/week03/score_maps/test_private_mixed/rice/083_mixed_1496fc74be.npy', '/content/drive/MyDrive/CV-Nhóm 9/outputs/week03_20260913_103652/score_maps/test_private_mixed/rice/083_mixed_1496fc74be.npy', "[Errno 28] No space left on device: '/content/msila/outputs/week03/score_maps/test_private_mixed/rice/083_mixed_1496fc74be.npy' -> '/content/drive/MyDrive/CV-Nhóm 9/outputs/week03_20260913_103652/score_maps/test_private_mixed/rice/083_mixed_1496fc74be.npy'"), ('/content/msila/outputs/week03/score_maps/test_private_mixed/rice/250_mixed_c519f080e4.npy', '/content/drive/MyDrive/CV-Nhóm 9/outputs/week03_20260913_103652/score_maps/test_private_mixed/rice/250_mixed_c519f080e4.npy', "[Errno 28] No space left on device: '/content/msila/outputs/week03/score_maps/test_private_mixed/rice/250_mixed_c519f080e4.npy' -> '/content/drive/MyDrive/CV-Nhóm 9/outputs/week03_20260913_103652/score_maps/test_private_mixed/rice/250_mixed_c519f080e4.npy'"), ('/content/msila/outputs/week03/score_maps/test_private_mixed/rice/079_mixed_255764682b.npy', '/content/drive/MyDrive/CV-Nhóm 9/outputs/week03_20260913_103652/score_maps/test_private_mixed/rice/079_mixed_255764682b.npy', "[Errno 28] No space left on device: '/content/msila/outputs/week03/score_maps/test_private_mixed/rice/079_mixed_255764682b.npy' -> '/content/drive/MyDrive/CV-Nhóm 9/outputs/week03_20260913_103652/score_maps/test_private_mixed/rice/079_mixed_255764682b.npy'"), ('/content/msila/outputs/week03/score_maps/test_private_mixed/rice/143_mixed_16b7716004.npy', '/content/drive/MyDrive/CV-Nhóm 9/outputs/week03_20260913_103652/score_maps/test_private_mixed/rice/143_mixed_16b7716004.npy', "[Errno 28] No space left on device: '/content/msila/outputs/week03/score_maps/test_private_mixed/rice/143_mixed_16b7716004.npy' -> '/content/drive/MyDrive/CV-Nhóm 9/outputs/week03_20260913_103652/score_maps/test_private_mixed/rice/143_mixed_16b7716004.npy'"), ('/content/msila/outputs/week03/score_maps/test_private_mixed/rice/125_mixed_8db7978437.npy', '/content/drive/MyDrive/CV-Nhóm 9/outputs/week03_20260913_103652/score_maps/test_private_mixed/rice/125_mixed_8db7978437.npy', "[Errno 28] No space left on device: '/content/msila/outputs/week03/score_maps/test_private_mixed/rice/125_mixed_8db7978437.npy' -> '/content/drive/MyDrive/CV-Nhóm 9/outputs/week03_20260913_103652/score_maps/test_private_mixed/rice/125_mixed_8db7978437.npy'"), ('/content/msila/outputs/week03/score_maps/test_private_mixed/rice/073_mixed_a2cce6ca09.npy', '/content/drive/MyDrive/CV-Nhóm 9/outputs/week03_20260913_103652/score_maps/test_private_mixed/rice/073_mixed_a2cce6ca09.npy', "[Errno 28] No space left on device: '/content/msila/outputs/week03/score_maps/test_private_mixed/rice/073_mixed_a2cce6ca09.npy' -> '/content/drive/MyDrive/CV-Nhóm 9/outputs/week03_20260913_103652/score_maps/test_private_mixed/rice/073_mixed_a2cce6ca09.npy'"), ('/content/msila/outputs/week03/score_maps/test_private_mixed/rice/121_mixed_90b9fe1e7a.npy', '/content/drive/MyDrive/CV-Nhóm 9/outputs/week03_20260913_103652/score_maps/test_private_mixed/rice/121_mixed_90b9fe1e7a.npy', "[Errno 28] No space left on device: '/content/msila/outputs/week03/score_maps/test_private_mixed/rice/121_mixed_90b9fe1e7a.npy' -> '/content/drive/MyDrive/CV-Nhóm 9/outputs/week03_20260913_103652/score_maps/test_private_mixed/rice/121_mixed_90b9fe1e7a.npy'"), ('/content/msila/outputs/week03/score_maps/test_private_mixed/rice/188_mixed_cce8a0c29a.npy', '/content/drive/MyDrive/CV-Nhóm 9/outputs/week03_20260913_103652/score_maps/test_private_mixed/rice/188_mixed_cce8a0c29a.npy', "[Errno 28] No space left on device: '/content/msila/outputs/week03/score_maps/test_private_mixed/rice/188_mixed_cce8a0c29a.npy' -> '/content/drive/MyDrive/CV-Nhóm 9/outputs/week03_20260913_103652/score_maps/test_private_mixed/rice/188_mixed_cce8a0c29a.npy'"), ('/content/msila/outputs/week03/score_maps/test_private_mixed/rice/094_mixed_6335c171bf.npy', '/content/drive/MyDrive/CV-Nhóm 9/outputs/week03_20260913_103652/score_maps/test_private_mixed/rice/094_mixed_6335c171bf.npy', "[Errno 28] No space left on device: '/content/msila/outputs/week03/score_maps/test_private_mixed/rice/094_mixed_6335c171bf.npy' -> '/content/drive/MyDrive/CV-Nhóm 9/outputs/week03_20260913_103652/score_maps/test_private_mixed/rice/094_mixed_6335c171bf.npy'"), ('/content/msila/outputs/week03/score_maps/test_private_mixed/rice/022_mixed_44216b8df1.npy', '/content/drive/MyDrive/CV-Nhóm 9/outputs/week03_20260913_103652/score_maps/test_private_mixed/rice/022_mixed_44216b8df1.npy', "[Errno 28] No space left on device: '/content/msila/outputs/week03/score_maps/test_private_mixed/rice/022_mixed_44216b8df1.npy' -> '/content/drive/MyDrive/CV-Nhóm 9/outputs/week03_20260913_103652/score_maps/test_private_mixed/rice/022_mixed_44216b8df1.npy'"), ('/content/msila/outputs/week03/score_maps/test_private_mixed/rice/110_mixed_0cb95a004b.npy', '/content/drive/MyDrive/CV-Nhóm 9/outputs/week03_20260913_103652/score_maps/test_private_mixed/rice/110_mixed_0cb95a004b.npy', "[Errno 28] No space left on device: '/content/msila/outputs/week03/score_maps/test_private_mixed/rice/110_mixed_0cb95a004b.npy' -> '/content/drive/MyDrive/CV-Nhóm 9/outputs/week03_20260913_103652/score_maps/test_private_mixed/rice/110_mixed_0cb95a004b.npy'"), ('/content/msila/outputs/week03/score_maps/test_private_mixed/rice/221_mixed_9297a8cc3b.npy', '/content/drive/MyDrive/CV-Nhóm 9/outputs/week03_20260913_103652/score_maps/test_private_mixed/rice/221_mixed_9297a8cc3b.npy', "[Errno 28] No space left on device: '/content/msila/outputs/week03/score_maps/test_private_mixed/rice/221_mixed_9297a8cc3b.npy' -> '/content/drive/MyDrive/CV-Nhóm 9/outputs/week03_20260913_103652/score_maps/test_private_mixed/rice/221_mixed_9297a8cc3b.npy'"), ('/content/msila/outputs/week03/score_maps/test_private_mixed/rice/237_mixed_4321adc5ee.npy', '/content/drive/MyDrive/CV-Nhóm 9/outputs/week03_20260913_103652/score_maps/test_private_mixed/rice/237_mixed_4321adc5ee.npy', "[Errno 28] No space left on device: '/content/msila/outputs/week03/score_maps/test_private_mixed/rice/237_mixed_4321adc5ee.npy' -> '/content/drive/MyDrive/CV-Nhóm 9/outputs/week03_20260913_103652/score_maps/test_private_mixed/rice/237_mixed_4321adc5ee.npy'"), ('/content/msila/outputs/week03/score_maps/test_private_mixed/rice/202_mixed_4c33e5b851.npy', '/content/drive/MyDrive/CV-Nhóm 9/outputs/week03_20260913_103652/score_maps/test_private_mixed/rice/202_mixed_4c33e5b851.npy', "[Errno 28] No space left on device: '/content/msila/outputs/week03/score_maps/test_private_mixed/rice/202_mixed_4c33e5b851.npy' -> '/content/drive/MyDrive/CV-Nhóm 9/outputs/week03_20260913_103652/score_maps/test_private_mixed/rice/202_mixed_4c33e5b851.npy'"), ('/content/msila/outputs/week03/score_maps/test_private_mixed/rice/006_mixed_3b74d8c211.npy', '/content/drive/MyDrive/CV-Nhóm 9/outputs/week03_20260913_103652/score_maps/test_private_mixed/rice/006_mixed_3b74d8c211.npy', "[Errno 28] No space left on device: '/content/msila/outputs/week03/score_maps/test_private_mixed/rice/006_mixed_3b74d8c211.npy' -> '/content/drive/MyDrive/CV-Nhóm 9/outputs/week03_20260913_103652/score_maps/test_private_mixed/rice/006_mixed_3b74d8c211.npy'"), ('/content/msila/outputs/week03/score_maps/test_private_mixed/rice/261_mixed_4df19310ac.npy', '/content/drive/MyDrive/CV-Nhóm 9/outputs/week03_20260913_103652/score_maps/test_private_mixed/rice/261_mixed_4df19310ac.npy', "[Errno 28] No space left on device: '/content/msila/outputs/week03/score_maps/test_private_mixed/rice/261_mixed_4df19310ac.npy' -> '/content/drive/MyDrive/CV-Nhóm 9/outputs/week03_20260913_103652/score_maps/test_private_mixed/rice/261_mixed_4df19310ac.npy'"), ('/content/msila/outputs/week03/score_maps/test_private_mixed/rice/204_mixed_72fbcceb03.npy', '/content/drive/MyDrive/CV-Nhóm 9/outputs/week03_20260913_103652/score_maps/test_private_mixed/rice/204_mixed_72fbcceb03.npy', "[Errno 28] No space left on device: '/content/msila/outputs/week03/score_maps/test_private_mixed/rice/204_mixed_72fbcceb03.npy' -> '/content/drive/MyDrive/CV-Nhóm 9/outputs/week03_20260913_103652/score_maps/test_private_mixed/rice/204_mixed_72fbcceb03.npy'"), ('/content/msila/outputs/week03/score_maps/test_private_mixed/rice/058_mixed_b71219bd9e.npy', '/content/drive/MyDrive/CV-Nhóm 9/outputs/week03_20260913_103652/score_maps/test_private_mixed/rice/058_mixed_b71219bd9e.npy', "[Errno 28] No space left on device: '/content/msila/outputs/week03/score_maps/test_private_mixed/rice/058_mixed_b71219bd9e.npy' -> '/content/drive/MyDrive/CV-Nhóm 9/outputs/week03_20260913_103652/score_maps/test_private_mixed/rice/058_mixed_b71219bd9e.npy'"), ('/content/msila/outputs/week03/score_maps/test_private_mixed/rice/159_mixed_5b398a9dce.npy', '/content/drive/MyDrive/CV-Nhóm 9/outputs/week03_20260913_103652/score_maps/test_private_mixed/rice/159_mixed_5b398a9dce.npy', "[Errno 28] No space left on device: '/content/msila/outputs/week03/score_maps/test_private_mixed/rice/159_mixed_5b398a9dce.npy' -> '/content/drive/MyDrive/CV-Nhóm 9/outputs/week03_20260913_103652/score_maps/test_private_mixed/rice/159_mixed_5b398a9dce.npy'"), ('/content/msila/outputs/week03/score_maps/test_private_mixed/rice/205_mixed_d92860797d.npy', '/content/drive/MyDrive/CV-Nhóm 9/outputs/week03_20260913_103652/score_maps/test_private_mixed/rice/205_mixed_d92860797d.npy', "[Errno 28] No space left on device: '/content/msila/outputs/week03/score_maps/test_private_mixed/rice/205_mixed_d92860797d.npy' -> '/content/drive/MyDrive/CV-Nhóm 9/outputs/week03_20260913_103652/score_maps/test_private_mixed/rice/205_mixed_d92860797d.npy'"), ('/content/msila/outputs/week03/score_maps/test_private_mixed/rice/137_mixed_2f07e44c41.npy', '/content/drive/MyDrive/CV-Nhóm 9/outputs/week03_20260913_103652/score_maps/test_private_mixed/rice/137_mixed_2f07e44c41.npy', "[Errno 28] No space left on device: '/content/msila/outputs/week03/score_maps/test_private_mixed/rice/137_mixed_2f07e44c41.npy' -> '/content/drive/MyDrive/CV-Nhóm 9/outputs/week03_20260913_103652/score_maps/test_private_mixed/rice/137_mixed_2f07e44c41.npy'"), ('/content/msila/outputs/week03/score_maps/test_private_mixed/rice/217_mixed_a778004cb3.npy', '/content/drive/MyDrive/CV-Nhóm 9/outputs/week03_20260913_103652/score_maps/test_private_mixed/rice/217_mixed_a778004cb3.npy', "[Errno 28] No space left on device: '/content/msila/outputs/week03/score_maps/test_private_mixed/rice/217_mixed_a778004cb3.npy' -> '/content/drive/MyDrive/CV-Nhóm 9/outputs/week03_20260913_103652/score_maps/test_private_mixed/rice/217_mixed_a778004cb3.npy'"), ('/content/msila/outputs/week03/score_maps/test_private_mixed/rice/050_mixed_08e6a4d540.npy', '/content/drive/MyDrive/CV-Nhóm 9/outputs/week03_20260913_103652/score_maps/test_private_mixed/rice/050_mixed_08e6a4d540.npy', "[Errno 28] No space left on device: '/content/msila/outputs/week03/score_maps/test_private_mixed/rice/050_mixed_08e6a4d540.npy' -> '/content/drive/MyDrive/CV-Nhóm 9/outputs/week03_20260913_103652/score_maps/test_private_mixed/rice/050_mixed_08e6a4d540.npy'"), ('/content/msila/outputs/week03/score_maps/test_private_mixed/rice/216_mixed_2dc32a0d37.npy', '/content/drive/MyDrive/CV-Nhóm 9/outputs/week03_20260913_103652/score_maps/test_private_mixed/rice/216_mixed_2dc32a0d37.npy', "[Errno 28] No space left on device: '/content/msila/outputs/week03/score_maps/test_private_mixed/rice/216_mixed_2dc32a0d37.npy' -> '/content/drive/MyDrive/CV-Nhóm 9/outputs/week03_20260913_103652/score_maps/test_private_mixed/rice/216_mixed_2dc32a0d37.npy'"), ('/content/msila/outputs/week03/score_maps/test_private_mixed/rice/267_mixed_9674fccbe0.npy', '/content/drive/MyDrive/CV-Nhóm 9/outputs/week03_20260913_103652/score_maps/test_private_mixed/rice/267_mixed_9674fccbe0.npy', "[Errno 28] No space left on device: '/content/msila/outputs/week03/score_maps/test_private_mixed/rice/267_mixed_9674fccbe0.npy' -> '/content/drive/MyDrive/CV-Nhóm 9/outputs/week03_20260913_103652/score_maps/test_private_mixed/rice/267_mixed_9674fccbe0.npy'"), ('/content/msila/outputs/week03/score_maps/test_private_mixed/rice/211_mixed_938a6a5da7.npy', '/content/drive/MyDrive/CV-Nhóm 9/outputs/week03_20260913_103652/score_maps/test_private_mixed/rice/211_mixed_938a6a5da7.npy', "[Errno 28] No space left on device: '/content/msila/outputs/week03/score_maps/test_private_mixed/rice/211_mixed_938a6a5da7.npy' -> '/content/drive/MyDrive/CV-Nhóm 9/outputs/week03_20260913_103652/score_maps/test_private_mixed/rice/211_mixed_938a6a5da7.npy'"), ('/content/msila/outputs/week03/score_maps/test_private_mixed/rice/035_mixed_fb4c183fc6.npy', '/content/drive/MyDrive/CV-Nhóm 9/outputs/week03_20260913_103652/score_maps/test_private_mixed/rice/035_mixed_fb4c183fc6.npy', "[Errno 28] No space left on device: '/content/msila/outputs/week03/score_maps/test_private_mixed/rice/035_mixed_fb4c183fc6.npy' -> '/content/drive/MyDrive/CV-Nhóm 9/outputs/week03_20260913_103652/score_maps/test_private_mixed/rice/035_mixed_fb4c183fc6.npy'"), ('/content/msila/outputs/week03/score_maps/test_private_mixed/rice/056_mixed_aa95d54baf.npy', '/content/drive/MyDrive/CV-Nhóm 9/outputs/week03_20260913_103652/score_maps/test_private_mixed/rice/056_mixed_aa95d54baf.npy', "[Errno 28] No space left on device: '/content/msila/outputs/week03/score_maps/test_private_mixed/rice/056_mixed_aa95d54baf.npy' -> '/content/drive/MyDrive/CV-Nhóm 9/outputs/week03_20260913_103652/score_maps/test_private_mixed/rice/056_mixed_aa95d54baf.npy'"), ('/content/msila/outputs/week03/score_maps/test_private_mixed/rice/262_mixed_16ea5aa744.npy', '/content/drive/MyDrive/CV-Nhóm 9/outputs/week03_20260913_103652/score_maps/test_private_mixed/rice/262_mixed_16ea5aa744.npy', "[Errno 28] No space left on device: '/content/msila/outputs/week03/score_maps/test_private_mixed/rice/262_mixed_16ea5aa744.npy' -> '/content/drive/MyDrive/CV-Nhóm 9/outputs/week03_20260913_103652/score_maps/test_private_mixed/rice/262_mixed_16ea5aa744.npy'"), ('/content/msila/outputs/week03/score_maps/test_private_mixed/rice/235_mixed_8be30f99e2.npy', '/content/drive/MyDrive/CV-Nhóm 9/outputs/week03_20260913_103652/score_maps/test_private_mixed/rice/235_mixed_8be30f99e2.npy', "[Errno 28] No space left on device: '/content/msila/outputs/week03/score_maps/test_private_mixed/rice/235_mixed_8be30f99e2.npy' -> '/content/drive/MyDrive/CV-Nhóm 9/outputs/week03_20260913_103652/score_maps/test_private_mixed/rice/235_mixed_8be30f99e2.npy'"), ('/content/msila/outputs/week03/score_maps/test_private_mixed/rice/007_mixed_3510f74058.npy', '/content/drive/MyDrive/CV-Nhóm 9/outputs/week03_20260913_103652/score_maps/test_private_mixed/rice/007_mixed_3510f74058.npy', "[Errno 28] No space left on device: '/content/msila/outputs/week03/score_maps/test_private_mixed/rice/007_mixed_3510f74058.npy' -> '/content/drive/MyDrive/CV-Nhóm 9/outputs/week03_20260913_103652/score_maps/test_private_mixed/rice/007_mixed_3510f74058.npy'"), ('/content/msila/outputs/week03/score_maps/test_private_mixed/rice/178_mixed_155a9d401a.npy', '/content/drive/MyDrive/CV-Nhóm 9/outputs/week03_20260913_103652/score_maps/test_private_mixed/rice/178_mixed_155a9d401a.npy', "[Errno 28] No space left on device: '/content/msila/outputs/week03/score_maps/test_private_mixed/rice/178_mixed_155a9d401a.npy' -> '/content/drive/MyDrive/CV-Nhóm 9/outputs/week03_20260913_103652/score_maps/test_private_mixed/rice/178_mixed_155a9d401a.npy'"), ('/content/msila/outputs/week03/score_maps/test_private_mixed/rice/155_mixed_6c0c7b8886.npy', '/content/drive/MyDrive/CV-Nhóm 9/outputs/week03_20260913_103652/score_maps/test_private_mixed/rice/155_mixed_6c0c7b8886.npy', "[Errno 28] No space left on device: '/content/msila/outputs/week03/score_maps/test_private_mixed/rice/155_mixed_6c0c7b8886.npy' -> '/content/drive/MyDrive/CV-Nhóm 9/outputs/week03_20260913_103652/score_maps/test_private_mixed/rice/155_mixed_6c0c7b8886.npy'"), ('/content/msila/outputs/week03/score_maps/test_private_mixed/rice/123_mixed_058a7151f3.npy', '/content/drive/MyDrive/CV-Nhóm 9/outputs/week03_20260913_103652/score_maps/test_private_mixed/rice/123_mixed_058a7151f3.npy', "[Errno 28] No space left on device: '/content/msila/outputs/week03/score_maps/test_private_mixed/rice/123_mixed_058a7151f3.npy' -> '/content/drive/MyDrive/CV-Nhóm 9/outputs/week03_20260913_103652/score_maps/test_private_mixed/rice/123_mixed_058a7151f3.npy'"), ('/content/msila/outputs/week03/score_maps/test_private_mixed/rice/102_mixed_4ecafd9bf1.npy', '/content/drive/MyDrive/CV-Nhóm 9/outputs/week03_20260913_103652/score_maps/test_private_mixed/rice/102_mixed_4ecafd9bf1.npy', "[Errno 28] No space left on device: '/content/msila/outputs/week03/score_maps/test_private_mixed/rice/102_mixed_4ecafd9bf1.npy' -> '/content/drive/MyDrive/CV-Nhóm 9/outputs/week03_20260913_103652/score_maps/test_private_mixed/rice/102_mixed_4ecafd9bf1.npy'"), ('/content/msila/outputs/week03/score_maps/test_private_mixed/rice/077_mixed_9f0a46262b.npy', '/content/drive/MyDrive/CV-Nhóm 9/outputs/week03_20260913_103652/score_maps/test_private_mixed/rice/077_mixed_9f0a46262b.npy', "[Errno 28] No space left on device: '/content/msila/outputs/week03/score_maps/test_private_mixed/rice/077_mixed_9f0a46262b.npy' -> '/content/drive/MyDrive/CV-Nhóm 9/outputs/week03_20260913_103652/score_maps/test_private_mixed/rice/077_mixed_9f0a46262b.npy'"), ('/content/msila/outputs/week03/score_maps/test_private_mixed/rice/241_mixed_06cdf79ebf.npy', '/content/drive/MyDrive/CV-Nhóm 9/outputs/week03_20260913_103652/score_maps/test_private_mixed/rice/241_mixed_06cdf79ebf.npy', "[Errno 28] No space left on device: '/content/msila/outputs/week03/score_maps/test_private_mixed/rice/241_mixed_06cdf79ebf.npy' -> '/content/drive/MyDrive/CV-Nhóm 9/outputs/week03_20260913_103652/score_maps/test_private_mixed/rice/241_mixed_06cdf79ebf.npy'"), ('/content/msila/outputs/week03/score_maps/test_private_mixed/rice/233_mixed_5197abd5e4.npy', '/content/drive/MyDrive/CV-Nhóm 9/outputs/week03_20260913_103652/score_maps/test_private_mixed/rice/233_mixed_5197abd5e4.npy', "[Errno 28] No space left on device: '/content/msila/outputs/week03/score_maps/test_private_mixed/rice/233_mixed_5197abd5e4.npy' -> '/content/drive/MyDrive/CV-Nhóm 9/outputs/week03_20260913_103652/score_maps/test_private_mixed/rice/233_mixed_5197abd5e4.npy'"), ('/content/msila/outputs/week03/score_maps/test_private_mixed/rice/179_mixed_acb97d1219.npy', '/content/drive/MyDrive/CV-Nhóm 9/outputs/week03_20260913_103652/score_maps/test_private_mixed/rice/179_mixed_acb97d1219.npy', "[Errno 28] No space left on device: '/content/msila/outputs/week03/score_maps/test_private_mixed/rice/179_mixed_acb97d1219.npy' -> '/content/drive/MyDrive/CV-Nhóm 9/outputs/week03_20260913_103652/score_maps/test_private_mixed/rice/179_mixed_acb97d1219.npy'"), ('/content/msila/outputs/week03/score_maps/test_private_mixed/rice/043_mixed_9265aa2e98.npy', '/content/drive/MyDrive/CV-Nhóm 9/outputs/week03_20260913_103652/score_maps/test_private_mixed/rice/043_mixed_9265aa2e98.npy', "[Errno 28] No space left on device: '/content/msila/outputs/week03/score_maps/test_private_mixed/rice/043_mixed_9265aa2e98.npy' -> '/content/drive/MyDrive/CV-Nhóm 9/outputs/week03_20260913_103652/score_maps/test_private_mixed/rice/043_mixed_9265aa2e98.npy'"), ('/content/msila/outputs/week03/score_maps/test_private_mixed/rice/246_mixed_19a2876d1b.npy', '/content/drive/MyDrive/CV-Nhóm 9/outputs/week03_20260913_103652/score_maps/test_private_mixed/rice/246_mixed_19a2876d1b.npy', "[Errno 28] No space left on device: '/content/msila/outputs/week03/score_maps/test_private_mixed/rice/246_mixed_19a2876d1b.npy' -> '/content/drive/MyDrive/CV-Nhóm 9/outputs/week03_20260913_103652/score_maps/test_private_mixed/rice/246_mixed_19a2876d1b.npy'"), ('/content/msila/outputs/week03/score_maps/test_private_mixed/rice/085_mixed_480171debf.npy', '/content/drive/MyDrive/CV-Nhóm 9/outputs/week03_2026

# Mapping task tuần 3 ↔ cell

| Task | Cell/section |
|---|---|
| Frozen DINOv3 checkpoint + zero trainable params | **W3.1.1** |
| Normal patch sampling | **W3.1.2–W3.1.3** |
| Normal category/layer/view representation | **W3.1.3** |
| Prototype norm/finite QA | **W3.1.3–W3.1.4** |
| Cosine anomaly score | **W3.2.1–W3.2.3** |
| Context → local FOV alignment | **W3.2.1** |
| Multi-layer uniform fusion | **W3.2.2** |
| Local/context 0.5/0.5 control | **W3.2.2** |
| Hann full-resolution score map | **W3.2.2** |
| Save soft `.npy` score maps | **W3.2.4** |
| Soft-map QA, no threshold | **W3.2.5** |
| Final two-task status report | **W3.3** |


# Fix out of memories GG Drive

In [3]:
# =====================================================================
# MS-ILA WEEK 3 — FULL RESUME / REPAIR FROM A FRESH COLAB
#
# MỤC TIÊU:
#   - week03_20260913_103652 là folder W3 DUY NHẤT / canonical.
#   - Duyệt artifact đã tồn tại.
#   - .pt hợp lệ            -> SKIP W3.1
#   - .pt thiếu nhưng .npz đủ -> rebuild KMeans từ .npz, KHÔNG chạy DINOv3 train
#   - .pt + .npz thiếu      -> chạy lại W3.1 đúng category đó
#   - từng .npy hợp lệ      -> SKIP inference ảnh đó
#   - .npy thiếu/hỏng       -> chỉ inference đúng ảnh đó
#   - ghi output trực tiếp bổ sung vào Google Drive
#   - xử lý dataset TỪNG CATEGORY một để tiết kiệm disk
#   - rebuild manifest
#   - chỉ sau khi scoring hoàn chỉnh mới regenerate preview PNG
#
# Có thể chạy lại cell nhiều lần. Nó sẽ tiếp tục từ nơi đã dừng.
# =====================================================================

# =====================================================================
# 0. MOUNT DRIVE
# =====================================================================

from google.colab import drive
drive.mount("/content/drive", force_remount=False)

# =====================================================================
# 1. IMPORT
# =====================================================================

import os
import sys
import re
import gc
import math
import time
import random
import hashlib
import shutil
import tarfile
import subprocess
import importlib.util

from pathlib import Path
from getpass import getpass

import numpy as np
import pandas as pd
import torch
import torch.nn.functional as F

from tqdm.auto import tqdm


# =====================================================================
# 2. CONFIG — CHỈ SỬA PHẦN NÀY NẾU PATH DRIVE KHÁC
# =====================================================================

W3_FOLDER_NAME = "week03_20260913_103652"

# Các vị trí có thể của folder team trên 2 account
TEAM_ROOT_CANDIDATES = [
    Path("/content/drive/MyDrive/[Q3-4] 2026/[S7] Computer Vision/CV-Nhóm 9/"
    ),
]

TEAM_ROOT = next(
    (p for p in TEAM_ROOT_CANDIDATES if p.exists()),
    None,
)

if TEAM_ROOT is None:
    raise FileNotFoundError(
        "Không tìm thấy folder CV-Nhóm 9 trên MyDrive.\n"
        "Hãy Add shortcut folder shared vào My Drive hoặc sửa "
        "TEAM_ROOT_CANDIDATES ở đầu cell."
    )

# Folder W3 canonical — KHÔNG tạo folder timestamp mới nữa
W3_OUTPUT_DIR = TEAM_ROOT / "outputs" / W3_FOLDER_NAME

if not W3_OUTPUT_DIR.exists():
    raise FileNotFoundError(
        f"Không tìm thấy folder Week 3 shared:\n{W3_OUTPUT_DIR}"
    )

# Dataset archive trên Drive
DRIVE_ARCHIVE_DIR = TEAM_ROOT / "data"

if not DRIVE_ARCHIVE_DIR.exists():
    raise FileNotFoundError(
        f"Không tìm thấy dataset archives:\n{DRIVE_ARCHIVE_DIR}\n\n"
        "Account mới cần được quyền truy cập/share folder data."
    )

# Weight
WEIGHTS_DIR = TEAM_ROOT / "weights"

weight_candidates = [
    WEIGHTS_DIR / "dinov3_vits16_pretrain_lvd1689m.pth",
    WEIGHTS_DIR / "dinov3_vits16_pretrain_lvd1689m-08c60483.pth",
]

DINOV3_WEIGHTS = next(
    (p for p in weight_candidates if p.exists()),
    None,
)

if DINOV3_WEIGHTS is None and WEIGHTS_DIR.exists():
    tmp = list(
        WEIGHTS_DIR.glob(
            "dinov3_vits16_pretrain_lvd1689m*.pth"
        )
    )
    if tmp:
        DINOV3_WEIGHTS = tmp[0]

if DINOV3_WEIGHTS is None:
    raise FileNotFoundError(
        f"Không tìm thấy DINOv3 ViT-S/16 weight trong:\n{WEIGHTS_DIR}\n\n"
        "Account mới cần được quyền truy cập/share folder weights."
    )

# Repo local mới
PROJECT_ROOT = Path("/content/msila")
DINOV3_REPO = Path("/content/dinov3_repo")

# Dataset local — chỉ giữ 1 category tại một thời điểm
DATA_ROOT = PROJECT_ROOT / "src" / "data"

# Output TRỰC TIẾP trên Drive
REP_DIR = W3_OUTPUT_DIR / "normal_representation"
NORMAL_FEATURE_DIR = W3_OUTPUT_DIR / "normal_features"
SCORE_DIR = W3_OUTPUT_DIR / "score_maps"

for p in [
    REP_DIR,
    NORMAL_FEATURE_DIR,
    SCORE_DIR,
]:
    p.mkdir(
        parents=True,
        exist_ok=True,
    )

# Week-2 locked protocol
LOCAL_TILE_SIZE = 512
LOCAL_OVERLAP = 128
CONTEXT_SIZE = 768
CONTEXT_OUT_SIZE = 512

DINOV3_MEAN = (0.485, 0.456, 0.406)
DINOV3_STD  = (0.229, 0.224, 0.225)

DINOV3_MODEL = "dinov3_vits16"
DINOV3_LAYER_IDS = [-4, -2, -1]

# ViT-S/16 depth=12 -> [-4,-2,-1] = [8,10,11]
EXPECTED_RESOLVED_LAYERS = [8, 10, 11]

N_PROTOTYPES = 64
PATCH_SAMPLES_PER_TILE_PER_VIEW = 64
MAX_FIT_PATCHES_PER_LAYER_VIEW = 30000

PAIR_BATCH_SIZE = 4
SEED = 42

SCORE_SPLITS = [
    # "validation",
    # "test_public",
    "test_private",
    "test_private_mixed",
]

# Sau khi TOÀN BỘ score map đầy đủ mới tạo preview
REGENERATE_PREVIEWS = True
N_PREVIEW_PER_CATEGORY_SPLIT = 5

# Nếu .pt đã có nhưng .npz cache thiếu:
# False = KHÔNG chạy DINOv3 lại chỉ vì thiếu cache -> tiết kiệm time
REBUILD_OPTIONAL_NPZ_IF_BANK_EXISTS = False

EXPECTED_DINOV3_SHA256 = (
    "08c60483bc63c04f533611e34bf70b120eedb7240f469bc16e9e20bf344b941d"
)

random.seed(SEED)
np.random.seed(SEED)
torch.manual_seed(SEED)

DEVICE = torch.device(
    "cuda"
    if torch.cuda.is_available()
    else "cpu"
)

if DEVICE.type != "cuda":
    raise RuntimeError(
        "Không có GPU. Hãy chọn Colab Runtime -> T4 GPU rồi chạy lại cell."
    )

print("=" * 80)
print("WEEK 3 RESUME")
print("=" * 80)
print("TEAM_ROOT :", TEAM_ROOT)
print("W3 OUTPUT :", W3_OUTPUT_DIR)
print("DATA      :", DRIVE_ARCHIVE_DIR)
print("WEIGHTS   :", DINOV3_WEIGHTS)
print("DEVICE    :", DEVICE)


# =====================================================================
# 3. CLONE / UPDATE MS-ILA
# =====================================================================

if PROJECT_ROOT.exists():

    print("\nMS-ILA repo đã tồn tại:", PROJECT_ROOT)

else:

    print("\nCloning MS-ILA...")

    public_url = (
        "https://github.com/"
        "haduckien-raccoon/msila.git"
    )

    result = subprocess.run(
        [
            "git",
            "clone",
            "--depth",
            "1",
            public_url,
            str(PROJECT_ROOT),
        ],
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        text=True,
    )

    if result.returncode != 0:

        print(
            "Repo yêu cầu quyền GitHub."
        )

        token = getpass(
            "Nhập GitHub PAT (input sẽ bị ẩn): "
        )

        private_url = (
            f"https://haduckien-raccoon:{token}"
            "@github.com/"
            "haduckien-raccoon/msila.git"
        )

        subprocess.run(
            [
                "git",
                "clone",
                "--depth",
                "1",
                private_url,
                str(PROJECT_ROOT),
            ],
            check=True,
        )

        del token
        del private_url


assert (
    PROJECT_ROOT / "src"
).exists()

if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(
        0,
        str(PROJECT_ROOT),
    )


# =====================================================================
# 4. IMPORT WEEK-2 LOCKED LOADER / TILING
# =====================================================================

from src.data.loader import MVTecAD2HighResDataset

from src.data.tiling import (
    generate_tile_records,
    extract_local_context,
    stitch_tiles_hann,
)


# =====================================================================
# 5. CATEGORY LIST TỪ 8 ARCHIVES
# =====================================================================

archives = sorted(
    DRIVE_ARCHIVE_DIR.glob(
        "*.tar.gz"
    )
)

if not archives:
    raise RuntimeError(
        f"Không có .tar.gz trong {DRIVE_ARCHIVE_DIR}"
    )

# CATEGORIES = [
#     p.name[:-7]
#     for p in archives
# ]
CATEGORIES = ["walnuts"]

print("\nCategories:", CATEGORIES)
print("N categories:", len(CATEGORIES))

if len(CATEGORIES) != 8:
    print(
        "WARNING: Không phát hiện đúng 8 archives. "
        "Cell vẫn chạy trên những category tìm được."
    )


# =====================================================================
# 6. DATASET EXTRACTION — 1 CATEGORY/LẦN
# =====================================================================

EXPECTED_SPLITS_SET = {
    "train",
    "validation",
    "test_public",
    "test_private",
    "test_private_mixed",
}


def safe_extract(tf, dest: Path):

    dest_r = dest.resolve()

    for member in tf.getmembers():

        target = (
            dest / member.name
        ).resolve()

        if (
            target != dest_r
            and dest_r not in target.parents
        ):
            raise RuntimeError(
                f"Unsafe tar path: {member.name}"
            )

    try:
        tf.extractall(
            dest,
            filter="data",
        )
    except TypeError:
        tf.extractall(dest)


def find_dataset_root(tmp: Path):

    candidates = []

    dirs = [tmp] + [
        p
        for p in tmp.rglob("*")
        if p.is_dir()
    ]

    for d in dirs:

        try:
            child = {
                x.name
                for x in d.iterdir()
                if x.is_dir()
            }
        except OSError:
            continue

        if child.intersection(
            EXPECTED_SPLITS_SET
        ):
            candidates.append(
                (
                    len(
                        d.relative_to(
                            tmp
                        ).parts
                    ),
                    d,
                )
            )

    if candidates:

        return sorted(
            candidates,
            key=lambda x: x[0],
        )[0][1]

    top_dirs = [
        p
        for p in tmp.iterdir()
        if p.is_dir()
    ]

    top_files = [
        p
        for p in tmp.iterdir()
        if p.is_file()
    ]

    if (
        len(top_dirs) == 1
        and not top_files
    ):
        return top_dirs[0]

    return tmp


def extract_category(category):

    archive = (
        DRIVE_ARCHIVE_DIR
        / f"{category}.tar.gz"
    )

    if not archive.exists():
        raise FileNotFoundError(
            archive
        )

    DATA_ROOT.mkdir(
        parents=True,
        exist_ok=True,
    )

    out_dir = (
        DATA_ROOT
        / category
    )

    # Nếu đã tồn tại đúng dataset
    if out_dir.exists():

        child = {
            p.name
            for p in out_dir.iterdir()
            if p.is_dir()
        }

        if child.intersection(
            EXPECTED_SPLITS_SET
        ):

            print(
                f"Dataset local exists: {category}"
            )

            return out_dir

        shutil.rmtree(out_dir)

    tmp = (
        Path("/content")
        / f"_extract_{category}"
    )

    if tmp.exists():
        shutil.rmtree(tmp)

    tmp.mkdir(
        parents=True,
        exist_ok=True,
    )

    print(
        f"\nExtract directly Drive -> SSD: {archive.name}"
    )

    # KHÔNG copy tar.gz xuống SSD
    with tarfile.open(
        archive,
        "r:gz",
    ) as tf:

        safe_extract(
            tf,
            tmp,
        )

    detected = find_dataset_root(
        tmp
    )

    if detected == tmp:

        tmp.rename(
            out_dir
        )

    else:

        shutil.move(
            str(detected),
            str(out_dir),
        )

        if tmp.exists():
            shutil.rmtree(tmp)

    return out_dir


def cleanup_category(category):

    p = (
        DATA_ROOT
        / category
    )

    if p.exists():

        print(
            f"Cleanup local dataset: {category}"
        )

        shutil.rmtree(p)

    tmp = (
        Path("/content")
        / f"_extract_{category}"
    )

    if tmp.exists():
        shutil.rmtree(tmp)

    gc.collect()

    if torch.cuda.is_available():
        torch.cuda.empty_cache()


# =====================================================================
# 7. HELPER
# =====================================================================

def norm_name(x):

    return re.sub(
        r"[^a-z0-9]+",
        "",
        str(x).lower(),
    )


def sha256_file(
    path,
    chunk_size=8 * 1024 * 1024,
):

    h = hashlib.sha256()

    with open(path, "rb") as f:

        for chunk in iter(
            lambda: f.read(
                chunk_size
            ),
            b"",
        ):
            h.update(chunk)

    return h.hexdigest()


def sample_id_from_meta(meta):

    p = Path(
        meta["path"]
    )

    token = hashlib.sha1(
        str(p).encode(
            "utf-8"
        )
    ).hexdigest()[:10]

    return (
        f"{p.stem}_{token}"
    )


def resolve_existing_category_dir(
    split_root: Path,
    category: str,
):

    exact = (
        split_root
        / category
    )

    if exact.exists():
        return exact

    if split_root.exists():

        matches = [
            p
            for p in split_root.iterdir()
            if (
                p.is_dir()
                and norm_name(p.name)
                == norm_name(category)
            )
        ]

        if len(matches) == 1:
            return matches[0]

    return exact


def resolve_bank_path(
    category,
):

    exact = (
        REP_DIR
        / f"{category}.pt"
    )

    if exact.exists():
        return exact

    matches = [
        p
        for p in REP_DIR.glob(
            "*.pt"
        )
        if norm_name(p.stem)
        == norm_name(category)
    ]

    if len(matches) == 1:
        return matches[0]

    return exact


# =====================================================================
# 8. CHECK SCORE FILE NHANH
#
# Không đọc toàn bộ 20 MB nếu file cũ hợp lệ.
# np.load(mmap) cũng phát hiện phần lớn file truncate/copy dở.
# =====================================================================

def score_file_valid(
    path: Path,
    H: int,
    W: int,
):

    if not path.exists():
        return False

    try:

        arr = np.load(
            path,
            mmap_mode="r",
            allow_pickle=False,
        )

        if arr.shape != (
            H,
            W,
        ):
            return False

        if arr.dtype != np.float32:
            return False

        # probe nhanh finite
        probes = [
            arr[0, 0],
            arr[H // 2, W // 2],
            arr[-1, -1],
        ]

        if not np.isfinite(
            probes
        ).all():
            return False

        return True

    except Exception:
        return False


def npz_feature_valid(
    path: Path,
):

    if not path.exists():
        return False

    try:

        with np.load(
            path,
            allow_pickle=False,
        ) as z:

            if "features" not in z.files:
                return False

            x = z["features"]

            return (
                x.ndim == 2
                and x.shape[0] > 0
                and x.shape[1] > 0
            )

    except Exception:
        return False


# =====================================================================
# 9. ATOMIC COPY -> DRIVE
# =====================================================================

def copy_atomic_to_drive(
    local_path: Path,
    drive_path: Path,
):

    drive_path.parent.mkdir(
        parents=True,
        exist_ok=True,
    )

    part = Path(
        str(drive_path)
        + ".part"
    )

    if part.exists():
        part.unlink()

    shutil.copy2(
        local_path,
        part,
    )

    if drive_path.exists():
        drive_path.unlink()

    part.replace(
        drive_path
    )


# Xóa artifact .part từ backup bị gián đoạn
for p in W3_OUTPUT_DIR.rglob(
    "*.part"
):
    try:
        p.unlink()
    except Exception:
        pass


# =====================================================================
# 10. LAZY DINOv3 LOAD
#
# Chỉ clone/load khi THỰC SỰ phát hiện file cần inference.
# Nếu Drive đã đủ -> không load DINOv3 luôn.
# =====================================================================

dinov3 = None
RESOLVED_LAYERS = EXPECTED_RESOLVED_LAYERS
actual_sha256 = EXPECTED_DINOV3_SHA256


def ensure_dinov3():

    global dinov3
    global RESOLVED_LAYERS
    global actual_sha256

    if dinov3 is not None:
        return dinov3

    print(
        "\nMissing artifact detected -> loading Frozen DINOv3..."
    )

    actual_sha256 = sha256_file(
        DINOV3_WEIGHTS
    )

    print(
        "Checkpoint SHA256:",
        actual_sha256
    )

    assert (
        actual_sha256
        == EXPECTED_DINOV3_SHA256
    ), (
        "DINOv3 checkpoint hash không đúng."
    )

    if not (
        DINOV3_REPO
        / "dinov3"
        / "hub"
        / "backbones.py"
    ).exists():

        print(
            "Clone official DINOv3..."
        )

        subprocess.run(
            [
                "git",
                "clone",
                "--depth",
                "1",
                "https://github.com/facebookresearch/dinov3.git",
                str(DINOV3_REPO),
            ],
            check=True,
        )

    repo_str = str(
        DINOV3_REPO.resolve()
    )

    if repo_str not in sys.path:
        sys.path.insert(
            0,
            repo_str,
        )

    from dinov3.hub import backbones as dinov3_backbones

    factory = getattr(
        dinov3_backbones,
        DINOV3_MODEL,
    )

    dinov3 = factory(
        pretrained=True,
        weights=str(
            DINOV3_WEIGHTS
        ),
        check_hash=False,
    )

    dinov3 = (
        dinov3
        .to(DEVICE)
        .eval()
    )

    for p in dinov3.parameters():
        p.requires_grad_(False)

    RESOLVED_LAYERS = []

    n_blocks = len(
        dinov3.blocks
    )

    for idx in DINOV3_LAYER_IDS:

        j = (
            idx
            if idx >= 0
            else n_blocks + idx
        )

        RESOLVED_LAYERS.append(
            j
        )

    assert (
        RESOLVED_LAYERS
        == EXPECTED_RESOLVED_LAYERS
    )

    assert sum(
        p.numel()
        for p in dinov3.parameters()
        if p.requires_grad
    ) == 0

    print(
        "Frozen DINOv3 loaded."
    )
    print(
        "Layers:",
        RESOLVED_LAYERS
    )

    return dinov3


# =====================================================================
# 11. DINO FEATURE FUNCTIONS
# =====================================================================

def _first_tensor(obj):

    if torch.is_tensor(obj):
        return obj

    if isinstance(
        obj,
        (tuple, list),
    ):
        for x in obj:
            t = _first_tensor(x)
            if t is not None:
                return t

    if isinstance(obj, dict):
        for x in obj.values():
            t = _first_tensor(x)
            if t is not None:
                return t

    return None


@torch.no_grad()
def forward_with_block_features(
    model,
    x,
    layer_ids,
):

    n = len(
        model.blocks
    )

    resolved = [
        i if i >= 0 else n + i
        for i in layer_ids
    ]

    feats = {}
    handles = []

    for j in resolved:

        def hook(
            module,
            inputs,
            output,
            j=j,
        ):

            t = _first_tensor(
                output
            )

            if t is None:
                raise RuntimeError(
                    f"No tensor at block {j}"
                )

            feats[j] = (
                t.detach()
            )

        handles.append(
            model.blocks[
                j
            ].register_forward_hook(
                hook
            )
        )

    try:
        _ = model(x)

    finally:

        for h in handles:
            h.remove()

    missing = [
        j
        for j in resolved
        if j not in feats
    ]

    if missing:
        raise RuntimeError(
            f"Missing features: {missing}"
        )

    return {
        j: feats[j]
        for j in resolved
    }


def feature_tensor_to_spatial_map(
    feat,
):

    if feat.ndim == 4:
        return feat

    if feat.ndim != 3:
        raise ValueError(
            feat.shape
        )

    B, N, C = feat.shape

    found = None

    for n_special in range(
        min(32, N - 1) + 1
    ):

        n_patch = (
            N - n_special
        )

        side = math.isqrt(
            n_patch
        )

        if (
            side * side
            == n_patch
        ):
            found = (
                n_special,
                side,
            )
            break

    if found is None:
        raise ValueError(
            f"Cannot infer grid N={N}"
        )

    n_special, side = found

    tokens = feat[
        :,
        n_special:,
        :
    ]

    return (
        tokens
        .transpose(1, 2)
        .contiguous()
        .reshape(
            B,
            C,
            side,
            side,
        )
    )


def normalize_batch_dinov3(x):

    mean = torch.tensor(
        DINOV3_MEAN,
        device=x.device,
        dtype=x.dtype,
    )[None, :, None, None]

    std = torch.tensor(
        DINOV3_STD,
        device=x.device,
        dtype=x.dtype,
    )[None, :, None, None]

    return (
        x - mean
    ) / std


# =====================================================================
# 12. NORMAL REPRESENTATION
# =====================================================================

class PriorityReservoir:

    def __init__(
        self,
        cap,
        seed,
    ):

        self.cap = int(cap)

        self.gen = torch.Generator(
            device="cpu"
        )

        self.gen.manual_seed(
            int(seed)
        )

        self.x = None
        self.key = None
        self.seen = 0


    def add(self, rows):

        rows = (
            rows
            .detach()
            .float()
            .cpu()
        )

        self.seen += (
            rows.shape[0]
        )

        keys = torch.rand(
            rows.shape[0],
            generator=self.gen,
        )

        if self.x is None:

            x = rows
            k = keys

        else:

            x = torch.cat(
                [
                    self.x,
                    rows,
                ],
                dim=0,
            )

            k = torch.cat(
                [
                    self.key,
                    keys,
                ],
                dim=0,
            )

        if (
            x.shape[0]
            > self.cap
        ):

            idx = torch.topk(
                k,
                k=self.cap,
                largest=True,
            ).indices

            x = x[idx]
            k = k[idx]

        self.x = x
        self.key = k


    def tensor(self):

        if (
            self.x is None
            or self.x.shape[0] == 0
        ):
            raise RuntimeError(
                "Empty reservoir"
            )

        return self.x


def sample_rows_per_tile(
    spatial_bchw,
    n_per_tile,
    generator,
):

    B, C, H, W = (
        spatial_bchw.shape
    )

    flat = (
        spatial_bchw
        .permute(
            0, 2, 3, 1
        )
        .reshape(
            B,
            H * W,
            C,
        )
    )

    rows = []

    for b in range(B):

        n = min(
            int(n_per_tile),
            H * W,
        )

        idx = torch.randperm(
            H * W,
            generator=generator,
        )[:n]

        rows.append(
            flat[
                b,
                idx.to(
                    flat.device
                ),
            ]
        )

    return torch.cat(
        rows,
        dim=0,
    )


def ensure_sklearn():

    if importlib.util.find_spec(
        "sklearn"
    ) is None:

        subprocess.run(
            [
                sys.executable,
                "-m",
                "pip",
                "install",
                "-q",
                "scikit-learn",
            ],
            check=True,
        )


def fit_spherical_prototypes(
    features_nc,
    n_prototypes=N_PROTOTYPES,
    seed=SEED,
):

    ensure_sklearn()

    from sklearn.cluster import MiniBatchKMeans

    x = F.normalize(
        features_nc.float(),
        dim=1,
        eps=1e-12,
    ).cpu().numpy()

    k = min(
        int(n_prototypes),
        x.shape[0],
    )

    km = MiniBatchKMeans(
        n_clusters=k,
        random_state=int(
            seed
        ),
        batch_size=min(
            4096,
            max(
                256,
                x.shape[0],
            ),
        ),
        n_init=3,
        max_iter=100,
        reassignment_ratio=0.01,
    )

    km.fit(x)

    centers = torch.from_numpy(
        km.cluster_centers_
    ).float()

    centers = F.normalize(
        centers,
        dim=1,
        eps=1e-12,
    )

    return (
        centers,
        float(km.inertia_),
    )


def feature_cache_path(
    category,
    layer,
    view,
):

    return (
        NORMAL_FEATURE_DIR
        / f"{category}_layer{layer}_{view}.npz"
    )


def save_feature_cache(
    category,
    layer,
    view,
    fit_x,
):

    dst = feature_cache_path(
        category,
        layer,
        view,
    )

    local = Path(
        f"/content/"
        f"_feature_{category}_{layer}_{view}.npz"
    )

    np.savez_compressed(
        local,
        features=(
            fit_x
            .cpu()
            .numpy()
            .astype(
                np.float16
            )
        ),
        category=np.array(
            category
        ),
        layer=np.int32(
            layer
        ),
        view=np.array(
            view
        ),
        checkpoint_sha256=np.array(
            EXPECTED_DINOV3_SHA256
        ),
    )

    copy_atomic_to_drive(
        local,
        dst,
    )

    local.unlink(
        missing_ok=True
    )


def bank_valid(
    path,
    category,
):

    if not path.exists():
        return False

    try:

        bank = torch.load(
            path,
            map_location="cpu",
            weights_only=False,
        )

        if (
            norm_name(
                bank["category"]
            )
            != norm_name(
                category
            )
        ):
            return False

        if (
            bank[
                "checkpoint_sha256"
            ]
            != EXPECTED_DINOV3_SHA256
        ):
            return False

        for layer in EXPECTED_RESOLVED_LAYERS:

            for view in [
                "local",
                "context",
            ]:

                x = bank[
                    "prototypes"
                ][layer][view]

                if (
                    x.ndim != 2
                    or x.shape[0] == 0
                    or not torch.isfinite(
                        x
                    ).all()
                ):
                    return False

        return True

    except Exception:
        return False


def all_feature_cache_available(
    category,
):

    for layer in EXPECTED_RESOLVED_LAYERS:

        for view in [
            "local",
            "context",
        ]:

            if not npz_feature_valid(
                feature_cache_path(
                    category,
                    layer,
                    view,
                )
            ):
                return False

    return True


def rebuild_bank_from_npz(
    category,
    ds_train,
):

    print(
        f"Rebuild .pt from cached .npz: {category}"
    )

    out = {
        "category": category,
        "model": DINOV3_MODEL,
        "checkpoint_sha256": EXPECTED_DINOV3_SHA256,
        "layers": EXPECTED_RESOLVED_LAYERS,
        "local_tile_size": LOCAL_TILE_SIZE,
        "local_overlap": LOCAL_OVERLAP,
        "context_size": CONTEXT_SIZE,
        "context_out_size": CONTEXT_OUT_SIZE,
        "n_train_images": len(ds_train),
        "n_tiles": None,
        "fast_dev_run": False,
        "prototypes": {},
        "meta": {},
        "rebuilt_from_npz": True,
    }

    for layer in EXPECTED_RESOLVED_LAYERS:

        out["prototypes"][
            layer
        ] = {}

        out["meta"][
            layer
        ] = {}

        for view in [
            "local",
            "context",
        ]:

            p = feature_cache_path(
                category,
                layer,
                view,
            )

            with np.load(
                p,
                allow_pickle=False,
            ) as z:

                fit_x = torch.from_numpy(
                    z["features"].astype(
                        np.float32
                    )
                )

            centers, inertia = (
                fit_spherical_prototypes(
                    fit_x,
                    n_prototypes=N_PROTOTYPES,
                    seed=SEED + layer,
                )
            )

            norm_err = float(
                (
                    centers.norm(dim=1)
                    - 1
                )
                .abs()
                .max()
            )

            out["prototypes"][
                layer
            ][view] = centers

            out["meta"][
                layer
            ][view] = {
                "seen_patch_samples": int(
                    fit_x.shape[0]
                ),
                "fit_patch_samples": int(
                    fit_x.shape[0]
                ),
                "n_prototypes": int(
                    centers.shape[0]
                ),
                "dim": int(
                    centers.shape[1]
                ),
                "kmeans_inertia": inertia,
                "max_prototype_norm_error": norm_err,
                "source": "cached_npz",
            }

    local_pt = Path(
        f"/content/{category}_bank.pt"
    )

    torch.save(
        out,
        local_pt,
    )

    dst = resolve_bank_path(
        category
    )

    copy_atomic_to_drive(
        local_pt,
        dst,
    )

    local_pt.unlink(
        missing_ok=True
    )

    return dst


@torch.no_grad()
def build_bank_from_dinov3(
    category,
    ds_train,
):

    model = ensure_dinov3()

    print(
        f"Run Frozen DINOv3 train-normal: {category}"
    )

    reservoirs = {}

    for layer in RESOLVED_LAYERS:

        for view in [
            "local",
            "context",
        ]:

            reservoirs[
                (
                    layer,
                    view,
                )
            ] = PriorityReservoir(
                MAX_FIT_PATCHES_PER_LAYER_VIEW,
                seed=(
                    SEED
                    + 1000 * layer
                    + (
                        0
                        if view == "local"
                        else 1
                    )
                ),
            )

    patch_gen = torch.Generator(
        device="cpu"
    )

    patch_gen.manual_seed(
        SEED
        + sum(
            ord(c)
            for c in category
        )
    )

    n_tiles_total = 0

    for i in tqdm(
        range(len(ds_train)),
        desc=f"Normal repr | {category}",
    ):

        sample = ds_train[i]
        image = sample["image"]

        H, W = image.shape[-2:]

        records = generate_tile_records(
            H,
            W,
            local_size=LOCAL_TILE_SIZE,
            overlap=LOCAL_OVERLAP,
            context_size=CONTEXT_SIZE,
        )

        n_tiles_total += len(
            records
        )

        for start in range(
            0,
            len(records),
            PAIR_BATCH_SIZE,
        ):

            chunk = records[
                start:
                start + PAIR_BATCH_SIZE
            ]

            pair = []

            for rec in chunk:

                local_img, context_img = (
                    extract_local_context(
                        image,
                        rec,
                        local_out_size=LOCAL_TILE_SIZE,
                        context_out_size=CONTEXT_OUT_SIZE,
                    )
                )

                pair.extend(
                    [
                        local_img,
                        context_img,
                    ]
                )

            x = torch.stack(
                pair,
                dim=0,
            ).to(DEVICE)

            x = normalize_batch_dinov3(
                x
            )

            feats = forward_with_block_features(
                model,
                x,
                DINOV3_LAYER_IDS,
            )

            for layer, feat in feats.items():

                spatial = (
                    feature_tensor_to_spatial_map(
                        feat
                    )
                )

                spatial = F.normalize(
                    spatial.float(),
                    dim=1,
                    eps=1e-12,
                )

                local_rows = (
                    sample_rows_per_tile(
                        spatial[0::2],
                        PATCH_SAMPLES_PER_TILE_PER_VIEW,
                        patch_gen,
                    )
                )

                context_rows = (
                    sample_rows_per_tile(
                        spatial[1::2],
                        PATCH_SAMPLES_PER_TILE_PER_VIEW,
                        patch_gen,
                    )
                )

                reservoirs[
                    (
                        layer,
                        "local",
                    )
                ].add(
                    local_rows
                )

                reservoirs[
                    (
                        layer,
                        "context",
                    )
                ].add(
                    context_rows
                )

    out = {
        "category": category,
        "model": DINOV3_MODEL,
        "checkpoint_sha256": actual_sha256,
        "layers": RESOLVED_LAYERS,
        "local_tile_size": LOCAL_TILE_SIZE,
        "local_overlap": LOCAL_OVERLAP,
        "context_size": CONTEXT_SIZE,
        "context_out_size": CONTEXT_OUT_SIZE,
        "n_train_images": len(ds_train),
        "n_tiles": n_tiles_total,
        "fast_dev_run": False,
        "prototypes": {},
        "meta": {},
    }

    for layer in RESOLVED_LAYERS:

        out["prototypes"][
            layer
        ] = {}

        out["meta"][
            layer
        ] = {}

        for view in [
            "local",
            "context",
        ]:

            reservoir = reservoirs[
                (
                    layer,
                    view,
                )
            ]

            fit_x = reservoir.tensor()

            # LƯU sampled DINOv3 features .npz
            save_feature_cache(
                category,
                layer,
                view,
                fit_x,
            )

            centers, inertia = (
                fit_spherical_prototypes(
                    fit_x,
                    n_prototypes=N_PROTOTYPES,
                    seed=SEED + layer,
                )
            )

            norm_err = float(
                (
                    centers.norm(dim=1)
                    - 1.0
                )
                .abs()
                .max()
            )

            assert norm_err < 1e-4

            out["prototypes"][
                layer
            ][view] = centers

            out["meta"][
                layer
            ][view] = {
                "seen_patch_samples": int(
                    reservoir.seen
                ),
                "fit_patch_samples": int(
                    fit_x.shape[0]
                ),
                "n_prototypes": int(
                    centers.shape[0]
                ),
                "dim": int(
                    centers.shape[1]
                ),
                "kmeans_inertia": inertia,
                "max_prototype_norm_error": norm_err,
                "source": "frozen_dinov3",
            }

    local_pt = Path(
        f"/content/{category}_bank.pt"
    )

    torch.save(
        out,
        local_pt,
    )

    dst = resolve_bank_path(
        category
    )

    copy_atomic_to_drive(
        local_pt,
        dst,
    )

    local_pt.unlink(
        missing_ok=True
    )

    return dst


# =====================================================================
# 13. ANOMALY SCORING
# =====================================================================

def spatial_score_against_prototypes(
    spatial_bchw,
    prototypes_kc,
):

    B, C, h, w = (
        spatial_bchw.shape
    )

    q = (
        spatial_bchw
        .permute(
            0,
            2,
            3,
            1,
        )
        .reshape(
            B,
            h * w,
            C,
        )
        .float()
    )

    q = F.normalize(
        q,
        dim=-1,
        eps=1e-12,
    )

    p = F.normalize(
        prototypes_kc
        .float()
        .to(
            q.device
        ),
        dim=1,
        eps=1e-12,
    )

    sim = torch.matmul(
        q,
        p.T,
    )

    max_cos = sim.amax(
        dim=-1
    )

    score = (
        0.5
        * (
            1.0
            - max_cos
        )
    )

    return (
        score
        .clamp(
            0,
            1,
        )
        .reshape(
            B,
            h,
            w,
        )
    )


def context_map_to_local_fov(
    context_map_bhw,
):

    B, H, W = (
        context_map_bhw.shape
    )

    ratio = (
        LOCAL_TILE_SIZE
        / CONTEXT_SIZE
    )

    theta = torch.tensor(
        [
            [
                ratio,
                0.0,
                0.0,
            ],
            [
                0.0,
                ratio,
                0.0,
            ],
        ],
        dtype=context_map_bhw.dtype,
        device=context_map_bhw.device,
    )[None].repeat(
        B,
        1,
        1,
    )

    grid = F.affine_grid(
        theta,
        size=(
            B,
            1,
            LOCAL_TILE_SIZE,
            LOCAL_TILE_SIZE,
        ),
        align_corners=False,
    )

    return F.grid_sample(
        context_map_bhw[:, None],
        grid,
        mode="bilinear",
        padding_mode="border",
        align_corners=False,
    )[:, 0]


@torch.no_grad()
def score_native_image(
    sample,
    bank,
):

    model = ensure_dinov3()

    image = sample["image"]

    H, W = (
        image.shape[-2:]
    )

    records = generate_tile_records(
        H,
        W,
        local_size=LOCAL_TILE_SIZE,
        overlap=LOCAL_OVERLAP,
        context_size=CONTEXT_SIZE,
    )

    tile_maps = []

    for start in range(
        0,
        len(records),
        PAIR_BATCH_SIZE,
    ):

        chunk = records[
            start:
            start + PAIR_BATCH_SIZE
        ]

        pair = []

        for rec in chunk:

            local_img, context_img = (
                extract_local_context(
                    image,
                    rec,
                    local_out_size=LOCAL_TILE_SIZE,
                    context_out_size=CONTEXT_OUT_SIZE,
                )
            )

            pair.extend(
                [
                    local_img,
                    context_img,
                ]
            )

        x = torch.stack(
            pair
        ).to(DEVICE)

        x = normalize_batch_dinov3(
            x
        )

        feats = forward_with_block_features(
            model,
            x,
            DINOV3_LAYER_IDS,
        )

        local_layer_scores = []
        context_layer_scores = []

        for layer, feat in feats.items():

            spatial = (
                feature_tensor_to_spatial_map(
                    feat
                )
            )

            local_s = (
                spatial_score_against_prototypes(
                    spatial[0::2],
                    bank[
                        "prototypes"
                    ][layer][
                        "local"
                    ],
                )
            )

            context_s = (
                spatial_score_against_prototypes(
                    spatial[1::2],
                    bank[
                        "prototypes"
                    ][layer][
                        "context"
                    ],
                )
            )

            local_s = F.interpolate(
                local_s[:, None],
                size=(
                    LOCAL_TILE_SIZE,
                    LOCAL_TILE_SIZE,
                ),
                mode="bilinear",
                align_corners=False,
            )[:, 0]

            context_s = F.interpolate(
                context_s[:, None],
                size=(
                    CONTEXT_OUT_SIZE,
                    CONTEXT_OUT_SIZE,
                ),
                mode="bilinear",
                align_corners=False,
            )[:, 0]

            context_s = (
                context_map_to_local_fov(
                    context_s
                )
            )

            local_layer_scores.append(
                local_s
            )

            context_layer_scores.append(
                context_s
            )

        local_score = torch.stack(
            local_layer_scores,
            dim=0,
        ).mean(
            dim=0
        )

        context_score = torch.stack(
            context_layer_scores,
            dim=0,
        ).mean(
            dim=0
        )

        fused = (
            0.5 * local_score
            + 0.5 * context_score
        ).clamp(
            0,
            1,
        )

        tile_maps.extend(
            [
                m.detach().cpu()
                for m in fused
            ]
        )

    stitched = stitch_tiles_hann(
        tile_maps,
        records,
        out_hw=(
            H,
            W,
        ),
        local_size=LOCAL_TILE_SIZE,
    ).float().clamp(
        0,
        1,
    )

    assert stitched.shape == (
        H,
        W,
    )

    assert torch.isfinite(
        stitched
    ).all()

    return (
        stitched,
        records,
    )


# =====================================================================
# 14. MAIN PASS
#
# Mỗi category:
#   extract
#   -> kiểm tra bank
#   -> nếu cần mới rebuild
#   -> duyệt từng sample
#   -> file hợp lệ SKIP
#   -> file thiếu mới inference
#   -> cleanup category
# =====================================================================

score_manifest_rows = []
score_audit_rows = []
errors = []

total_existing = 0
total_computed = 0
total_invalid = 0
total_expected = 0

print("\n")
print("=" * 80)
print("START WEEK 3 ARTIFACT RESUME")
print("=" * 80)

for category in CATEGORIES:

    print("\n")
    print("#" * 80)
    print(
        f"CATEGORY: {category}"
    )
    print("#" * 80)

    try:

        # -----------------------------------------------------
        # Extract đúng 1 category
        # -----------------------------------------------------

        extract_category(
            category
        )

        # -----------------------------------------------------
        # Train dataset
        # -----------------------------------------------------

        ds_train = (
            MVTecAD2HighResDataset(
                DATA_ROOT,
                split="train",
                categories=[
                    category
                ],
            )
        )

        # -----------------------------------------------------
        # BANK
        # -----------------------------------------------------

        bank_path = resolve_bank_path(
            category
        )

        if bank_valid(
            bank_path,
            category,
        ):

            print(
                f"[SKIP W3.1] Valid bank: {bank_path.name}"
            )

            if (
                not all_feature_cache_available(
                    category
                )
            ):

                print(
                    "  Optional .npz cache chưa đủ."
                )

                if not REBUILD_OPTIONAL_NPZ_IF_BANK_EXISTS:

                    print(
                        "  -> Không chạy DINOv3 lại chỉ để tạo cache."
                    )

        else:

            print(
                f"[MISSING/INVALID BANK] {category}"
            )

            # Ưu tiên dùng npz để không chạy DINO
            if all_feature_cache_available(
                category
            ):

                bank_path = (
                    rebuild_bank_from_npz(
                        category,
                        ds_train,
                    )
                )

            else:

                bank_path = (
                    build_bank_from_dinov3(
                        category,
                        ds_train,
                    )
                )

        assert bank_valid(
            bank_path,
            category,
        )

        bank = torch.load(
            bank_path,
            map_location="cpu",
            weights_only=False,
        )

        # -----------------------------------------------------
        # SCORE SPLITS
        # -----------------------------------------------------

        for split in SCORE_SPLITS:

            try:

                ds = (
                    MVTecAD2HighResDataset(
                        DATA_ROOT,
                        split=split,
                        categories=[
                            category
                        ],
                    )
                )

            except RuntimeError:

                print(
                    f"Skip empty split: {category}/{split}"
                )

                continue

            split_root = (
                SCORE_DIR
                / split
            )

            out_dir = (
                resolve_existing_category_dir(
                    split_root,
                    category,
                )
            )

            out_dir.mkdir(
                parents=True,
                exist_ok=True,
            )

            expected = len(ds)
            existing_valid = 0
            computed = 0
            invalid_replaced = 0

            total_expected += (
                expected
            )

            for i in tqdm(
                range(len(ds)),
                desc=(
                    f"Audit/Score | "
                    f"{category} | {split}"
                ),
            ):

                sample = ds[i]
                meta = sample["meta"]

                H = int(
                    meta["H"]
                )

                W = int(
                    meta["W"]
                )

                sid = sample_id_from_meta(
                    meta
                )

                npy_path = (
                    out_dir
                    / f"{sid}.npy"
                )

                # ---------------------------------------------
                # SKIP nếu đã tồn tại và hợp lệ
                # ---------------------------------------------

                if score_file_valid(
                    npy_path,
                    H,
                    W,
                ):

                    existing_valid += 1
                    total_existing += 1

                    n_tiles = len(
                        generate_tile_records(
                            H,
                            W,
                            local_size=LOCAL_TILE_SIZE,
                            overlap=LOCAL_OVERLAP,
                            context_size=CONTEXT_SIZE,
                        )
                    )

                    score_manifest_rows.append({
                        "category": category,
                        "split": split,
                        "index": i,
                        "sample_id": sid,
                        "image_path": meta["path"],
                        "H": H,
                        "W": W,
                        "n_tiles": n_tiles,
                        "runtime_s": np.nan,
                        "peak_vram_mb": np.nan,
                        "score_min": np.nan,
                        "score_max": np.nan,
                        "score_mean": np.nan,
                        "finite": True,
                        "score_path": str(
                            npy_path
                        ),
                        "has_gt_mask": (
                            sample["mask"]
                            is not None
                        ),
                        "status": "existing_valid",
                    })

                    continue

                # ---------------------------------------------
                # Nếu tồn tại nhưng lỗi -> xóa
                # ---------------------------------------------

                if npy_path.exists():

                    print(
                        "\nInvalid/truncated -> replace:",
                        npy_path.name,
                    )

                    npy_path.unlink()

                    invalid_replaced += 1
                    total_invalid += 1

                # ---------------------------------------------
                # CHỈ Ở ĐÂY MỚI CHẠY DINOv3
                # ---------------------------------------------

                if DEVICE.type == "cuda":

                    torch.cuda.synchronize()
                    torch.cuda.reset_peak_memory_stats()

                t0 = time.perf_counter()

                amap, records = (
                    score_native_image(
                        sample,
                        bank,
                    )
                )

                if DEVICE.type == "cuda":
                    torch.cuda.synchronize()

                elapsed = (
                    time.perf_counter()
                    - t0
                )

                peak_vram_mb = (
                    torch.cuda.max_memory_allocated()
                    / 1024**2
                )

                amap_np = (
                    amap
                    .detach()
                    .cpu()
                    .numpy()
                    .astype(
                        np.float32
                    )
                )

                assert amap_np.shape == (
                    H,
                    W,
                )

                assert np.isfinite(
                    amap_np
                ).all()

                # ---------------------------------------------
                # Save LOCAL TEMP trước
                # ---------------------------------------------

                local_npy = Path(
                    f"/content/"
                    f"_score_{category}_{split}_{i}.npy"
                )

                np.save(
                    local_npy,
                    amap_np,
                )

                # ---------------------------------------------
                # Sau đó atomic copy vào SAME W3 Drive folder
                # ---------------------------------------------

                copy_atomic_to_drive(
                    local_npy,
                    npy_path,
                )

                local_npy.unlink(
                    missing_ok=True
                )

                assert score_file_valid(
                    npy_path,
                    H,
                    W,
                )

                computed += 1
                total_computed += 1

                score_manifest_rows.append({
                    "category": category,
                    "split": split,
                    "index": i,
                    "sample_id": sid,
                    "image_path": meta["path"],
                    "H": H,
                    "W": W,
                    "n_tiles": len(
                        records
                    ),
                    "runtime_s": elapsed,
                    "peak_vram_mb": peak_vram_mb,
                    "score_min": float(
                        amap_np.min()
                    ),
                    "score_max": float(
                        amap_np.max()
                    ),
                    "score_mean": float(
                        amap_np.mean()
                    ),
                    "finite": True,
                    "score_path": str(
                        npy_path
                    ),
                    "has_gt_mask": (
                        sample["mask"]
                        is not None
                    ),
                    "status": "computed_now",
                })

            # -------------------------------------------------
            # Final verify count của split
            # -------------------------------------------------

            valid_after = 0

            for i in range(
                len(ds)
            ):

                sample = ds[i]
                meta = sample["meta"]

                sid = sample_id_from_meta(
                    meta
                )

                p = (
                    out_dir
                    / f"{sid}.npy"
                )

                if score_file_valid(
                    p,
                    int(
                        meta["H"]
                    ),
                    int(
                        meta["W"]
                    ),
                ):
                    valid_after += 1

            missing_after = (
                expected
                - valid_after
            )

            score_audit_rows.append({
                "category": category,
                "split": split,
                "expected": expected,
                "existing_valid_before": existing_valid,
                "computed_now": computed,
                "invalid_replaced": invalid_replaced,
                "valid_after": valid_after,
                "missing_after": missing_after,
            })

            print(
                f"\n{category}/{split}: "
                f"expected={expected}, "
                f"existing={existing_valid}, "
                f"computed={computed}, "
                f"valid_after={valid_after}, "
                f"missing={missing_after}"
            )

        # -----------------------------------------------------
        # Save audit ngay sau mỗi category
        # để nếu Colab disconnect thì report vẫn còn
        # -----------------------------------------------------

        pd.DataFrame(
            score_audit_rows
        ).to_csv(
            W3_OUTPUT_DIR
            / "resume_score_audit.csv",
            index=False,
        )

    except Exception as e:

        errors.append({
            "category": category,
            "error": repr(e),
        })

        print(
            "\nERROR CATEGORY:",
            category,
        )
        print(
            repr(e)
        )

    finally:

        # -----------------------------------------------------
        # Chỉ giữ 1 category local
        # -----------------------------------------------------

        cleanup_category(
            category
        )


# =====================================================================
# 15. REBUILD NORMAL REPRESENTATION MANIFEST
# =====================================================================

rep_rows = []

for category in CATEGORIES:

    bank_path = resolve_bank_path(
        category
    )

    if not bank_valid(
        bank_path,
        category,
    ):
        continue

    bank = torch.load(
        bank_path,
        map_location="cpu",
        weights_only=False,
    )

    for layer in bank["layers"]:

        for view in [
            "local",
            "context",
        ]:

            meta = bank[
                "meta"
            ][layer][view]

            rep_rows.append({
                "category": category,
                "layer": layer,
                "view": view,
                **meta,
                "n_train_images": bank.get(
                    "n_train_images",
                    np.nan,
                ),
                "n_tiles": bank.get(
                    "n_tiles",
                    np.nan,
                ),
            })

rep_manifest = pd.DataFrame(
    rep_rows
)

rep_manifest.to_csv(
    REP_DIR
    / "manifest.csv",
    index=False,
)


# =====================================================================
# 16. REBUILD SCORE MANIFEST
# =====================================================================

score_manifest = pd.DataFrame(
    score_manifest_rows
)

if len(score_manifest):

    score_manifest = (
        score_manifest
        .sort_values(
            [
                "category",
                "split",
                "index",
            ]
        )
        .drop_duplicates(
            subset=[
                "category",
                "split",
                "sample_id",
            ],
            keep="last",
        )
        .reset_index(
            drop=True
        )
    )

score_manifest.to_csv(
    SCORE_DIR
    / "manifest.csv",
    index=False,
)

score_audit = pd.DataFrame(
    score_audit_rows
)

score_audit.to_csv(
    W3_OUTPUT_DIR
    / "resume_score_audit.csv",
    index=False,
)

if errors:

    pd.DataFrame(
        errors
    ).to_csv(
        W3_OUTPUT_DIR
        / "resume_errors.csv",
        index=False,
    )


# =====================================================================
# 17. KIỂM TRA TOÀN BỘ SCORING ĐÃ XONG CHƯA
# =====================================================================

if len(score_audit):

    FINAL_MISSING = int(
        score_audit[
            "missing_after"
        ].sum()
    )

else:

    FINAL_MISSING = 999999


print("\n")
print("=" * 80)
print("SCORING SUMMARY")
print("=" * 80)

print(
    "Expected samples :",
    total_expected,
)

print(
    "Existing skipped:",
    total_existing,
)

print(
    "Computed now    :",
    total_computed,
)

print(
    "Invalid replaced:",
    total_invalid,
)

print(
    "Missing after   :",
    FINAL_MISSING,
)


# =====================================================================
# 18. PREVIEW PASS
#
# CHỈ chạy khi toàn bộ .npy đã hoàn tất.
# Không chạy DINOv3.
# Re-extract từng category -> tạo preview -> cleanup.
# =====================================================================

if (
    FINAL_MISSING == 0
    and not errors
    and REGENERATE_PREVIEWS
):

    print("\n")
    print("=" * 80)
    print("ALL SCORE MAPS COMPLETE")
    print("REGENERATING PREVIEWS")
    print("=" * 80)

    import matplotlib.pyplot as plt

    total_previews = 0

    for category in CATEGORIES:

        try:

            extract_category(
                category
            )

            for split in SCORE_SPLITS:

                try:

                    ds = (
                        MVTecAD2HighResDataset(
                            DATA_ROOT,
                            split=split,
                            categories=[
                                category
                            ],
                        )
                    )

                except RuntimeError:
                    continue

                out_dir = (
                    resolve_existing_category_dir(
                        SCORE_DIR
                        / split,
                        category,
                    )
                )

                count = 0

                for i in range(
                    len(ds)
                ):

                    if (
                        count
                        >= N_PREVIEW_PER_CATEGORY_SPLIT
                    ):
                        break

                    sample = ds[i]
                    meta = sample["meta"]

                    sid = sample_id_from_meta(
                        meta
                    )

                    npy_path = (
                        out_dir
                        / f"{sid}.npy"
                    )

                    if not score_file_valid(
                        npy_path,
                        int(
                            meta["H"]
                        ),
                        int(
                            meta["W"]
                        ),
                    ):
                        continue

                    amap = np.load(
                        npy_path,
                        mmap_mode="r",
                    )

                    ncols = (
                        3
                        if sample["mask"]
                        is not None
                        else 2
                    )

                    fig, axes = plt.subplots(
                        1,
                        ncols,
                        figsize=(
                            4 * ncols,
                            4,
                        ),
                    )

                    axes = np.atleast_1d(
                        axes
                    )

                    axes[0].imshow(
                        sample["image"]
                        .permute(
                            1,
                            2,
                            0,
                        )
                        .numpy()
                    )

                    axes[0].set_title(
                        "Native image"
                    )

                    axes[1].imshow(
                        amap,
                        cmap="magma",
                        vmin=0,
                        vmax=1,
                    )

                    axes[1].set_title(
                        "Frozen DINOv3 soft score"
                    )

                    if (
                        sample["mask"]
                        is not None
                    ):

                        axes[2].imshow(
                            sample[
                                "mask"
                            ].numpy(),
                            cmap="gray",
                        )

                        axes[2].set_title(
                            "GT mask"
                        )

                    for ax in axes:
                        ax.axis(
                            "off"
                        )

                    plt.tight_layout()

                    local_png = Path(
                        f"/content/"
                        f"_preview_{category}_{split}_{i}.png"
                    )

                    fig.savefig(
                        local_png,
                        dpi=130,
                        bbox_inches="tight",
                    )

                    plt.close(fig)

                    dst_png = (
                        out_dir
                        / f"{sid}_preview.png"
                    )

                    copy_atomic_to_drive(
                        local_png,
                        dst_png,
                    )

                    local_png.unlink(
                        missing_ok=True
                    )

                    count += 1
                    total_previews += 1

            print(
                f"Preview complete: {category}"
            )

        finally:

            cleanup_category(
                category
            )

    print(
        "Total preview PNG:",
        total_previews,
    )

elif FINAL_MISSING != 0:

    print(
        "\nPreview chưa được tạo lại vì scoring vẫn còn thiếu:",
        FINAL_MISSING,
    )

elif errors:

    print(
        "\nPreview chưa chạy vì có category error."
    )


# =====================================================================
# 19. FINAL ARTIFACT AUDIT
# =====================================================================

npy_files = list(
    SCORE_DIR.rglob(
        "*.npy"
    )
)

npz_files = list(
    NORMAL_FEATURE_DIR.glob(
        "*.npz"
    )
)

pt_files = list(
    REP_DIR.glob(
        "*.pt"
    )
)

preview_files = list(
    SCORE_DIR.rglob(
        "*_preview.png"
    )
)


print("\n")
print("=" * 80)
print("FINAL WEEK 3 DRIVE AUDIT")
print("=" * 80)

print(
    ".pt prototype banks :",
    len(pt_files),
)

print(
    ".npz normal features:",
    len(npz_files),
)

print(
    ".npy score maps     :",
    len(npy_files),
)

print(
    "preview PNG         :",
    len(preview_files),
)

print(
    "score manifest      :",
    SCORE_DIR
    / "manifest.csv",
)

print(
    "normal manifest     :",
    REP_DIR
    / "manifest.csv",
)

print(
    "resume audit        :",
    W3_OUTPUT_DIR
    / "resume_score_audit.csv",
)


# =====================================================================
# 20. SCORE MAP COUNTS BY SPLIT / CATEGORY
# =====================================================================

print("\nScore-map counts:")

for split in SCORE_SPLITS:

    split_root = (
        SCORE_DIR
        / split
    )

    if not split_root.exists():
        continue

    for category in CATEGORIES:

        d = (
            resolve_existing_category_dir(
                split_root,
                category,
            )
        )

        if not d.exists():
            n = 0
        else:
            n = len(
                list(
                    d.glob(
                        "*.npy"
                    )
                )
            )

        print(
            f"{split:20s} "
            f"{category:15s}: "
            f"{n}"
        )


# =====================================================================
# 21. FINAL STATUS
# =====================================================================

if (
    FINAL_MISSING == 0
    and not errors
):

    print("\n")
    print("=" * 80)
    print("FROZEN DINOv3 WEEK 3 RESUME: PASS")
    print("=" * 80)

    print(
        "Các artifact đã có được SKIP."
    )

    print(
        "Chỉ artifact thiếu/hỏng được tính lại."
    )

    print(
        "Tất cả output mới đã được ghi trực tiếp vào:"
    )

    print(
        W3_OUTPUT_DIR
    )

else:

    print("\n")
    print("=" * 80)
    print("WEEK 3 RESUME: INCOMPLETE")
    print("=" * 80)

    print(
        "Missing:",
        FINAL_MISSING,
    )

    print(
        "Errors:",
        len(errors),
    )

    if errors:

        for e in errors:
            print(
                " -",
                e,
            )

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
================================================================================
WEEK 3 RESUME
================================================================================
TEAM_ROOT : /content/drive/MyDrive/[Q3-4] 2026/[S7] Computer Vision/CV-Nhóm 9
W3 OUTPUT : /content/drive/MyDrive/[Q3-4] 2026/[S7] Computer Vision/CV-Nhóm 9/outputs/week03_20260913_103652
DATA      : /content/drive/MyDrive/[Q3-4] 2026/[S7] Computer Vision/CV-Nhóm 9/data
WEIGHTS   : /content/drive/MyDrive/[Q3-4] 2026/[S7] Computer Vision/CV-Nhóm 9/weights/dinov3_vits16_pretrain_lvd1689m.pth
DEVICE    : cuda

Cloning MS-ILA...
Repo yêu cầu quyền GitHub.
Nhập GitHub PAT (input sẽ bị ẩn): ··········

Categories: ['walnuts']
N categories: 1
WARNING: Không phát hiện đúng 8 archives. Cell vẫn chạy trên những category tìm được.


================================================================================
START WEEK 3 ARTIFACT RESUME
================================================================================


################################################################################
CATEGORY: walnuts
################################################################################

Extract directly Drive -> SSD: walnuts.tar.gz
[SKIP W3.1] Valid bank: walnuts.pt

Audit/Score | walnuts | test_private:   0%|          | 0/228 [00:00<?, ?it/s]

walnuts/test_private: expected=228, existing=228, computed=0, valid_after=228, missing=0

Audit/Score | walnuts | test_private_mixed:   0%|          | 0/228 [00:00<?, ?it/s]

Missing artifact detected -> loading Frozen DINOv3...
Checkpoint SHA256: 08c60483bc63c04f533611e34bf70b120eedb7240f469bc16e9e20bf344b941d
Clone official DINOv3...
Downloading: "file:///content/drive/.shortcut-targets-by-id/1mvaRCk65c_A7D8iYJyYGy2fo7z_hiJO6/%5BQ3-4%5D%202026/%5BS7%5D%20Computer%20Vision/CV-Nho%CC%81m%209/weights/dinov3_vits16_pretrain_lvd1689m.pth" to /root/.cache/torch/hub/checkpoints/dinov3_vits16_pretrain_lvd1689m.pth

100%|██████████| 82.5M/82.5M [00:00<00:00, 1.19GB/s]

Frozen DINOv3 loaded.
Layers: [8, 10, 11]

walnuts/test_private_mixed: expected=228, existing=122, computed=106, valid_after=228, missing=0
Cleanup local dataset: walnuts


================================================================================
SCORING SUMMARY
================================================================================
Expected samples : 456
Existing skipped: 350
Computed now    : 106
Invalid replaced: 0
Missing after   : 0


================================================================================
ALL SCORE MAPS COMPLETE
REGENERATING PREVIEWS
================================================================================

Extract directly Drive -> SSD: walnuts.tar.gz
Preview complete: walnuts
Cleanup local dataset: walnuts
Total preview PNG: 10


================================================================================
FINAL WEEK 3 DRIVE AUDIT
================================================================================
.pt prototype banks : 8
.npz normal features: 48
.npy score maps     : 5476
preview PNG         : 40
score manifest      : /content/drive/MyDrive/[Q3-4] 2026/[S7] Computer Vision/CV-Nhóm 9/outputs/week03_20260913_103652/score_maps/manifest.csv
normal manifest     : /content/drive/MyDrive/[Q3-4] 2026/[S7] Computer Vision/CV-Nhóm 9/outputs/week03_20260913_103652/normal_representation/manifest.csv
resume audit        : /content/drive/MyDrive/[Q3-4] 2026/[S7] Computer Vision/CV-Nhóm 9/outputs/week03_20260913_103652/resume_score_audit.csv

Score-map counts:
test_private         walnuts        : 228
test_private_mixed   walnuts        : 228


================================================================================
FROZEN DINOv3 WEEK 3 RESUME: PASS
================================================================================
Các artifact đã có được SKIP.
Chỉ artifact thiếu/hỏng được tính lại.
Tất cả output mới đã được ghi trực tiếp vào:
/content/drive/MyDrive/[Q3-4] 2026/[S7] Computer Vision/CV-Nhóm 9/outputs/week03_20260913_103652

# Fix out of memories

In [ ]:
# # ============================================================
# # W3.2.4 — RESUME full scoring run
# # Skip .npy hợp lệ, chỉ chạy sample còn thiếu / bị corrupt
# # TẠM THỜI KHÔNG SINH PREVIEW PNG
# # ============================================================

# from pathlib import Path
# import hashlib
# import time
# import numpy as np
# import pandas as pd
# import torch
# from tqdm.auto import tqdm

# def sample_id_from_meta(meta):
#     p = Path(meta["path"])
#     token = hashlib.sha1(str(p).encode("utf-8")).hexdigest()[:10]
#     return f"{p.stem}_{token}"


# def valid_score_file(path: Path, H: int, W: int):
#     """
#     True nếu .npy tồn tại, đọc được, đúng shape và finite.
#     Dùng mmap để không load toàn bộ ảnh vào RAM.
#     """
#     if not path.exists():
#         return False

#     try:
#         arr = np.load(path, mmap_mode="r")

#         if arr.shape != (H, W):
#             return False

#         if not np.isfinite(arr).all():
#             return False

#         return True

#     except Exception:
#         return False


# score_rows = []

# n_skipped = 0
# n_computed = 0
# n_corrupt_removed = 0

# for category in PILOT_CATEGORIES:

#     bank_path = REP_DIR / f"{category}.pt"

#     assert bank_path.exists(), (
#         f"Missing prototype bank: {bank_path}"
#     )

#     bank = torch.load(
#         bank_path,
#         map_location="cpu",
#     )

#     assert bank["category"] == category
#     assert bank["checkpoint_sha256"] == sha256

#     for split in SCORE_SPLITS:

#         try:
#             ds = MVTecAD2HighResDataset(
#                 DATA_ROOT,
#                 split=split,
#                 categories=[category],
#             )

#         except RuntimeError:
#             print(f"Skip empty split: {category}/{split}")
#             continue

#         indices = list(range(len(ds)))

#         if FAST_DEV_RUN:
#             indices = indices[
#                 :DEV_MAX_SCORE_IMAGES_PER_CATEGORY_SPLIT
#             ]

#         out_dir = SCORE_DIR / split / category
#         out_dir.mkdir(
#             parents=True,
#             exist_ok=True,
#         )

#         for i in tqdm(
#             indices,
#             desc=f"Score | {category} | {split}"
#         ):

#             sample = ds[i]
#             meta = sample["meta"]

#             H = int(meta["H"])
#             W = int(meta["W"])

#             sid = sample_id_from_meta(meta)

#             npy_path = out_dir / f"{sid}.npy"

#             # ==================================================
#             # RESUME
#             # ==================================================
#             if npy_path.exists():

#                 if valid_score_file(
#                     npy_path,
#                     H,
#                     W,
#                 ):
#                     arr = np.load(
#                         npy_path,
#                         mmap_mode="r",
#                     )

#                     score_rows.append({
#                         "category": category,
#                         "split": split,
#                         "index": i,
#                         "sample_id": sid,
#                         "image_path": meta["path"],
#                         "H": H,
#                         "W": W,

#                         # n_tiles/runtime không còn biết
#                         # nếu file đến từ run trước
#                         "n_tiles": np.nan,
#                         "runtime_s": np.nan,
#                         "peak_vram_mb": np.nan,

#                         "score_min": float(arr.min()),
#                         "score_max": float(arr.max()),
#                         "score_mean": float(arr.mean()),

#                         "finite": True,
#                         "score_path": str(npy_path),
#                         "has_gt_mask": (
#                             sample["mask"] is not None
#                         ),

#                         "status": "existing",
#                     })

#                     n_skipped += 1
#                     continue

#                 else:
#                     print(
#                         "Remove invalid/corrupt:",
#                         npy_path
#                     )

#                     npy_path.unlink(
#                         missing_ok=True
#                     )

#                     n_corrupt_removed += 1

#             # ==================================================
#             # COMPUTE ONLY MISSING SAMPLE
#             # ==================================================
#             if DEVICE.type == "cuda":
#                 torch.cuda.synchronize()
#                 torch.cuda.reset_peak_memory_stats()

#             t0 = time.perf_counter()

#             amap, records = (
#                 score_native_image_frozen_dinov3(
#                     sample,
#                     bank,
#                     pair_batch_size=PAIR_BATCH_SIZE,
#                 )
#             )

#             if DEVICE.type == "cuda":
#                 torch.cuda.synchronize()

#             elapsed = (
#                 time.perf_counter()
#                 - t0
#             )

#             peak_vram_mb = (
#                 torch.cuda.max_memory_allocated()
#                 / 1024**2
#                 if DEVICE.type == "cuda"
#                 else np.nan
#             )

#             # CPU numpy
#             amap_np = (
#                 amap
#                 .detach()
#                 .cpu()
#                 .numpy()
#                 .astype(np.float32)
#             )

#             assert amap_np.shape == (H, W)
#             assert np.isfinite(amap_np).all()

#             # Atomic-ish save:
#             # ghi temp trước rồi rename
#             tmp_path = npy_path.with_suffix(".tmp.npy")

#             np.save(
#                 tmp_path,
#                 amap_np,
#             )

#             tmp_path.replace(
#                 npy_path
#             )

#             score_rows.append({
#                 "category": category,
#                 "split": split,
#                 "index": i,
#                 "sample_id": sid,
#                 "image_path": meta["path"],
#                 "H": H,
#                 "W": W,
#                 "n_tiles": len(records),
#                 "runtime_s": elapsed,
#                 "peak_vram_mb": peak_vram_mb,
#                 "score_min": float(amap_np.min()),
#                 "score_max": float(amap_np.max()),
#                 "score_mean": float(amap_np.mean()),
#                 "finite": True,
#                 "score_path": str(npy_path),
#                 "has_gt_mask": (
#                     sample["mask"] is not None
#                 ),
#                 "status": "computed",
#             })

#             n_computed += 1


# # ============================================================
# # SAVE MANIFEST
# # ============================================================

# score_manifest = pd.DataFrame(score_rows)

# score_manifest = (
#     score_manifest
#     .sort_values([
#         "category",
#         "split",
#         "index",
#     ])
#     .reset_index(drop=True)
# )

# manifest_path = (
#     SCORE_DIR
#     / "manifest.csv"
# )

# score_manifest.to_csv(
#     manifest_path,
#     index=False,
# )

# display(
#     score_manifest.head(20)
# )

# print()
# print("Existing valid :", n_skipped)
# print("New computed   :", n_computed)
# print("Corrupt removed:", n_corrupt_removed)
# print("Total rows     :", len(score_manifest))

# # ============================================================
# # QA
# # ============================================================

# assert len(score_manifest) > 0
# assert score_manifest["finite"].all()

# assert (
#     score_manifest["score_min"]
#     >= -1e-6
# ).all()

# assert (
#     score_manifest["score_max"]
#     <= 1.0 + 1e-6
# ).all()

# for (
#     category,
#     split
# ), g in score_manifest.groupby(
#     ["category", "split"]
# ):

#     r = g.iloc[0]

#     arr = np.load(
#         r["score_path"],
#         mmap_mode="r",
#     )

#     assert arr.shape == (
#         int(r["H"]),
#         int(r["W"]),
#     )

#     assert np.isfinite(
#         arr
#     ).all()

# WEEK3_STATUS["anomaly_scoring"] = (
#     "DEV_PASS"
#     if FAST_DEV_RUN
#     else "PASS"
# )

# print(
#     "\nFrozen DINOv3 anomaly scoring:",
#     WEEK3_STATUS["anomaly_scoring"],
# )

# print(
#     "Score maps:",
#     SCORE_DIR,
# )

In [ ]:
# # ============================================================
# # W3.2.5 — Regenerate preview PNGs AFTER scoring complete
# # Không chạy DINOv3 lại
# # ============================================================

# import matplotlib.pyplot as plt
# import numpy as np
# from pathlib import Path
# from tqdm.auto import tqdm

# N_PREVIEW_PER_CATEGORY_SPLIT = 5

# n_created = 0

# for category in PILOT_CATEGORIES:

#     for split in SCORE_SPLITS:

#         try:
#             ds = MVTecAD2HighResDataset(
#                 DATA_ROOT,
#                 split=split,
#                 categories=[category],
#             )

#         except RuntimeError:
#             print(
#                 f"Skip empty split: "
#                 f"{category}/{split}"
#             )
#             continue

#         out_dir = (
#             SCORE_DIR
#             / split
#             / category
#         )

#         if not out_dir.exists():
#             continue

#         count = 0

#         for i in tqdm(
#             range(len(ds)),
#             desc=f"Preview | {category} | {split}"
#         ):

#             if count >= N_PREVIEW_PER_CATEGORY_SPLIT:
#                 break

#             sample = ds[i]
#             meta = sample["meta"]

#             sid = sample_id_from_meta(
#                 meta
#             )

#             npy_path = (
#                 out_dir
#                 / f"{sid}.npy"
#             )

#             if not npy_path.exists():
#                 continue

#             amap = np.load(
#                 npy_path
#             )

#             assert amap.shape == (
#                 int(meta["H"]),
#                 int(meta["W"]),
#             )

#             ncols = (
#                 3
#                 if sample["mask"] is not None
#                 else 2
#             )

#             fig, axes = plt.subplots(
#                 1,
#                 ncols,
#                 figsize=(4 * ncols, 4),
#             )

#             axes = np.atleast_1d(
#                 axes
#             )

#             axes[0].imshow(
#                 sample["image"]
#                 .permute(1, 2, 0)
#                 .numpy()
#             )

#             axes[0].set_title(
#                 "Native image"
#             )

#             axes[1].imshow(
#                 amap,
#                 cmap="magma",
#                 vmin=0.0,
#                 vmax=1.0,
#             )

#             axes[1].set_title(
#                 "Frozen DINOv3 soft score"
#             )

#             if sample["mask"] is not None:

#                 axes[2].imshow(
#                     sample["mask"].numpy(),
#                     cmap="gray",
#                 )

#                 axes[2].set_title(
#                     "GT mask"
#                 )

#             for ax in axes:
#                 ax.axis("off")

#             plt.tight_layout()

#             preview_path = (
#                 out_dir
#                 / f"{sid}_preview.png"
#             )

#             fig.savefig(
#                 preview_path,
#                 dpi=130,
#                 bbox_inches="tight",
#             )

#             plt.close(fig)

#             count += 1
#             n_created += 1

# print(
#     f"\nCreated {n_created} preview PNGs."
# )

In [ ]:
# from pathlib import Path
# import os

# LOCAL_W3_OUTPUT = PROJECT_ROOT / "outputs" / "week03"

# print("Week 3 output:", LOCAL_W3_OUTPUT)
# print()

# # Prototype banks
# pt_files = list(
#     (LOCAL_W3_OUTPUT / "normal_representation").glob("*.pt")
# )

# # Normal feature cache
# npz_files = list(
#     (LOCAL_W3_OUTPUT / "normal_features").glob("*.npz")
# ) if (LOCAL_W3_OUTPUT / "normal_features").exists() else []

# # Score maps
# npy_files = list(
#     (LOCAL_W3_OUTPUT / "score_maps").rglob("*.npy")
# )

# # Preview
# png_files = list(
#     (LOCAL_W3_OUTPUT / "score_maps").rglob("*_preview.png")
# )

# print("Prototype .pt       :", len(pt_files))
# print("Normal feature .npz :", len(npz_files))
# print("Score map .npy      :", len(npy_files))
# print("Preview PNG         :", len(png_files))

# print("\nScore maps by category/split:")

# score_root = LOCAL_W3_OUTPUT / "score_maps"

# for split_dir in sorted(score_root.iterdir()):
#     if not split_dir.is_dir():
#         continue

#     for category_dir in sorted(split_dir.iterdir()):
#         if not category_dir.is_dir():
#             continue

#         n = len(list(category_dir.glob("*.npy")))

#         print(
#             f"{split_dir.name:20s} "
#             f"{category_dir.name:12s}: {n}"
#         )